- scout/core/templates/variant.html
- scout/ext/backend/utils/get_mongo_variant.py
- scout/models/variant/variant.py
I've added the link and will display the max freq when the variant model is updated, relates to #107
@moonso: I named the fields as "max_" followed by the normal AF frequency name
> add link to 1000G page with detailed freq information (#107)

- scout/commands/load_database.py
- scout/ext/backend/variant_handler.py
Only use rank score treshold when loading variants.
Loop through whole vcf and load all variants that meets the rank score treshold.
Current default is rank score 0.
Fix #329
> Changes load functionality

- scout/utils/link.py
That is, there can still be multiple refseq transcripts per enst.
Before there could be douplicates.
Fix #489
> Refseq ids will only be added once per enst

- scout/adapter/mongo/variant.py
- scout/constants/__init__.py
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/variant.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/utils/par.py
- tests/utils/test_par.py
> Adds functionality to check if a variant is in the PAR regions

- scout/parse/variant/transcript.py
Our VEP-annotated VCFs sometimes contain allele frequencies for multiple alleles like this "A:0.00483&T:0.0001725", which causes "scout load  case" to crash. This should fix that.
> Allows multiple alleles in VEP's MAF-fields, separated by ampersands

- scout/adapter/client.py
- scout/adapter/mongo/case.py
- scout/adapter/mongo/variant.py
- scout/adapter/utils.py
- scout/build/case.py
- scout/commands/base.py
- scout/commands/load/research.py
- scout/commands/view/view_command.py
- scout/demo/643594.config.yaml
- scout/load/case.py
- scout/parse/case.py
- scout/parse/variant/compound.py
- scout/parse/variant/genotype.py
- scout/parse/variant/ids.py
- scout/parse/variant/models.py
- scout/parse/variant/variant.py
- tests/adapter/conftest.py
- tests/adapter/test_adapter_variant_caseid.py
- tests/adapter/test_variant_handling.py
- tests/conftest.py
- tests/load/test_load_case.py
- tests/parse/test_ids.py
- tests/parse/test_parse_case.py
- tests/parse/test_parse_compounds.py
- tests/parse/test_parse_genotype.py
I've added a method that can migrate a case using the `CUSTOMER-FAMILY` syntax over to using a unique family id.
I'm not updating variant documents since I think we should only run this function when we re-upload a case and then all the variants will be deleted either way!
> Support defining a unique family id in the config

- scout/build/panel.py
- scout/commands/load/panel.py
Fixes bug when trying to add gene panel with an hgnc_id which is not in the database. Also adds an error message.
> Bugfix: load panel, hgnc_id not in database

- scout/server/blueprints/cases/templates/cases/actionbar.html
I think this bug might be caused by the fact that the sample_ids are passed to the function as arguments and not as form inputs. I have no way to test it on my local computer because I don't have chanjo-report running. What do you think @moonso ?
> fix #698 , PDF coverage empty

- requirements.txt
In about the next month, Flask-PyMongo 2.0 is going to be released, which is not (necessarily) compatible with 0.x versions. This change will prevent accidental updates, but I'd also be happy to work with you on upgrading safely to 2.0, which will be the base version going forward that will receive compatibility and bug fix improvements, etc.
In particular, it looks like you are configuring with MONGO_HOST, MONGO_DBNAME, etc. To use Flask-PyMongo 2.0, you should convert to using MONGO_URI. It should be pretty straight forward, and I'll be happy to lend a hand if it helps.
> pin flask-pymongo 0.5.2

- scout/server/blueprints/genes/templates/genes/gene.html
- scout/server/blueprints/genes/templates/genes/genes.html
- scout/server/blueprints/panels/templates/panels/panel.html
Mostly useful when, from a case view, you want to check the coverage for a certain gene of a panel. It can be used as a reference for the customized search on the coverage report. Addresses issue #865
> show gene HGNC id in gene, genes, and gene panels pages

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/cases.html
Now you see a small green or yellow label under the clinvar submission column for each snv/sv submitted for a case
> added links for clinvar submitted variants under cases page

- scout/server/blueprints/igv/views.py
Demo version has case.genome_build = '37' while in scout database the reference is named 'GRCh37'
> Modified reference name to match the one in case collection

- scout/server/blueprints/igv/templates/igv_viewer.html
- scout/server/blueprints/igv/views.py
Whenever the variant to visualize is a MT one, use reference genome hg38
> workaround to visualize MT variants in IGV with right MT reference

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variants/templates/variants/sv-variant.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
This way whenever end chromosome is different from start chromosome, end chr is shown in sv_variant and sv_variants pages.
In sv_variant: cytoband becomes [startchr][cytobandstart]-[endchr][cytobandend]
in sv_variants: startchr becomes [startchr]-[endchr]
> Show end_chrom in sv_variant and sv_variants when different from start_chrom

- scout/server/blueprints/variants/templates/variants/sv-variant.html
I removed the alignments view for the breakpoints by mistake when I introduced the IGV viewer! Fix #910 
Since the line was a bit busy I've introduced a left and right breakpoint line. Or should I name them breakpoint 1 and breakpoint 2 instead?
> re-introduced breakpoint alignments for SVs

- scout/server/blueprints/alignviewers/templates/alignviewers/pileup.html
This should prevent the http warnings blocking the pileup alignments during the page loading. See here: http://www.biodalliance.org/https.html
> access biodalliance over the httpS

- scout/server/app.py
The idea is to fix #917.
It is weird that jinja2 extensions are found in scout stage but not in scout production..!
> adding jinja2 'do' extension

- CHANGELOG.md
- scout/adapter/mongo/variant.py
Found a query which was not optimized and fixed it. Instead of returning just the variants for a case that were either ACMG-classified, Manual ranked or dismissed, it returned them all. Later in the code there was a control loop that was potentially quite slow. 
This way the report page should be faster to load
> Speed up query for creating case report, fix #984 

- scout/server/blueprints/cases/controllers.py
There is a problem with the demo data having case._id = 'internal_id'. I just noticed it!
> use case_id when collecting clinvars

- CHANGELOG.md
- scout/adapter/mongo/variant_events.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/cases/views.py
- tests/adapter/mongo/test_sanger_validation.py
Fixes #998, namely:
- Variants with Sanger to be evaluated are queried by institute and user.
- Fixed a bug that suggested to be evaluated variants with sanger canceled.
- Showing in popup "Sanger validations to evaluate" both link to cases and all their sanger-ordered variants.
> Fix sanger snvs

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
Rearrange dismissed variants in report so that it fits in the report whenever a variant is dismissed because inherited from unaffected parents. 
HTML was not affected, just PDF.
The whole "Dimissed description" column should now be more clear
Previously looked like this:
After fix:
> Minify dismissed variants in report

- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/sv-variant.html
- scout/server/blueprints/variants/templates/variants/utils.html
- tests/adapter/mongo/test_query.py
Fix #1046
I don't know if I'm naive and missing something here, but I was reasoning that instead of looping through the genes of the query variant to establish the largest genomic interval (given by the start of the first gene and the end of the last), you could simply get all variants that occur in the same genes as the query one (it's basically the same, isn't it?). This way the query should be faster and you also skip the passage where you have to create a gene object for each gene in the query variant.
It fixes the BND issue because BNDs that don't have that gene are not collected.
I also realized that BNDs still had visualizing issues in the sv_variant page and in the report. I've fixed them now!
Fixed also the template so it doesn't print the length of the variant if it's a huge …
> Query overlapping variants by matching genes instead of coordinates

- scout/adapter/mongo/panel.py
- scout/server/blueprints/panels/forms.py
- scout/server/blueprints/panels/views.py
- entry version of a gene accepts text string values now and not only numbers (see #1052)
- Fixed a bug that prevented to update a gene in a panel with empty values in one of the info fields: ['disease_associated_transcripts', 'inheritance_models', 'reduced_penetrance',  'mosaicism', 'database_entry_version', 'comment']
- Improved the code a bit
> Fix gene edit and entry version format

- scout/adapter/mongo/variant.py
- scout/commands/export/variant.py
- scout/export/variant.py
If a case-id is given, i.e. 'scout export variants --case-id ...' this will print more complete vcf entries.
> Export causative variants from a case, with '--case-id' option

- docs/user-guide/variants.md
- scout/adapter/mongo/query.py
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/templates/variants/sv-variants.html
Fix #1073. Replaces length inclusive option with a "shorter than" boolean, that is also inclusive to non-existing lengths. This extends the interface with the sought function, while preserving the old to all practical purposes.
> Sv length shorter

- CHANGELOG.md
- scout/server/blueprints/panels/controllers.py
- scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html
It takes too much time to check in which other panels each gene of a panel is. I'm removing this option for preventing bug #1067 . 
What we could do instead is improving the gene view, listing there all gene panels the gene belongs to.
> Removed reference to other panels in gene panel export

- CHANGELOG.md
- README.md
I'm referring to the page of the library we use. Otherwise it's messy because installation of the external libraries is platform-specific..
> added instructions to install cairo and pango separately

- scout/server/blueprints/variants/controllers.py
Simply adds the the word "primary" to the refseq primary transcript in the verification email.
> Mark primary transcript in verification email

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/cases.html
- tests/adapter/mongo/test_case_handling.py
In cases page, write 'synopsis:', 'HP:' or 'PG:' to get all cases with missing info for these fields
> List cases with missing HPO terms, pheno groups and blank synopsis

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/views.py
- scout/server/blueprints/variants/views.py
- tests/server/blueprints/cases/test_cases_views.py
fix #1236.
Mitochondial reports downloaded from case page contain an excel file per case individual. 
Each file was named like this:  **caseDisplayName_individualID_date**.
This fix renames the files to: **caseDisplayName_individualDisplayName_date**
> Case names on mt report

- CHANGELOG.md
- scout/commands/base.py
- tests/commands/test_base_command.py
This PR reintroduces the --version option required for deployment on clinical-db. fix #1259
1. ssh to clinical-db server
1. become hiseq.clinical user
1. go to $HOME/servers/resources/clinical-db
1. run:
```
bash update-scout-stage.sh fix_cli_version
```
1. Installation process should have no errors
1. activate stage environment with the 'us' command
1. run:
```
scout --version
```
and make sure that it displays: **scout, 4.5.1**
**Review:**
> reintroduces --version

- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
Update igv javascrit from 1.0.9 to 2.2.11. Addresses issue #1199.
This PR to update igv javascript from 1.0.9 to 2.2.11. Tests below are for 
Contact: @mikaell
(Running Scout in demo)
1. open corresponding <filename>.config.yaml (e.i. scout/demo/643594.config.yaml)
2. edit samples:bam_path to point to a bam-file (can be found at ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/data)
3. load the config
`$ scout --demo load case scout/demo/<filename>.config.yaml -u`
4. start scout and login
5. click the igv-button in the "Clinical Structural Variants" or in "Clinical SNV and Indels".
a. the igv view will load in a separate browser window (or tab).
b. inspect page source HTML header, where igv 2 now is called
`<script type="text/javascript" …
> Update to IGV.js 2.2.11

- CHANGELOG.md
- scout/parse/case.py
- tests/parse/test_parse_case.py
Remove if-clauses when building ind_info dict. Make sure no None
value is added by callin removeNoneValues(ind_info) in Return.
This PR is refactoring. And preparation for later bigger commits.
1. how to install it
`git checkout feature_igv-tracks_190626`
`pytest tests/parse/test_parse_case.py`
Tests should pass.
**Review:**
> Refactor: case.parse_individual(sample) <parse>

- CHANGELOG.md
- scout/adapter/mongo/hgnc.py
- scout/commands/export/gene.py
- scout/commands/export/utils.py
- scout/constants/__init__.py
- scout/export/panel.py
- tests/commands/export/test_export_gene.py
- tests/commands/export/test_export_panel_cmd.py
This PR adds the functionality to export genes and panels to build GRCh38. It's addressing #1276
** 1) Testing the gene export**
- from a local installation of scout, master branch run the following command:
```
scout --demo export genes -b 38 
```
You should get a list of gene coordinates where the first column is a chromosome such as 1,2..X,Y,**MT**
- switch to this branch (git checkout export_grch38)
- run now the following command
```
scout --demo export genes -b GRCh38
```
Expected outcome is list of gene coordinates where the first column is a chromosome formatted like this:
chr1, chr2... chrX, chrY, **chrM**
The formatting above should be valid also using the --json option 
** 1) Testing the gene panels export**
- from master branch run the following command:
``` …
```
> Export gene and gene panels to chr build GRCh38

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/query.py
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/forms.py
- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/cases/templates/cases/gene_variants.html
- scout/server/blueprints/cases/views.py
- tests/adapter/mongo/test_case_handling.py
I'm going to PR this now so I don't get tempted to add more features.
This adds three features as it is now:
- Solves the last remaining item in #1065 by allowing case queries for cases with pinned or causative variants in a particular genes. 
- Allows local case searches for phenotypically similar cases using the HPO-tree queries previously available from scout CLI.
- Solves the remaining suggested items in #1064 by allowing limitation of case_variants searches to HPO-terms, phenogroups and cohorts - and for good measure similar cases as well, which didn't exist when the issue was written.
Not ready for merge, obviously - automated tests to follow.
1. Pin variants on case and ensure you can search with pinned gene and find these cases in the case view.
2. Mark variants …
> Wui similar case

- CHANGELOG.md
- pytest.ini
- scout/build/variant/gene.py
- scout/parse/variant/gene.py
- tests/build/test_build_gene.py
- tests/build/test_build_individual.py
- tests/build/test_build_variant.py
Update pytest.ini to remove 'build' from the ignored test directories.
Previous default setting was:
.*', 'build', 'dist', 'CVS', '_darcs', '{arch}', '*.egg', ’venv'
It will start breaking some unit tests that previously were ignored.
This update is needed in every product using the tests/build name structure!
Further reading [https://docs.pytest.org/en/3.0.0/customize.html]
1. how to install it
Update your repository
$ git pull
Run the pytest
$ pytest tests
Pytest will now enter tests/build and execute unit tests. 
**Review:**
> Stop ignoring 'build' dir when running Pytest

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
This PR fixes the SSL: CERTIFICATE_VERIFY_FAILED error in #1289.
This is a workaround before changing the settings in servers (see here: https://github.com/Clinical-Genomics/servers/issues/179)
1. It's not possible to download PDF reports from the 'general report' page. You can test on any case on scout-stage
1. How to install the branch on clinical-db stage:
```
ssh your.user@clinical-db.scilifelab.se
sudo -iu hiseq.clinical
cd servers/resources/clinical-dbscilifelab.se
bash update-scout-stage.sh disable_ssl
```
**Review:**
> Disable ssl

- CHANGELOG.md
- requirements-dev.txt
- requirements.txt
- scout/adapter/mongo/hgnc.py
- scout/adapter/mongo/variant_loader.py
- scout/build/variant/variant.py
- scout/commands/load/research.py
- scout/commands/load/variants.py
- scout/export/panel.py
- scout/server/blueprints/login/views.py
- scout/utils/coordinates.py
- tests/commands/export/test_export_hpo_cmd.py
- tests/commands/update/test_update_groups_cmd.py
- tests/commands/view/test_view_diseases_cmd.py
- tests/commands/view/test_view_hpo_cmd.py
- tests/commands/view/test_view_whitelist_cmd.py
- tests/utils/test_par.py
This PR adds updates some of the deprecated functions.
1. Install this branch
1. Run the tests and see that most deprecation warnings are gone
Deprecation warnings from pymongo, interval tree and logging should be gone
**Review:**
> Fix deprecation warnings

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/case_events.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/cases/views.py
- scout/server/templates/layout.html
- tests/adapter/mongo/test_case_handling.py
- tests/adapter/mongo/test_event_handling.py
- tests/conftest.py
- tests/load/test_load_case.py
- tests/server/blueprints/cases/test_cases_views.py
This PR adds the following functionalities:
- Cases that are **re-run become 'inactive'** if they were previously archived (fix #1271)
- Makes it possible to **sort cases by 'Status', 'Analysis date' and 'Track'** in cases page (fix #1271)
- Orders the categories of displayed cases (cases page) like this: **'prioritized', 'active', 'inactive', 'archived', 'solved'** (fix #1285)
**How to test dearchiving of re-runs**:
1. On a local installation of scout-stage, archive the test case
1. From the command line update the case with the following command:
```
scout --demo load case scout/demo/643594.config.yaml --update
```
3. Expected outcome: Refresh the page and make sure that the case status is now 'inactive'
**How to test the case sorting by 'Status', 'Analysis date' or 'Track' :**
1. …
> De-archive re-runs and sorting of cases page

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- scout/server/blueprints/alignviewers/views.py
fix #1309.
I've finally understood why we had no power over the sample track height in igv. It was because we changed its value in the python view but we never passed it to the javascript of the template. Now I've fixed it at the template level. And it works. It's on stage now!
1. Check IGV alignments of this case on stage: https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/2d7c606e92383a8572556138d1310c10 and compare with any alignment in scout production. 
Stage sample tracks' height are 700 pixels on stage, prod ones are 300 pixels instead.
**Review:**
> Resize igv sample tracks

- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
fix #1302
- Create a local command for a variant
- Create a local and a global comment for another variant (or just a global comment)
When the variants are displayed in the rank list, the one with the global comment should have a globe icon close to the comment one: 
I've fix snvs, STRs and SVs to behave this way. 
**Review:**
> Global comments get a dedicated icon in variants list

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/variants.html
This PR shows earlier ACMG evalautions (ie in other cases) to the variants list, to allow quick identification of previously evalauated variants.
Not sure how this affects performance on large databases. Do you have tests for such things? I see no noticable slow-down on our installation.
See screenshot below.  I used "label-primary" to visually differentiate it from ACMG-classifications made in the specific case, but I could change that to something else.
> Display earlier ACMG classifications in the variants list

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- scout/server/blueprints/alignviewers/views.py
fix #1331 and ugly IGV logo (top left of igv view). fix #1329 (display genes track on top)
1. On prod, choose a case variant and open it in igv viewer. 
- Gene track should be at the bottom of the page
- You should see the ugly igv logo (two logos juxtaposed)
- Try to search for a gene and you'll get error code:
1. how to test it:
- This branch is already on stage.
- Open case on stage: (https://scout-stage.scilifelab.se/cust002/643594-300M) and load one of its variants in IGV
- The above mentioned problems don't occur
- Genes track is displayed on top of the samples tracks
- Take a screenshot and attach or copy/paste the output.
**Review:**
> Fix igv bugs and display genes track on top

- CHANGELOG.md
- scout/adapter/mongo/case.py
Bug fix #1328
With a fresh db, 
1. pin a variant for a case, say in POT1 
2. ensure you can find the case again by searching cases for pinned:POT1
3. Repeat for causatives, by marking the variant causative and searching for the case as causative:POT1
**Expected outcom**:
**Review:**
> Fix #1328 - case search.

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/variant_events.py
- scout/commands/load/variants.py
- scout/server/config.py
- tests/adapter/mongo/test_sanger_validation.py
- tests/adapter/mongo/test_variant_events.py
- tests/commands/load/test_load_variants_cmd.py
fix #1326 ---> Keep Sanger validation status or Sanger validation ordered after reuploading the variants for a case
Updating of variants in scout may occur in 2 ways: 
- **Force re-uploading of variants**
- **Updating of case**
This PR modifies both ways so that Sanger info is retained.
**------->How to test Force re-uploading of variants (on a local installation)**
requirements:
1. Make sure you are on the master branch of scout
1. open config.py file in scout/server/ and add the following lines to it:
```
ADMINS = ['your_scilifelab_username']
MAIL_USERNAME = 'your_scilifelab_username'
MAIL_PASSWORD = 'your_real_scilifelab_password'
```
This way you can order Sanger from your installation.
1. Go on a variant and order Sanger for it.
1. Then go to another and pin it then, from the case …
> Keep sanger

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/templates/bootstrap4.html
fixes a bug affecting variants page. 
1. Can be tested on a local installation of Scout after adding a global comment and/or a local comment for a variant. Variants page for that case won't work.
2. Alternatively go to stage and make sure that variants page for this sample doesn't work: https://scout-stage.scilifelab.se/cust000/620573fam30M/
3. Install this branch and check that the problem is fixed.
4. Click on the first variant, which has 1 global and 1 local comment. Variant page should work as well.
The pages work on stage when using this branch, crashes while using master branch
**Review:**
> Fix missing comments_table import in current master (fix #1372)

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
This functionality is bug fix #1374
1. install the branch and check that variants page filter look like this:
1. sv-variants should also look like the picture above (action dropdown missing from the top bar and 2 new buttons available in filter form)
1. "HPO gene list" and "reset filter" buttons should do what they are supposed to do (compare with scout prod, where the functionality is working)
**Review:**
> Moved and fixed variants filter actions (fix #1374)

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/sv-variant.html
- scout/server/blueprints/variants/views.py
This PR adds a functionality and fixes a bug.
1. look at the SV variants page on stage. make sure you can see exon ranges for a couple of SV variants that should have it (eg an exonic 100kb or so deletion or duplication)
1. look at a SV variant and see that UCSC coordinates are visible. See that you cannot see the button for the whole variant for variants that span across contigs such as translocations (BND).
**Review:**
> Exon ranges

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
This PR adds a functionality and so indirectly amends the impact of a bug.
Users should be able to see coverage for the dynamic gene panel. As a benefit, as single genes can now be added to the dynamic panel, this can be used together to quickly create a coverage report for a few genes of interest, indirectly solving the issue in #499.
1. Use a setup with chanjo-report configured.
1. See that when dynamic gene panel is populated, a link to a coverage report for the panel is added to the case page. 
1. When the dynamic panel is empty, no Coverage link should be shown.
**Review:**
> Dynamic panel coverage

- CHANGELOG.md
- scout/adapter/mongo/case.py
Change %n to {}.format in log.info print.
I ran into a crash this morning when loading configs:  
```
2019-10-12 10:59:26 mikaellmbp scout.adapter.mongo.case[65669] DEBUG Updating verification status for variants in case:internal_id
--- Logging error ---
Traceback (most recent call last):
File "/miniconda3/envs/python3.6/lib/python3.6/logging/__init__.py", line 994, in emit
msg = self.format(record)
File "/miniconda3/envs/python3.6/lib/python3.6/logging/__init__.py", line 840, in format
return fmt.format(record)
File "/miniconda3/envs/python3.6/lib/python3.6/site-packages/coloredlogs/__init__.py", line 1116, in format
return logging.Formatter.format(self, record)
File "/miniconda3/envs/python3.6/lib/python3.6/logging/__init__.py", line 577, in format
record.message = …
```
> Bugfix: log print

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/cases/views.py
1. Install in an environment with more than one case.
1. Click sort of track, status and date to see that date sorting reverses sort order on toggle and icon colour changes to indicate which order is active.
**Review:**
> Toggle date sort order - fix #1299.

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/variant.html
- scout/server/blueprints/variants/views.py
This PR fixes a bug / adds a missing function.
1. click an STR variant (rank link). 
1. see that the variant page shows a link back to the STR variants list, and that it works.
**Review:**
> Fix #1391 - STR back link (and column layout) broken.

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
This PR adds a functionality - SV variants hover.
1. In environment with cases with a few SV variant sources, 
1. hover over the frequency field of the SV variant and see frequencies.
**Review:**
> Fix #1305 - SV variants hover.

- CHANGELOG.md
- scout/commands/setup/setup_scout.py
- scout/load/hgnc_gene.py
- scout/load/hpo.py
- scout/load/setup.py
- scout/utils/link.py
- tests/commands/test_setup_cmd.py
This PR fixes so that it is possible to setup scout without an OMIM api key
1. Install this branch
1. Setup scout in the usual way but without an api key:
1. `scout -db gene-test setup database`
1. `scout -db gene-test load panel scout/demo/panel_1.txt` 
1. `scout -db gene-test load case scout/demo/643594.config.yaml`
1. `scout -db gene-test serve`
Everything should work as usual but there will not be any OMIM information. This means reduced gene information and no disease terms.
**Comments**
Don't forget to apply for a api-key from OMIM: https://omim.org/downloads/
And when you have it run:
`scout update genes --api-key <your key>`
`scout update diseases --api-key <your key>`
**Review:**
> Skip omim genes

- CHANGELOG.md
- scout/commands/base.py
This PR adds a fixes a bug at cli where `--version` shows twice, and one is from flask.
```
scout --help
```
There should be one `--version` in output.
**Review:**
This is a patch bump, as it is clearing up help and an inactive command line option,
> Removes flask version from cli

- CHANGELOG.md
- docs/admin-guide/server.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/case_events.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/cases/templates/cases/causatives.html
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/cases/templates/cases/index.html
- scout/server/blueprints/cases/views.py
- scout/server/blueprints/genes/templates/genes/gene.html
- scout/server/blueprints/institutes/templates/overview/institutes.html
- scout/server/blueprints/login/templates/login/users.html
- scout/server/blueprints/panels/templates/panels/panel.html
- scout/server/blueprints/variants/templates/variants/clinvar.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variant.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variant.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/blueprints/variants/views.py
- tests/adapter/mongo/test_case_handling.py
1. Activate (or archive) a case.
1. Request rerun, and ensure that case does not become inactive.
1. See that the case gets a rerun-pending badge on cases list.
1. Re-upload case, e.g.  ```scout --demo load case --update scout/demo/643594.config.yaml```
and ensure that it now becomes inactive, a rerun badge is shown but no pending badge.
The functionality should be working.
**Review:**
> Fix #1395. Inactivate rerun cases only on re-upload.

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
Bug fix #1417
1. From a demo instance of scout, load the demo cancer sample:
```
scout --demo load case scout/demo/cancer.load_config.yaml
```
1. From master branch go to the variants of this case
1. try to hover above cancer variants frequencies and observe that popup doesn't work
1. Switch to this branch and see the difference
**Review:**
> Reintroduce tooltip in cancer variants page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/variants/templates/variants/sv-variant.html
This PR adds a new feature (fix #1408)
1. Install the branch on stage
1. Mark one or more (SV) variants as causative or partial causative
1. Make sure that you have to associate a phenotype (HPO terms or OMIM diagnosis) to each partial causative.
1. Make sure case is not marked as solved when a partial causative variant is assigned.
1. Make sure that specific links to phenotypes on case page work.
1. Make sure events are correctly recorded.
1. Make sure you can remove causative and partial causative variants.
**Review:**
> Mark SV variants as partial causative

- CHANGELOG.md
- scout/adapter/mongo/variant_loader.py
- tests/adapter/mongo/test_variant_loader.py
This PR fixes a bug that scout raised an `pymongo.errors.InvalidOperation` when updating variant ranks for a case without variants
1. travis tests
**Review:**
> Loading fails

- scout/parse/variant/clnsig.py
We have CLNACC as an integer in our VCFs. Since 59559116901fe189fa7b46e7f7bdeb3bed6e95a6 this causes case loading to crash with this error:
```
File "/opt/scout/scout/parse/variant/clnsig.py", line 45, in parse_clnsig
if acc.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
```
Which makes sense, since isdigit() is a string method. 
This PR fixes this error. :)
> bugfix: Case loading crashes if CLNACC is an integer

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
Bug fix #1444 
Looking at the files changes it looks like I changed a lot of stuff, but it's not this big deal, I've just added 2 lines of code:
- line 448: {% if reason is number %}
- line 569 {% endif %}
1. To recreate this bug on a local instance of scout create the following key value in a variant object:
1. Using master branch notice that it is not possible to open the general report for the demo case
1. Switch to this branch and make sure that general report is working and the variant is among the dismissed variants in the report. The reason why the variant is dismissed should be empty.
**Review:**
> Check dismissed variant code when printing report

- scout/server/blueprints/cases/templates/cases/cases.html
- scout/server/blueprints/cases/views.py
- tests/adapter/mongo/test_case_handling.py
fix #1445
**Behavior before the fix**:
1. From a local instance of Scout load demo sample:
```
scout setup demo
```
1. Load another test sample as well:
```
scout --demo load case scout/demo/643595.config.yaml
```
1. You will now have these 2 samples:
1. If you filter for cases with the name: 643594
1. Then in the footer of the search form there will be written **Showing 1 / 1 cases**
**Behavior after the fix**
1. Checkout to this branch and perform the same search.
1. Then in the footer of the search form there will be written **Showing 1 / 2 cases**
**Review:**
> Show total number of available cases in cases search footer

- CHANGELOG.md
- scout/adapter/mongo/user.py
- scout/server/blueprints/login/views.py
- tests/adapter/mongo/test_user_handling.py
This PR fixes a problem when `_id != email` in the `user_objs`
Users can now be fetched even if the _id is not the email adress
Check tests in https://github.com/Clinical-Genomics/scout/blob/search-user-email/tests/adapter/mongo/test_user_handling.py
**Review:**
> Search user email

- scout/parse/case.py
- tests/parse/test_parse_case.py
This PR fixes a problem when analysis date is a string in load config.  Fix #1448
See tests for parse_case
Analysis dates will always be date time objects
**Review:**
> Always use datetime object when loading a case.

- CHANGELOG.md
- scout/server/static/bs4_styles.css
fix #1450
1. Multiple selects look messy in current master when there are long and short options: for instance open variants page and variants filter. Clinsig filter looks like this, with options all over the place:
1. Before checking out to this branch clear the history of the browser (cached images and files)
1. Checkout to this branch and refresh the variants page. 
1. Multiselects should look ordered with all options on one column:
**Review:**
> fixed conflict between our css and multiselects css

- CHANGELOG.md
- scout/server/blueprints/login/views.py
Bug fix #1465
1. Install on stage and log in using a valid Google account (email) for a user which is in Scout database.
1. Install on stage and log in using a valid Google account (email) that is not in Scout database.
The functionality should be working and allow the Scout login only in the first case
**Review:**
> Prevent the AttributeError: 'NoneType' object has no attribute 'message'

- CHANGELOG.md
- scout/server/blueprints/login/models.py
- tests/server/blueprints/login/test_models.py
Fix #1467
1. Create a new user from mongoDB compass. Don't provide any custom _id so it will be of type ObjectID. Example:
1. Try to login with this user from master branch and this branch. 
1. Test even from Scout stage trying to log in a user that has ObjectID as _id 
Login from master should give error while from this branch it should work.
**Review:**
> Flask login returns email as _id instead of risky ObjectId id

- scout/server/blueprints/variants/templates/variants/utils.html
Bug fix #1479 
1. Variants filter page (all types of variants) crashes when users try to remove or load a filter from an empty filter list
1. This fix disables load and delete filter buttons if filter select is empty:
1. From a local instance of Scout:
- Make sure that you can create and remove filters from any type of variants page
- Make sure you can't remove or load filters from an empty filter select.
All should work according to instructions
**Review:**
> Disable load and remove filter if there's no saved filter

- scripts/merge_users.py
This PR adds a functionality that will winter clean the db, merging old ObjectId _id users with existing email _id users, or creating new such users, and assigning their ACMG, ClinVar, and general event entries to the new merged user.
1. dry run on local, stage and prod and see that everything looks kosher.
1. live run local
1. dump relevant tables on scout-stage, then run live and evaluate.
**Review:**
> merge user script - fix #1472, fix #1473, fix #1481

- CHANGELOG.md
- scout/parse/case.py
- scout/server/blueprints/cases/controllers.py
This PR fixes a bug when rank model version where stored as strings in the database.
**How to test**
On stage:
1. Try to open a case where rank_model_version is a float (try 15078-miptest)
1. En exception is raised
1. Pull this branch and repeat the above.
1. Check that it works
Old cases should be possible to open.
**Review:**
> Make sure rank model version are always strings. Fix #1475

- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
fix #1477
1. Clicking on coverage report on the sidebar now opens an extra blank page
1. This change should avoid this
1. To be tested on stage where there are actual coverage reports to open for cases.
**Review:**
> Avoid coverage report opening an extra blank page 

- scout/server/blueprints/variant/views.py
- scout/server/links.py
- tests/server/test_links.py
This PR fixes three (small) bugs.
1. ppaint link will not cause error if hgnc symbol is missing (#1478 )
1. Variant verification will work (#1490 )
1. USCS gene link was broken but will now work
**Review:**
> Fix broken links

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
1. dismiss a variant 
1. note that current master general reports will not display dismiss reasons
1. checkout the present PR branch
1. note that the general reports now display dismiss reasons
**Review:**
> Fix #1473 - dismiss reasons are back again.

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
P/LP ACMG classifications in the same case would appear also as previous evaluation, due to loop logic.
1. on master, classify some variants and note that they appear on the variants list both as ACMG-P and previous-P.
1. with this branch, repeat and note that only the current ACMP-P event is shown for the case/variant.
1. pick a reasonably common variant on one case, where you also have shared variants with other cases. Classify it in one of the cases and check that it is still shown as previously classified in the other.
**Review:**
> Fix #1487. Actually ignore same case previous evaluations.

- CHANGELOG.md
- scout/constants/variant_tags.py
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/views.py
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/blueprints/variants/views.py
1. Ask @AnnHam, @1ctw, @4WGH or some other Power-user how they manage to generate a "Select a tag" for a variant (I couldn't without explicitly crafting a URL for it 😊) and ensure that this PR handles the issue without crashes. Or perhaps just review for errors and test that you can assign- and unassign manual rank to variants and sv-variants without crashes.
**Review:**
> Fix #1515 - don't generate 'Select a tag' and catch them if we do.

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/matchmaker.html
- scout/server/static/bs4_styles.css
fix #1517
1. From master branch, check matchmaker external matches on stage for this case: https://scout-stage.scilifelab.se/cust101/A1383/mme_matches
1. Open one random external match and make sure that contact email is not displayed (contact looks like in fix #1375 
1. Install this branch on stage check the same external matches
1. Email fields email should be now present and MME pages in general are more clear
**Review:**
> display MME contact emails when available

- CHANGELOG.md
- scout/server/blueprints/genes/templates/genes/gene.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/links.py
This PR adds links to [genemania](genemania.org) on variant and gene pages.
1. Install the branch
1. Browse a variant and a gene and check that the link is there and works
**Review:**
> Link genemania

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/views.py
This PR adds a functionality fixes #1499
1. Go to stage and browse a variant that should have overlapping variants. See that no variants are shown on variant page:
1. Install this branch
1. Browse the same variant and check that the overlapping are there:
Overlapping variants should now show up on variant page
**Review:**
> Show overlapping variants on variant page

- scout/adapter/mongo/case.py
- scout/build/case.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/views.py
- tests/adapter/mongo/test_case_handling.py
- tests/conftest.py
This PR fixes two bugs on dynamic_gene_list entry:
1. It apparently happens that empty (deleted?) dynamic gene panels become dicts rather than lists in the db. Check and correct for that. #1507 
1. Also, if random strings are entered into the gene field for addition to the dynamic gene list, the view croaks trying to parse a gene with hgnc_id | etc. #1500. Flash a warning instead of crashing.
1. with empty (deleted) dynamic (HPO) gene lists on a case, add a gene to the dynamic gene panel
1. add some well thought through QC manager / tester phrases into the gene field, and note flashed warnings. No gene should be added for simple phrases. No guarantees for handcrafted |- and ' ' containing ones.
Take a screenshot …
> Fix #1507, Fix #1500: dynamic gene panel addition meets users

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/causatives.html
fix #1532
- Causatives page from master branch doesn't show the rank model used to rank the specific variant
- On a local instance of Scout (master) mark a snv variant and a sv variant as causatives.
- Go on the causatives page and make sure that no model is displayed alongside the rank value for the variants.
- Checkout to this branch and see that now rank model is shown:
- Can alternatively be tested on stage
**Review:**
> added rank score model to causatives page

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
This PR disables Mosaic Tags for cancer variants
1. Install on stage
See that the Mosaic Tags form is gone for cancer, but not for SNVs and INDELS
**Review:**
> no mosaic for cancer

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
- tests/server/blueprints/variants/test_variants_controllers.py
This PR adds a functionality - show clinical assessments / dismissals on research page.
1. manually rank, dismiss, tag, comment and evaluate to your hearts content on a clinical case variant page
1. ensure that you can see shadows from all your clinical assessments on the research page
**Review:**
> Fix #1344 - show clinical assessment/dismiss on research page.

- CHANGELOG.md
- scout/server/templates/report_base.html
This is exactly the same PR as #1563, but without conflicts!
1. General report using the current master should not show any info regarding patients' sex
1. Branching out to this PR will fix it and when patient gender is available it will be shown as an icon:
**Review:**
> Use FontAwesome library in general report

- CHANGELOG.md
- scout/parse/case.py
- tests/utils/test_ensembl_rest_clients.py
fix #1565. This PR fixes the following problem:
- On clinical-db stage and prod environment path dependency is missing
- It is not possible to install the current master on clinical-db stage using the bash script because before installing from git you get this error:
```
from scout.parse.case import parse_case
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/parse/case.py", line 7, in
from path import Path
ModuleNotFoundError: No module named 'path'
```
1. Try to run the bash command `bash update-scout-stage.sh master` as user hiseq-clinical from /home/hiseq.clinical/servers/resources/clinical-db.scilifelab.se. You should get the: No module named 'path' error described above.
1. Try to install master branch from scout stage environment on …
> Fix path dependency problem

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/alignviewers/views.py
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/views.py
This PR addresses the easiest requests from #1501
For clarity sake I found this solution, what do you think?
1. Install the branch on clinical-db stage and see the difference with scout production
The functionalities in the checkbox should be working as described
**Review:**
 
> Improve str layout

- CHANGELOG.md
- scout/adapter/mongo/index.py
This PR should fix #1568 and eventually #1557 
1. Install the branch on Hasta stage and use the stage environment with `us`
1. Run the command:
`scout update genes`
The command should update genes and run until the end, with no errors but just warnings
**Review:**
> Handle pymongo.OperationFailure errors when updating indexes

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/causatives.html
fix #1572. 
Introduce QG and read depth along with zygosity.
The field should look like this:
1. Mark causatives some variants (good-bad quality, snv, svs, str vars) and see how the new causatives page shows them. Make sure that:
**Review:**
> show GQ and allele depth in causatives page.

- CHANGELOG.md
- scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
final fix #1497
**Introduced fixes:**
Master looks like this:
After this fix:
-------------------
Master looks like this ()
After installing this branch:
-------------------
Master looks like this:
After installing this branch:
-------------------
**Review:**
> Layout fixes

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case_report.html
fix #1587
1. Mark one or more variants (SNVs, SVs) as partial causatives
1. Go to general report and check they're shown on it (also relative HPO and OMIM terms)
1. Make sure that also the PDF report is correct.
**Review:**
> Include partial causatives in general report

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
fix #1601
1. Install the branch on a local instance of scout
1. Open a str variant page and note that the repeat locus name is present:
**Review:**
> display locus name on str variant page

- .travis.yml
- CHANGELOG.md
- requirements-dev.txt
- tests/utils/test_ensembl_rest_clients.py
fix #1604 and fix #1564 
The ideal would be to fix the tests to take into account also when the Ensembl Rest API is down, but now it is working and I don't remember exactly what the page says when the service is down. I guess we could fix it some other time!
1. Travis CI will run the tests
Automated tests should pass (3 tests, including coveralls call)
**Review:**
> Restore coveralls call from Travis CI and handle Biomart service errors

- CHANGELOG.md
- scout/server/static/bs4_styles.css
The comment popover:
...is flickering wildly and is unreadable for long comments (if wider than the browser window I think). This has been the case since the BS4 update.
This simple CSS change fixes it. And as far as I can see it doesn't have any other side effects.
> Avoid flashing popovers

- .travis.yml
- CHANGELOG.md
This PR fixes erroneous coverage calculation on CI by moving it from the push CI to the PR CI
1. open the push check
1. open the PR check
**Review:**
> Calculate coverage for PR CI but not for push CI

- .travis.yml
Lint, Lint score and PEP8 rests on travis should be advisory / discretional. Fix #1638.
**Review:**
> Fix #1638. Allow travis fails on code quality advisory jobs.

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/views.py
- scout/server/blueprints/variant/views.py
- tests/adapter/mongo/test_clinvar_handler.py
- tests/commands/view/test_view_collections_cmd.py
- tests/utils/test_ensembl_rest_clients.py
Allow institute-level clinvar submissions. fix #1625
1. Testable on a local instance of Scout
1. Create a new user with the same institute of test user.
1. Create a clinvar submission containing one or more variants using test user.
1. Login with the other user and make sure the submission is viewable.
1. Add one or more variants to the same submission
1. Remove one or more variants from the same submission.
1. Try to close and reopen the submission.
**Review:**
> Decouple Clinvar submission from users

- .pre-commit-config.yaml
- .travis.yml
- CHANGELOG.md
- CONTRIBUTING.md
- requirements-dev.txt
This PR adds optional automatic Black as pre-commit event
install scout locally including dev-requirements
* run pre-commit install
* make a non PEP8 change to a .py file 
* commit
The file should be pep8 formatted auto by Black
**Review:**
> Add black as optional pre commit

- .travis.yml
- CHANGELOG.md
This PR fixes the issue with coverage reports missing on PRs (fix #1666)
1. Open this PR on Github
1. Commit some changes that reduces the amount of code covered
1. Revert those changes
**Review:**
This is a patch/fix
> Upload coverage on master an push CI checks

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
This PR fixes the link that from a cancer case leads to variants hitting genes in the HPO panel. (fix #1611).
Current behavior:
1. When an HPO panel is created the link to `Clinical HPO SNV variants` :
1. This link opens the NON-CANCER variants page
1. On a local implementation of Scout load a demo cancer case: 
`scout --demo load case scout/demo/cancer.load_config.yaml`
1. Generate an HPO panel on a case page using a random HPO term. 
1. Check that the button to `Clinical HPO SNV variants` opens the "Clinical Cancer Variants" page.
**Review:**
> Fix cancer variants HPO panel link

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/str-variants.html
Bug fix #1698
Make it sure that the form action is the IGV view and the method is POST. Add this to the buttons as well so that the first one behaves as it should. Don't ask me why but this is working!
**How to test on a local branch**:
- Modify the load config file `scout/demo/643594.config.yaml` by adding the field: 
```
bam_path : scout/demo/reduced_mt.bam 
```
to each of the 3 samples of the case. (*Doesn't matter that it's not the correct bam file, it does the trick to display the buttons and triggers the igv view anyway).
-  Upload the case with the command:
``` 
scout --demo upload path_to_the_above_demo_config-file
``` 
- From master branch, go to the str variants page of the case and make sure that the first button doesn't work (doesn't open a new igv window)
- Switch to this …
> Fix first str variant button

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/phenotype.html
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/blueprints/variants/views.py
Fixes also missing info in cancer variants and cancer sv variants pages (fix #1680)
Fixes also: 
- a bug affecting case page for cases with pinned or causative variants in genes without hgvs_identifier. Example: https://scout-stage.scilifelab.se/cust000/620573fam30M
- a bug in case page due to missing parameters in hpo_group_item macro
- a bug caused by missing old_observation import in sv variant page
1. Open a **snv variant from a non-cancer case** and pin it, add an ACMG classification, comment it globally and locally
1. Open a **structural variant from a non-cancer case** and pin it, add an ACMG classification, comment it globally and locally
1. Open a **str variant from a non-cancer case** and pin it, add an ACMG classification, comment it globally and locally
1. …
> Reuse variant events (pinned/classif/comments) in all variants pages

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
Show two instead of four decimals for Allele and Normal frequency
in cancer view.
As from discussion here:
https://github.com/Clinical-Genomics/scout/issues/1629#event-3009077515
1. how to install it
Clone and install Scout from `QoL-cancer_variant_view_200214`. Setup demo or preferred configuration showing cancer variants such as `cancer.load_config.yaml`
Go to `Clinical Cancer Variants Page`in Scout.
At the most two decimals are shown, instead of four, for Allele and Normal in Scout's cancer view. For example:
**Review:**
> Round Allele and Normal Frequency to Two Decimals

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/causatives.html
- scout/server/blueprints/cases/views.py
fix #1690
1. Install this branch on scout stage and go to causatives page of one institute
1. Make sure that each causative has an acmg classification missing (-) or a value (P, LP, VUS, LB, B)
**Review:**
> fix #1690: unique ACMG map for all causatives

- CHANGELOG.md
- scout/parse/case.py
This is an urgent bug fix
The current master branch doesn't handle well when both these keys are present in case config file:
1. An empty `bam_path`
1. A valid `alignment_path`
1. Install it on hasta stage and upload a case with the above configuration
1. Make sure that the correct bam path is passed along and saved in the database.
**Review:**
> Take care of empty bam paths values

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
So it mirrors the actual alt allele frequency
1. Install it and check that on variants page it is reported the right info
**Review:**
> Swap ref/alt to alt/ref reads in cancer variants page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
A patch over the cancer pinned variant hgvs view. Appears some details on the genes there (and for STRs) is missing. We should return to this, but this at least just doesn't leave an empty field for pinned variants.
1. Pin a variant of each type (cancer, cancer_sv, str, snv. sv) and make sure they render reasonably on the case page.
**Review:**
> Fix pin cancer var

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variants/templates/variants/components.html
fix #1737 and fixes another minor potential bug in variants components.html template.
Something must have changed in the code where variant frequencies are collected and now it's a list of tuples with 3 elements each, and not 2, as before.
1. Install branch on stage 
1. Go to case https://scout-stage.scilifelab.se/cust000/15026-mip7 (which has a general report not working with current master branch) and the report should work. Check also PDF report
**Review:**
> Variant frequency loop fix in 2 templates

- CHANGELOG.md
- scout/server/blueprints/panels/views.py
fix #1750. 
1. From a local instance of Scout (master branch), go to a gene panel and remove a gene using the red delete button (remember which gene!)
1. Try to add the gene again using the form above: 
1. Make sure that when you apply the pending action of adding the gene the app crashes.
1. Checkout to this branch and make sure that the gene can be added normally.
1. Test also the option to modify a gene and not add it
**Review:**
> Fix code for when a new gene is added (and not edited) in a panel

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- scout/server/blueprints/alignviewers/views.py
This PR adds a Clinvar IGV track on top of the gene track (fix : #1660)
For more reference about where I took the track and color codes: https://genome-euro.ucsc.edu/cgi-bin/hgTrackUi?hgsid=234574442_yPXTIamdZkAXX0L6DUZZmsPXEy7H&c=chr21&g=clinvar
Clinvar files are updated every month so it would be nice to use their track!
1. Install this branch on stage and check some variants' alignments  (example case: http://scout-stage.scilifelab.se/cust000/lovedmarlin)
**Review:**
> introduced clinvar SNVs track for IGV, both genome builds

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Fix #1745
1. Install on stage and check that all the points in #1745 are OK for a recent case having those reports available
The functionality should be working:
**Review:**
> Side panel fixes

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/commands/delete/delete_command.py
- tests/adapter/mongo/test_case_handling.py
- tests/commands/delete/test_delete_cmd.py
Fix #1709
1. Delete using case ID should remove case and variants:
`scout setup demo`
`scout --demo --loglevel DEBUG delete case -c internal_id`
1. Delete using display_nave and institute should remove case and variants:
`scout setup demo`
`scout --demo --loglevel DEBUG delete case -i cust000 -d 643594`
**Review:**
> Delete case and variants when using delete command with case display_name

- CHANGELOG.md
- scout/adapter/mongo/query.py
This PR fixes a bug causing the coordinates filter to override all other filters.
In SVfilters, if you select these filters: SVtype=DEL, Chromosome 3. This will show all variants on chr3 reagardless of SVtype. The query looks like this:
```
mongo query: {'case_id': 'xxx', 'category': 'sv', 'variant_type': 'clinical', '$and': [{'$or': [{'chromosome': '3'}, {'end_chrom': '3'}]}]}
```
This will fix that and make the query look like this:
```
mongo query: {'case_id': 'xxx', 'category': 'sv', 'variant_type': 'clinical', '$and': [{'$or': [{'chromosome': '3'}, {'end_chrom': '3'}]}, {'sub_category': {'$in': ['del']}}]}
```
I think this was caused by a typo where `if mongo_query.get("query"):` should have been `if mongo_query.get("$and"):`, but I don't understand the query building well enough to …
> Fix coordinates filter bug

- .coveragerc
- .github/workflows/pythonapp.yml
- .gitignore
- .travis.yml
- CHANGELOG.md
This PR switch from using travis to GitHub Actions for coveralls
Coveralls should be run from GitHub Actions 
**Review:**
> Run coveralls from github actions

- .github/workflows/pythonapp.yml
- .travis.yml
- CHANGELOG.md
This PR changes so that pip checks are executed in GitHub Actions instead of travis
pip checks should be run on GitHub Actions
**Review:**
> Run pip checks on github actions

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/links.py
Yet another hg19/hg38 fix.
For hg38 cases, link to gnomAD 3.0 (which is hg38 based) instead of the default (currently 2.1.1, which is hg19 based).
Also fixes a related typecasting bug that I have a feeling that I've fixed before. Maybe in another function.
> Gnomad link hg38

- CHANGELOG.md
- README.md
- docs/admin-guide/loqusdb_integration.md
- scout/commands/base.py
- scout/server/extensions/loqus_extension.py
- tests/server/extensions/conftest.py
- tests/server/extensions/test_loqusdb_extension.py
- tests/server/extensions/test_loqusdb_extension_init.py
This PR adds a requirement on loqusdb to use `version >= 2.5`
1. Install on local machine 
1. Create a loqusdb environment with a loqusdb version <= 2.5
1. Start the server
Scout should exit gracefully and tell what was the problem
**Review:**
> Loqus version req

- scout/parse/variant/coordinates.py
- tests/parse/conftest.py
- tests/parse/test_parse_coordinates.py
This PR adds the functionality to calculate end position for translocations when break points are on the same chromosome
1. Tests are automated
Scout will now display the correct length for translocations
**Review:**
> Calculate correct translocation lengths

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/variant/controllers.py
- tests/adapter/mongo/test_variant_handling.py
This PR fixes a bug when a variant found in loqusdb does not exist in another case
Should not fail when the above happens
**Review:**
> Fix problem with fetching cases

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
This PR rearranges the cards on variant page
**Prepare for test**:
1. On stage
1. Open a variant, looks something like this:
Frequencies in one row, gene models in one etc.
1. Install on clinical-db stage
1. Refresh the variant from above
Models should be in one column, frequencies in one and severity/conservation in one
**Review:**
> Arrange cards using card-columns

- CHANGELOG.md
- scout/server/blueprints/cases/views.py
Fix #1835.
In the current situation whenever a clinvar submission object is created, then the downloadable files have the same name. This PR fixes that and adds the type of file (case_data, variant_data) to the downloadable file names.
1. Install the branch on a local instance of Scout.
1. Assign an HPO phenotype to the demo case
1. Pin a variant
1. Create a clinvar submission object and download the associated files
1. The 2 downloaded files should have different names. 
**Review:**
> Name clinvar submission files according to their type

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
This PR fixes a bug which caused causatives from other cases to show up only if there were at least **two** of them.
> Bugfix other causatives case

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/sv-variant.html
This commit https://github.com/Clinical-Genomics/scout/commit/e5468f439ee9c89fe68280ebb3cffe76611a53d7 accidentally (?) removed the "custom annotations" from the SV-variant template.
This PR adds them back in. I realize we're the only ones using these, but they don't affect anything if you're not using them.
> Add custom annotations back in for SVs

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/clinvar_submissions.html
- scout/server/blueprints/variant/templates/variant/clinvar.html
fix #1850 (dbsnp ids containing rsnumber:something)
fix #1851 (option to leave zygosity empty)
fix #1853 (display dbsnp box even if variant doesn't have associated dbsnp id)
fix  #1837 (display gene in clinVar submissions page)
1. Install the branch on a local instance of Scout
1. Assign a HPO phenotype to the case
1. Pin a snv variant (POT1 works perfectly)
1. From the variant page click on "Submit to clinVar"
1. Check the zygosity option in the casedata (checkbox "Submit case data for this variant") has the new option "leave blank"
1. Change the dbsnp_id for this variant in the database to "rs116916706:blabla" and check that the clinVar form shows only "rs116916706".
1. Remove completely the dbsnp_id field from the database and make sure that it still shows up in the …
> 4 improvements to clinvar submissions page

- CHANGELOG.md
- scout/commands/update/panel.py
- scout/server/blueprints/panels/controllers.py
This PR fixes a bug
1. on a scout db with panel obj without even empty maintainer fields, visit panel pages
2. Just to be sure, again test updating maintainer for the same maintainer field lacking panel obj
**Review:**
> Fix issue with maintainerless panels

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/sv-variant.html
This small PR adds the verification email comment box that was available for small variants also to SVs. Only changes the template, since the backend functionality is shared with SNVs.
I have tested this, and it works as intented for me.
> Add verification comment box also for SVs

- CHANGELOG.md
- scout/server/blueprints/variants/forms.py
Bug fix #1880 .
A bunch of things happened in the latest WTForm releases (release + bugfix release): https://wtforms.readthedocs.io/en/2.3.x/changes/#version-2-3-1
1. On a local instance of scout make sure that all the pages that contain a form validation work (variants of any type, edit institute page)
The pages mentioned above should work, and scout tests as well.
**Review:**
> fix #1880 (WTForm validation error)

- CHANGELOG.md
- scout/server/templates/utils.html
This PR embeds the pedigree svgs in the pedigree panel as scrollable objects. This is a simple workaround to the issues in #1818 without committing to more arcane viewBox javascripting.
1. look at a pedigree and shrink the view until it is obvious the pedigree can scroll
**Review:**
> Scroll pedigree - Fix #1818

- CHANGELOG.md
- scout/server/links.py
This PR fixes the Alamut link for hg38. 
When linking to a specific genome build in Alamut, the link must contain a query like this (GRCh37 is default if nothing is given):
```
3(GRCh38):g.37020386A>G
```
This has been tested and works properly on our setup (with Alamut 2.11), both for GRCh37 and 38.
> Alamut link hg38

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
igv.js has released a bug fixed version containing the fix to our bigBed bug (I've done a nice assonance here!). The bug in question is the one in #1793
Our current master is using a patched version of igv.js at the moment (the version they use for developing in between official releases), so it would be nice to use the current version instead.
1. Install this branch on clinical-db scout stage
1. make sure that bigBed tracks (for instance clinVar CNVs) are displayed correctly
**Review:**
> update igv.js to the newest version (2.5.4)

- .github/CODEOWNERS
- CHANGELOG.md
This PR reverts the use of CODEOWNERS until we have use for it. Up until today, we have been fine with write permissions and requiring reviews from one other contributor.
**Review:**
> Revert CODEOWNERS.

- CHANGELOG.md
- scout/adapter/mongo/case_events.py
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/cases/views.py
Bug fix #1910 
1. To reproduce the bug on a local instance:
1. Add a new institute using the cli command:
`scout --demo load institute -i cust001 -d cust001`
1. Launch the server:
`scout --demo serve`
1. Change the cust000 institute server settings including cust001 in the list of institutes selectable for case sharing, see at the bottom of this pic:
1. Go to the case page and note that cust001 appears in the list of the institutes to share the case with:
1. Share the case with cust001
1. Share the case with cust001, again. This will trigger the bug.
1. Checkout to this branch and the repeated sharing will only flash an error message, instead of crashing the app.
1. Also "unsharing" the case will not cause any error
1. HTML selects of this branch will look smaller and fit …
> Fix collaborate twice

- CHANGELOG.md
- scout/adapter/mongo/variant_events.py
- scout/server/blueprints/cases/views.py
bug fix #1912
1. Use a local instance of Scout
1. Mark a variant as causative
1. Assign an HPO phenotype to the case and mark another variant as partial causative for that specific phenotype
1. Make sure that removing causative works
1. Make sure that removing partial causative works
**Review:**
> Fix remove causative variants

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/links.py
1. In Scout's cancer view, if cosmic ID exists, add a badge "Cosmic". 
2. Hoover over will show IDs No links.
No extras, no links :)
Ref: https://github.com/Clinical-Genomics/scout/issues/1629
Ref: Old pr #1867 
Install and run Scout in cancer view. 
1. If a variant has a Cosmic ID, a badge is shown in Exac-column.
2. Mouse hoover over will show details, among those Cosmic ID:s.
**Review:**
> Add COSMIC Badge (revisited)

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variants/controllers.py
OR
1. In a sample with default gene-panel, select a variant in structural view, then click on "Clinical Structural variants", the default gene-panel should not be lost.
**Review:**
> added default gene panel for non-cancer structural variant view

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/constants/query_terms.py
- scout/server/blueprints/institutes/templates/overview/institute.html
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/views.py
- tests/server/blueprints/institutes/test_institutes_views.py
- tests/server/blueprints/variants/test_variants_views.py
- tests/server/conftest.py
Fix #1922
- Adds a field to filter variants with Tumor AF > than a certain floating point value
- Validates the whole filter on submission. So when some weird parameter is submitted, the search is not performed and an error will be flashed instead
1. Install the branch on Scout stage
1. Go to a cancer case
1. Filter for variants with VAF > than a custom number (try with numbers like 0.25 or 0,25)
1. Try to fill in the form with wrong input for the fields
The functionality should be working:
1. VAF filter should work (compare with VAF for the returned variants)
1. Form validation errors should be returned when the occur
**Review:**
> Add VAF filter in cancer SNV variants filter form

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
Fix #1941  and fix #1940
I've turned the Tumor and Normal alt allele frequency fields to decimal numbers, instead of %, to be consistent with the population frequencies. This way is also consistent with the numbers expected in the filters form above.
So this:
Becomes this:
I've also added a tooltip when you hover on "Tumor" and "Normal", to explain what these numbers are. Example:
Do we need to explain a bit more?
1. Install the branch on Scout stage (or use a local instance with a cancer case loaded) and go to cancer SNV variantS page.
**Review:**
> Turn tumor and normal allele frequencies to decimal and add tooltip

- CHANGELOG.md
- scout/constants/clinvar.py
- scout/server/blueprints/variant/templates/variant/clinvar.html
Fix #1902.
Save "Assertion method citation" to clinVar export form:
And make it exportable in the relative downloadable submission file:
And the downloadable file:
1. Assign a phenotype (OMIM or HPO) to a case and pin one of its variants
1. Go to the variants and click on the "Submit to ClinVar" button. Follow the procedure to save the submission and make sure that the "Assertion method citation" is present in the variants file downloadable from the submission object (button `Download variants file`)
**Review:**
> Export clinVar "assertion method citation" in downloaded clinVar variants file

- CHANGELOG.md
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/templates/variants/utils.html
This PR adds functionality to filter cancer variants on chromosome, start/end in cancer view.
Ref #1926 -customer request.
The functionality is like filtering on the ordinary SNVs/Indels and uses the same backend.
Install `featuer-filter_on_chr-200603` (typo!).
Go to cancer variants, select filter and enter a chromosome, start and end. 
All matching variants will be shown.
**Review:**
> Feature filter on chr 200603

- CHANGELOG.md
- scout/commands/download/everything.py
Fix #1957
1. check that on master branch the `scout download everything` command fails
1. Checkout to this branch and run
- `scout (--demo) download everything`
- `scout (--demo) download everything --api-key a-valid-key`
The functionality should be working and download all the expected files.
**Review:**
> Fix "download everything" command

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/static/form_scripts.js
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/blueprints/variants/views.py
Adds support for cytoband search in cancer variants.
This is a copy of  #1390, but for Scout Cancer.
The cytoband start and end selects are dynamic and their content depends on the selected chromosome. Once a cytoband start is selected it updates the start coordinate in the filters form. End coordinate works in the same way
1. Cytobands collection can be populated in 2 ways:
- `scout setup demo` or `scout setup`
- `scout load cytobands` (--build to specify which build, otherwise both builds are used) 
2. After populating the cytobands collection in a local instance of Scout, go to the demo case, variants page. Use the cytoband start and end selects to filter variants
3.  Go to the structural variants page. Use the cytoband start and end selects to filter variants. …
> Cytoband Search for Cancer

- CHANGELOG.md
- mkdocs.yml
- requirements.txt
- scout/server/auto.py
Fix #1970
1. Go to the Scout test real environment on clinical-db stage and update the Werkzeug module with the following command:
`pip install Werkzeug -U`. Running `pip freeze` should show that the installed version of the library is >= 1.0.
1. Restart Scout with the supervisor command and note that the server can't be started (because of #1970).
1. Install this branch and  restart the server. This time the server should be up and running
1. ** Don't forget to reinstall the old library of Werkzeug (0.16) before leaving the test environment, since other software might be using it as well**
**Review:**
> Handle the ProxyFix ModuleNotFoundError when Werkzeug installed version is >1.0

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/user.py
- scout/commands/delete/delete_command.py
- tests/commands/delete/test_delete_cmd.py
fix #1933 
When the user delete cli command is used it first deletes the user and then it removes it from any case where it is found as case assignee.
**How to test (local implementation of scout is fine)**:
1. setup a demo instance of scout with `scout setup demo`.
1. launch the server and go to the demo case page.
1. Assign yourself to the case.
1. Stop the server and run the following command from the cli: `scout --demo delete user -m clark.kent@mail.com`
The functionality should be working:
- it should say that the user was deleted
- it should say that the user was deleted as assignee from one case
**Review:**
> Remove users as case assignees when their account is deleted

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/views.py
Ref: #1686
Install `feature-#1686_show_internal_name-200707`.
a. Go to Case page:
-Internal ID should show
b. Download CGH
-File name should be <case-id>.<internal-id>.vcf2cytosure.cgh
**Review:**
> Show Internal ID and Add Internal ID to CGH-Download

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
This PR changes the style of the Matchmaker card
Now it looks like this:
On stage this repo in scout-staging, and pick a case with a match in Matchmaker like 
https://scout-stage.scilifelab.se/cust101/A1383
Check out the matchmaker card
**Review:**
- [ x ] code approved by
- [ x  ] tests executed by
> Make matchmaker results scrollable 1654

- CHANGELOG.md
- docs/admin-guide/load-config.md
- scout/demo/643594.config.yaml
- scout/load/setup.py
- scout/parse/case.py
Fix #1989 
The current demo setup doesn't parse the peddy info, so the demo case is missing this info. And when it's uploaded, the case (individuals table) looks like this:
This PR fixes the issue and when the same command is run from this branch the info is not missing any more.
1. From a local instance of Scout, checkout to this branch and `run scout setup demo`
1. Launch the browser (`scout --demo serve`) and go to the demo case page.
Alternative test:
1. Force re-upload the demo case with this other command:
`scout --demo load case scout/demo/643594.config.yaml -u`
Also in this case the individual table should show the peddy info.
Individuals table should show:
- Sex check
- Ancestry prediction
- Parenthood
**Review:**
> Add peddy info (ancestry, sex check, parenthood) to demo case

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/buttons.html
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/blueprints/variants/views.py
This PR adds the column "Dismiss variant" to all the variants tables.
1. Deploy this branch to scout-stating, look at the variant tables for a "Rare disease variant" and then for a "Cancer" variant. Try out the filtering of the table as well since I changed the form a little bit.
**Review:**
> Add action button to dismiss variants from list #2004

- CHANGELOG.md
- README.md
- requirements-dev.txt
This PR adds Black and pre-commit packages to requirements-dev. Since Black is run in Github Actions
I think it's a good idea to have it installed by default when setting up the project.
**Review:**
> Add pre-commit and black packages in dev requirements, edit README

- CHANGELOG.md
- scout/parse/case.py
- tests/parse/test_parse_case.py
This PR adds a sanity check for file loading, changing the priority from bam to cram (alignment_path), warning the user if multiple files were added to config.
1. add an extra non empty bam_file or bam_path entry to an individual that has an alignment_path entry - or vice versa.
**Review:**
> Fix #2011. Add safety check for load config alignment_path.

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/gene_variants.html
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/static/bs4_styles.css
This PR adds a functionality, in the variant list causative variants are now highlighted. The tables style was also improved.
1. Run Scout locally, mark a variant causative.
In the list, the causative variant should be highlighted.
**Review:**
> Highlight causative variants in the variants list #2012

- CHANGELOG.md
- scout/server/blueprints/variants/views.py
This is a much safer fix #2021 
1. Install the branch either locally or on scout stage
1. If testing locally, load the demo cancer case with the following command:
`scout --demo load case scout/demo/cancer.load_config.yaml `
1. Go to the cancer variants and try to filter by some criteria (your choice really)
1. Make sure that variants are filtered correctly
1. Save the filters used using the "save filter" button
1. Reset filter and make sure you see again all variants
1. Load the saved filter.
1. Filter load and filtering itself should work
1. Remove the filter
**Review:**
> Skip validation of a pre-existing variant filter -- Alternative to #2028, because I'm a chicken

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/cases.html
- scout/server/blueprints/institutes/templates/overview/causatives.html
- scout/server/blueprints/institutes/templates/overview/users.html
This PR changes the styling in some pages
1. run this branch in staging (you will need a lot of data and long tables) and check out the users, causatives and institute tables
The tables should look fine
**Review:**
> Remove overflow auto to avoid cut tables from several pages

- CHANGELOG.md
- scout/adapter/mongo/panel.py
- scout/build/panel.py
- tests/build/test_build_panel.py
This PR filters remove leading and trailing whitespaces from the gene panel name
Add a panel with a name that contains trailing whitespaces in your local or stage branch
The uploaded gene panel name should not have trailing whitespaces
**Review:**
> No trailing spaces in new gene panels #2032

- CHANGELOG.md
- scout/commands/delete/delete_command.py
- tests/commands/delete/test_delete_cmd.py
fix #2039.
Current situation is that whenever a user is assignee of one or more cases, if the user is removed using the command line, those cases become inactive. This fix will keep those cases in their status, whichever that is.
**How to test --in a local instance of Scout**:
---> From master branch:
1. Create a dummy user to assign the case to:
`scout --demo load user -u "Dummy User" -m dummyuser@dummysite.se -i cust000`
1. Log in into scout with the dummy users's email
1. Enter the case page and then one of its variants; you should get a notification that the case is active.
1. Assign yourself to the case and log out.
1. Remove dummy user from the command line:
`scout --demo delete user -m dummyuser@dummysite.se`
1. Log in as Clark Kent and note that the case is inactivated
--> Repeat …
> Do not inactivate case whenever the assignee is removed from database using the cli

- CHANGELOG.md
- scout/constants/variant_tags.py
- scout/server/blueprints/variant/templates/variant/buttons.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/components.html
This PR formats the cancer variant tables
1. Deployed this branch to staging
2. Checked out the table of this variant that contains a lot of text.
https://scout-stage.scilifelab.se/cust000/20190327_cancer_T_N/cancer/variants?variant_type=clinical
It should look fine.
The content is still a bit compressed but it has to be with so much text. The other solution is to decrease the text size but then it wouldn't be so readable.
Edit: with shrinked tags and tooltip:
When not hovering:
**Review:**
> Format cancer variants table

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
This PR adds the default panel name to the case page collapsible sidebar.
1. check a couple of cases and click link
**Review:**
> Fix #1449 - panel in sidebar.

- CHANGELOG.md
- scout/adapter/mongo/filter.py
- scout/server/blueprints/variants/controllers.py
fix #2060
1. Install the branch and open the variants page for a case.
1. Create a custom filter
1. Open the same page on another browser tab
1. Delete the filter from one tab and try to delete it from the second tab. It should flash an error message and not crash.
1. Repeat the filter creation and have it displayed on the 2 tabs
1. Remove from the first tab and try to load it from the second tab. Also in this case it should display an error message, no page crash
**Review:**
> Fix filter removal and upload for un-existing filters

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/sv-variants.html
This PR adds fixes a bug
1. Deploy to staging and click on a SV variant tables. Tested locally but I still cannot deploy to clinical-db.
The table header should include Score
**Review:**
> Fix sv variant header labels#2064

- .github/workflows/keep_a_changelog.yml
- CHANGELOG.md
This PR adds a GitHub Action that reminds developers to update the CHANGELOG.md whenever a PR is opened.
**Review:**
> Enforce updates to changelog on PRs

- .github/workflows/build_and_publish.yml
- CHANGELOG.md
- requirements-dev.txt
- setup.py
This PR adds a GitHub Action workflow for publishing the package to pypi.
The event will be triggered whenever a new release is made.
1. Create a new release
The the package should be published to pypi
**Review:**
> Adds workflow to upload releases to PyPI

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
This PR adds a functionality: previous buttons.
It also reverts the STR variants page to previous behaviour (e.g. v4.19 and v4.20 - prior to current master), without the general pagination footer. This can migrate when filters are turned on for STRs.
Feel free to suggest an alternative row layout, e.g. button spacing and alignment. 😸 
1. access snv, sv, str, cancer and cancer_sv variants pages and click all pagination buttons, with and without applied filters to ensure behaviour is as per the button labels
**Review:**
> Fix #2067 - previous button

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- tests/server/blueprints/cases/test_cases_controllers.py
- tests/server/blueprints/cases/test_cases_views.py
Display a warning badge if case default panels' version is older than panel version in database. This PR goes together with #2007
1. Can be done both on stage or a local implementation of scout.
1. Update a gene panel that is the default gene panel of a case
1. Go to the case and see the warning badge
1. On mouseover it should tell you the gene differences between case panel and updated panel.
**Review:**
> Warn users if case default panels are outdated

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
This PR extends a functionality: show VAF on pinned and causative cancer variants on the case page.
Fix #2069!
1. pin / mark variants causative, ideally both tumor-only, tumor-normal and RD and make sure all looks ok and shows intended values
**Review:**
> Fix #2069 - show VAF on pinned and causatives

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/static/bs4_styles.css
While testing #2077 on stage using older cases, I've realized that there are so many differences in genes that the info no longer fits in a tooltip, so a popover looks like a better solution.
1. On stage, master branch, go to a case runned with an older panel, for instance: https://scout-stage.scilifelab.se/cust000/WNB127N
1. Notice that the gene panel differences from the latest panels are a lot:
1. Install this branch and see that the visualization of the message improves
**Review:**
> Move outdated panel info from tooltip to popover

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/gene_variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
This PR adds a tiny styling change
1. Deploy to staging and check this case https://scout-stage.scilifelab.se/cust000/GIAluc14p19fam/variants?variant_type=clinical&gene_panels=OMIM-AUTO
2. Change the browser size to see the table behaviour when changing size
**Review:**
> Improve column naming to avoid strange text shrinking

- CHANGELOG.md
- scout/server/blueprints/variants/views.py
fix #2082
The dynamic gene list generated by the selected HPO terms in a case is not currently recognized as the list of genes to be used by clinical filter, even if it is marked so:
This PR fixes this behavior and introduces the same behavior in cancer SNVs filtering, that currently don't support this feature either
1. On stage, master branch, assign one of more HPO phenotypes to a case, then click "HPO panel":
1. Then select "Use HPO list for clinical filter" option at the bottom of that panel, and click the `Clinical HPO snv variants button`:
1. The variants page, filters field named "HGNC symbols", should be empty and the variants search should return variants from the case default gene panels:
1. Switch to this branch and repeat the search from the case page. Notice …
> Restore HPO panel use in clinical filtering for SNVs and cancer SNVs

- CHANGELOG.md
- scout/server/app.py
fix #2086 
This is a fix to the problem of the PDF coverage report redirecting to the login page. This problem is affecting 2 pages:
- Coverage report, HTML page, when you click on the "PDF" button
- PDF version of the general report. The last section of the report, which is containing the coverage data.
Perhaps there is a better solution to fix this problem, but I haven't found it. Any other suggestion is highly appreciated!
1. Test with one case on stage, for instance this: https://scout-stage.scilifelab.se/cust002/F0015031
1. Make sure that with master branch the 2 errors described above show up.
1. Install the branch and make sure that the 2 errors don't occur any more
Take a screenshot and attach or copy/paste …
> Fix coverage report PDF download

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/buttons.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/static/form_scripts.js
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/blueprints/variants/views.py
- tests/server/blueprints/variants/test_variants_views.py
Fix #2081 
This PR:
- removes the code to dismiss single variants from variants pages (all types of variants).
- Adds a system to dismiss many variants at the time for 
- SNVs (rare disease track)
- SVs (rare disease track)
- Cancer SNVs (cancer track)
Screenshot:
I've tried to apply this system also to cancer SVs and STRS but I had problems:
- cancer SVs  returns an error that I couldn't fix yet 
- and STRS page contains a form to show bam files and since this multi-checkbox system must be included in another form, but you can't have a form inside a form, I just reverted the code to how it was before the dismiss.
Of course the things above might be fixed, but it will take time, and we don't have much time for the patch of current version..
1. On stage, try to dismiss …
> Bulk dismiss SNVs, SVs and cancer SNVs

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/views.py
Fix #2091
Landing page of research variants (SNVs and SVs) should have no gene panels selected.
1. On stage, pick a case with research variants.
1. On current master, note that research variants landing pages are pre-filtered by case default gene panels.
1. Install this branch and make sure that research variants should not be filtered any panel instead
1. Clinical variants instead should be filtered by case default gene panels. 
**Review:**
> Do not filter research variants by panel

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
fix #2097 --> Empty activity panel at the end of  a variant page
The bug is caused by the events being a cursor that becomes empty after a loop in variants controller. Looping over the events is possible if the cursor is transformed into a list.
1. On a local branch, or stage go to a variant and do something on the page, for instance: comment, tag it, pin it, etc.
1. Note that no activity shows on master branch
1. Install this branch and you should see that activity panel is populated
**Review:**
> Transform event cursor to list to avoid having an empty variants event panel

- CHANGELOG.md
- scout/server/templates/utils.html
Fix #2110 
Double quotes in inner HTML probably closed the string content of the popover.
1. Install master branch on Stage and check that this page doesn't render properly: https://scout-stage.scilifelab.se/cust000/643594-300M/str/variants?variant_type=clinical
1. Install the branch and check that same page is looking normal
**Review:**
> use single quotes in inner html badge class

- CHANGELOG.md
- scout/parse/variant/clnsig.py
- tests/parse/test_parse_clnsig.py
fix #2112.
1. Install this branch on Hasta stage.
1. Load a case that before showed warnings (vitalmouse?)
1. Make sure that there are no warnings on reupload
1. Go to a variant that previously caused warnings on upload (significance: "Conflicting_interpretations_of_pathogenicity&_other"). For instance: chr6, start:26091179. When clicking on the variant page, it should show the correct significance (conflicting_interpretations and other)
**Review:**
> Fix splitting multiple clnsig terms in variant parsing

- CHANGELOG.md
- scout/server/templates/utils.html
Current master has the following bug: whenever a user tries to update a comment (case comment but possibly variant comment) then the latest comment is updated. This PR fixes it.
1. Install on Scout stage.
1. Create several comments at the case level and the variant level.
1. Try to edit them and make sure that the right comment is edited every time
**Review:**
> Edit the right comment

- CHANGELOG.md
- scout/parse/variant/clnsig.py
- tests/parse/test_parse_clnsig.py
fix #2123 
I've been testing with some variants and I think the error occurs when the variant has clnsig values with no accession. In #2114 I've been kind of fixing the same situation when the clnsig has accession values and the't why this problem is still there in this case.
Clinvar parsing in Scout has been changing over the years and for backward compatibility we have kept old code and added new lines without really planning what we expect from the pipelines. And that's why we get unexpected situations and different keys and values from MIP and BALSAMIC. We often don't know if something is wrong unless a user complains about warnings. In the future we should simplify this code, otherwise it's too prone to bugs.
Anyway, this should fix the error in the issue.
1. Keep in …
> Fix parsing multi-cnlsig vars when clnsig acc is None

- CHANGELOG.md
- scout/server/blueprints/institutes/views.py
- tests/server/blueprints/institutes/test_institute_views.py
Fix #2020 --> whenever a database contains many variants (stage and prod server), if a user provides a gene not in database then the search is performed on all genes, and that causes a timeout in the page.
This fix prevents a search if no valid gene is provided in the case_variants page form. If no valid gene is provided then there is a flash message to the user with a warning and the page is redirected to the previous page.
1. On clinical-db stage, current master, go to an institute page and then to "All SNVs and Indels" page. Input a gene that doesn't exist in database.
1. Notice that page times out.
1. Install this branch and repeat the search.
1. This time it should show a warning instead and the page will not timeout.
The functionality should be …
> Perform gene variant search only if user provides genes and at least one is in database

- CHANGELOG.md
- scout/server/templates/utils.html
This PR adds a return to the comments section when comments are edited, deleted or added.
1. Locally, try submitting, editing and deleting a comment
After the request went trough, the view should be at the comment section
Case page:
Variant page:
**Review:**
> Return to anchor after submitted comment

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/templates/variants/variants.html
1. on a MIP9 case, view variants, variant and general report and note that CADD-values are rounded to one decimal place.
**Review:**
> Round CADD

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
fix #2139 --> Whenever the other causative variant has no hgnc symbol, display hgnc id instead!
**How to test on a local scout instance (scout demo)**:
1. load another case into cust000: case  643595 that is the exact replica of test case 643594.
1. Go to case 643595, variants page, and in variants filter UNcheck the test panel, so that all variants are shown:
1. Mark as causative a couple of variants that have no gene symbol, for instance the one ranked 1 (gene 14931) and 12 (gene 12015).
1. Go to the other case page and see two empty lines under the other causatives.
1. Switch to this branch and make sure that the other causatives under the case 643594 are now shown (their hgnc id).
1. Bonus test: mark POT1 as causative on case 643595 and see that "POT1" is shown under the other cases …
> Fix empty other causatives lines

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
1. open a case with matching causative and / or matching managed variants
1. note that managed variants and causative variants are shown folded with a number of variants until clicked
**Review:**
> Fix #2153 - hide causatives subtly

- CHANGELOG.md
- Dockerfile
Fix #2178 
Pango needs a font lib that is missing in the current Dockerfile. After installing it the download of the PDF report works as it should
**How to test -- locally**:
1. Stop any running mongodb service
1. From current master, start the demo using the command:
`docker-compose up -d`
1. Open a browser to the demo instance of Scout -> http://localhost:5000/
1. Make sure that the download of the PDF report doesn't work
1. Turn off the containers with the command:
`docker-compose down`
1. Switch to this branch and build the Docker image like this:
`docker build -t myscout:latest .`
1. Modify the docker-compose.yml file to use myscout instead of the image pulled from clinical genomics:
1. Save and restart docker-compose as in step 2
1. Now the PDF download should work 
**Expected …
> Add missing font lib required by Pango in Docker file

- .github/workflows/build_and_publish.yml
- CHANGELOG.md
Builds the Docker image and tags with it repo version tag and "latest", Pushes both images to Docker Hub. 
fix #2181
1. Locally I'll try on a forked repo, and I'll push to my user's Hub
**Review:**
> DockerHub push action on new release tag

- CHANGELOG.md
- scout/build/case.py
A scary bug in current master that would have made it impossible to upload any sample without pre-assigned phenotypes in the config file. Good that I've found it before deploying! :sweat_smile:
fix #2198 
Try to upload the cancer demo file (doesn't have synopsis, cohort and phenotype info on the config file): `scout --demo load case scout/demo/cancer.load_config.yaml`
When using master branch the case won't upload
When using this branch the case will be loaded into Scout
**Review:**
> Bug fix --> uploading of cases where no phenotype is specified in config file

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/views.py
Bug fix #2207 
1. On a local instance of scout, load the demo case
1. Strs should show in their respective page
**Review:**
> Fixed missing str vars from browser page

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/variant.py
- scout/build/case.py
- scout/commands/export/case.py
- scout/commands/export/export_command.py
- scout/commands/export/export_handler.py
- scout/commands/export/panel.py
- scout/commands/export/variant.py
- scout/commands/load/case.py
This PR fixes some problems with the export cases command.
The date time objects was not serialised in a correct way. Previously they where dumped in the json string as `datetime.datetime(2019, 6, 3, 10, 13, 47, 762000)` which is not possible for a json decoder to read. Now they are serialised as standardised strings on the format `"2020-05-06T09:26:04.348000"`
When running command `scout export cases --status solved` the events was not collected which made it impossible to fetch cases together with the `--within-days` parameter
When querying `get_causatives` with a case_id for a case without causatives there was a syntax error
These where also serialised in the wrong way before. Previously they where dumped to json like `ObjectId('5e3185fd124f63addb79384b')` which can not be parsed, but …
> fix export command

- CHANGELOG.md
- Dockerfile
- README.md
- setup.py
Installed requirements.txt in the setup
1. `pip install scout-browser`  in a clean environment and make sure that it runs by executing any cli command
**Review:**
> Reintroduce requirements install in setup

- CHANGELOG.md
- scout/commands/delete/delete_command.py
Print delete variant command output and a \t separated table ad and add to the output:
- analysis date
- instritute
- case track
1. Load some demo cases locally: demo case + cancer case?
1. Run the scout delete variants command with preferred parameters
1. Check that output contains a header and one line for each case with removed variants. Example:
`scout --demo --loglevel WARNING delete variants -u clark.kent@mail.com  -status inactive -rank-threshold 10 -variants-threshold 1 --dry-run`
**Review:**
> Reformat output or variant delete command and add analysis date, track and institute

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/links.py
This PR adds one more left over gene link to cancer variant pages.
**Review:**
> Fix #1239 comment - add CIViC gene link

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/commands/delete/delete_command.py
- tests/commands/delete/test_delete_cmd.py
1. Run the delete variants command with and without the exclude-ctg param and see the difference
1. If you exclude a variant category from deletion all variants of that category will be left, regardless of their rank score
**Review:**
> Exclude one or more variant categories in variant delete command

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
Marrvel has recently (last summer I think) updated the website to v2 (beta).
I've tried to update the input fields to query Marrvel v2 but without success. The thing is I don't understand the name of the new input fields, check here: https://github.com/LiuzLab/MARRVEL2/blob/master/src/app/components/search-box/search-box.component.html
But I managed to fix the link to the v1 of the portal, so at least the links are not broken. Fix #2220
1. Install this branch and go to a variant, check that the Marrvel link works.
**Review:**
> Fixed link to Marrvel

- CHANGELOG.md
- scout/server/links.py
1. check a protein changing and a silent variant. The TP53 PHANTM variant link icon should only appear on amino acid changing variants.
**Review:**
> Fix #2244-b: dont TP53 link to silent aa change.

- CHANGELOG.md
- scout/adapter/mongo/query.py
- tests/adapter/mongo/test_query.py
fix #2260. This bug is my fault, when I rewrote the get_similar_cases function I have missed to fix all the calls to it. This was a tricky one!
**How to test, on a local instance of Scout**:
1. To replicate on a local instance, master branch, upload the clone of the demo case:
`scout --demo load case scout/demo/643595.config.yaml`
1. Start the server (`scout --demo serve`) and go to this page: `http://localhost:5000/cust000/gene_variants`
1. Search for HGNC symbol "POT1", rank score "5", and Phenotypically similar case "643594"
1. The browser should crash
1. Switch to this branch and repeat
1. The browser should NOT crash
**Review:**
> Fix gene variants query with similar phenotype

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/gene_panel.html
fix #2269
Changes the style of case gene panels multiselect from this:
To this:
1. Install locally or Scout stage and see the difference from master. You might need to clear the cache
**Review:**
> Better panels multiselect

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/variant_loader.py
- scout/parse/case.py
My first scout hacking in 8 months turned into a 3 hour debugging session with minimal code changes in the end... :)
We've occasionally had compounds appear as "not loaded" (and links not working) although they are certainly loaded. Turns out get_coding_intervals() would always use hg19 intervals, thus sometimes causing variants from the same gene to be processed in different "bulks". This fixes that.
> Make get_coding_intervals() in load_variants() aware of genome build.

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
fix #2302 
Problem: when a cancer variant is dismissed with a [cancer-specific dismissed option](https://github.com/Clinical-Genomics/scout/blob/1d48b12e47b78d7f7765d0b6506abeb3b4245f80/scout/constants/variant_tags.py#L242), then the cancer variantS page (of the same type of the variant) crashes
- Locally, load the demo cancer case and dismiss a SNV or SV (or both) with one of the cancer specific reasons
- Go back to the variantS view and notice that it is broken on master branch
- Switch to this branch and the view should work again
**Review:**
> Fix dismissed cancer variants view

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/templates/cases/individuals_table.html
This PR fixes 3 things:
- Bug that causes the app crashing when a cancer case doesn't have a default tumor_purity value (fix #2310)
- Broken tooltips on case page when case doesn't have any associated default gene panel (#2307)
- Potential bug in general report whenever a case has a read depth that is None (it occurred to me with a variant of the demo cancer case)
**How to test - locally**:
1. on master branch, remove the tumor_purity field from the demo cancer config file and load the cancer demo case with the command:
```
scout --demo load case scout/demo/cancer.load_config.yaml
```
1. While staying on master branch, go to the case page of this demo cancer case and notice that crashes with the error described in #2310
1. Switch to this branch and the error should be gone. You should be …
> Relax tumor purity check and fix missing tooltips on cases with no default panels

- CHANGELOG.md
- scout/server/links.py
This PR  fixes a bug.
1. note that synonymous variants in TP53 still have a `p.=` `HGVS_p` string and thus get a mutatnTP53 link.
2. apply patch and see it dissapear
**Review:**
> Silence tp53 link synonymous

- CHANGELOG.md
- scout/adapter/mongo/query.py
Fix #2313.
To reproduce on a local instance of Scout:
- Install demo case (`scout setup demo`)
- Install other demo case (`scout --demo load case scout/demo/643595.config.yaml`)
- Start the app and go to this page:http://localhost:5000/cust000/gene_variants
- Search for POT1, rank score > 15 in similar case 643595
**Review:**
> Fix gene variants search when looking for similar cases and none is found

- CHANGELOG.md
- scout/server/blueprints/variant/views.py
Fix #2317 
The bug happens when for instance you have 2 browser tabs open on the same variant and you remove one acmg classification from it, If in the second browser tab, without refreshing the page, you click on the classification link, the app will crash
1. Create an ACMG classification for a variant (rare disease, not cancer) and do the steps described above.
1. With master branch the app should crash
1. Using this branch you shoudn't just get an error message and it shouldn't crash
**Review:**
> Redirect and display error when trying to open a non-existent ACMG classification

- CHANGELOG.md
- docs/admin-guide/containers/container-deploy.md
- docs/user-guide/README.md
- mkdocs.yml
- requirements-dev.txt
I've realized that in a previous PR I forgot to include the links of some new doc files in the mkdocs file. I'm adding these missing file now and I'm fixing also a couple of other links that didn't work from before. 
Note that **you might need to install mkdocs as a dependency**.
1. run `mkdocks serve` on master branch and make sure these pages don't work:
- From http://0.0.0.0:4000/user-guide/ the links to the ACMG classification and the dashboard (on the bottom of the list)
- http://0.0.0.0:4000/admin-guide/containers/container-deploy/
- http://0.0.0.0:4000/admin-guide/containers/kubernetes/
- http://0.0.0.0:4000/admin-guide/containers/systemd/
Run `mkdocs serve` from this branch and the links above should work
**Review:**
> Add missing links in documentation

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
See issue for details.
1. select IGV for a variant on master, verify that the gene is not visible at ordinary zoom
2. verify that it is directly visible with patch.
**Review:**
> Fix #2323 - throttle back IGV.js to 2.7.0 until a fix is available

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
Fix #2345 by setting SNV variant view IGV initial window end to center from variant start rather than end.
**Review:**
> Center igv on variant start

- CHANGELOG.md
- scout/server/blueprints/institutes/forms.py
- scout/server/blueprints/institutes/templates/overview/institute_settings.html
- scout/server/blueprints/institutes/templates/overview/utils.html
This PR adds a functionality:
- Allow only admin users to modify the Loqus instance in use for the institute
- Transform the loqus textfield of this form into a select with only existing loqus instance ids as possible values
fix #2352 
**How to test - local scout demo**:
1. Create a new user that has not an admin role: 
```
scout --demo load user -i cust000 -u "Diana Prince" -m wonderwoman@dc.com
```
2. Log in with this user and see the difference between master  branch and this branch (The loqus field should not be visible on the bottom of the institute settings in this branch)
3. Log out and login with Clark Kent (that is an admin) and see the difference with master branch (on master you should have a textfield accepting any value and on this branch a select showing only one value --> …
> Stricter LoqusDB management in institute settings

- CHANGELOG.md
- scout/server/blueprints/cases/static/case_images.js
Install patch. Now ideograms have a border. 
*No border*
*Border*
**Review:**
> Add Image Borders

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/templates/utils.html
I've started working on extending the phenotyping of cases including the phenomodels and I've realized that there are components that take too much space in the page.  This PR changes the style of synopsis and comments. 
**Case page** changes from this:
To this:
**Variants pages** change from this:
To this:
**Review:**
> More compact synopsis and comments

- CHANGELOG.md
- scout/adapter/mongo/variant_loader.py
1. try loading an STR file produced with Stranger 0.7 and note how few variants are loaded if rank score threshold is at 5 or higher
2. try with patch version and find variants loaded
**Review:**
> Load STRs regardless of rank score threshold

- CHANGELOG.md
- tests/commands/download/test_download_hpo_cmd.py
Fixing a test failing when the real resource is not available. Real resource: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/util/annotation/genes_to_phenotype.txt
1. Pytest should pass
**Review:**
> Patch the HPO download resource correctly in a test

- .gitignore
- CHANGELOG.md
- scout/commands/load/research.py
This PR changes the behaviour of the CLI so that it does not exit fail if there are no research variants when uploading reseach variants.
The command `scout upload research` will not exit fail if there are no variants
**Review:**
> handle none upload research

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/str-variants.html
STR reference size was duplicated on the hover, and also showing the wrong number. It has a column of its own, so we remove it for now.
**Review:**
> Fix STR hover reference size

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
- scout/server/blueprints/variant/templates/variant/tx_overview.html
- scout/server/blueprints/variant/utils.py
This PR adds tooltips and code docs of manual_inheritance handling: collected for default panels.
1. add a gene with a manual inheritance an disease transcript annotation to your favourite gene panel
2. check that on a variant, the manual inheritance is displayed with tooltips when your panel is selected as default for the case
**Review:**
> Tooltip manual inherit

- CHANGELOG.md
- scout/server/blueprints/panels/templates/panels/panels.html
- scout/server/blueprints/panels/views.py
Fix #2400
Improve the form validation by:
- Making the customer field select mandatory
- Checking that provided gene panel ID contains only alphanumeric chars and underscore
- Display the name of the file containing panel info after you click "browse"
- Is panel display name is not provided, use panel ID, after replacing _ with spaces 
1. Create a panel and check all the above changes (you can use the demo panel as the file to upload)
**Review:**
> Improve create new gene panel form validation

- CHANGELOG.md
- scout/server/blueprints/institutes/forms.py
- scout/server/blueprints/institutes/templates/overview/institute_settings.html
- scout/server/blueprints/institutes/templates/overview/utils.html
- scout/server/blueprints/institutes/views.py
- scout/server/config.py
- scout/server/extensions/loqus_extension.py
This PR:
- Prevents a bug caused by the server settings form initialized before the loqus instance settings and resulting in an empty Loqus instances select in institute settings
- Removes some code from #2349, that looks intimidating already.
**Prepare for test, locally**:
- Edit demo config file by uncomment the following lines:
```
LOQUSDB_SETTINGS = [
{"binary_path": "/miniconda3/envs/loqus2.5/bin/loqusdb", "id": "default"},
{"binary_path": "/miniconda3/envs/loqus2.5/bin/loqusdb", "id": "hejhej"},
{"binary_path": "/bin/yetanother/loqusdb", "id": "Mayo"},
]
```
- Clone and install in a dedicated environment [loqusDB executable](https://github.com/moonso/loqusdb).
- Replace the binary_path of the 3 instances in the settings with the path to the loqus binary, something like this: …
> Bugfix - collect LoqusDB instances correctly in institute settings

- CHANGELOG.md
- scout/server/templates/utils.html
The page of a demo case from a genomic course is squished to display both lists
Before:
----
After:
**Review:**
> Remove eyesore yellow and replace it with background color in even lines of lists (variant and case pages)

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/tx_overview.html
Fix #2404, specifically https://github.com/Clinical-Genomics/scout/issues/2404#issuecomment-790530420
VEP refseq transcripts have always an empty list of refseq ids so the field prints always "Check complete list of transcripts". This fix replaces that message with the transcripts ID, which is a refseq ID.
**Review:**
> Use VEP RefSeq ID if RefSeq list is empty in RefSeq transcripts overview

- CHANGELOG.md
- Use VEP RefSeq ID if RefSeq list is empty in RefSeq transcripts overview
- Bug creating variant links for variants with no end_chrom
**Review:**
> Patch release 4.30.2

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/views.py
- tests/server/blueprints/cases/test_cases_views.py
Fix #2418 
Changed
- Added number of group of cases in panel header
- Made a scrollable div so it doesn't expand so much if there are many cases
- Moved the "add new group" button to the panel header (top right corner)
- Made the whole thing more compact
- Every time a change happens the page redirects to the panel as an anchor
Before:
After:
**Review:**
> A more compact case groups panel

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/cases/controllers.py
fix #2440 
The error was probably due to the fact that only genes from HPO panels created based on HPO terms are exportable. Whenever a user adds a custom gene not associated to a specific HPO term, then this genes is added into case["dynamic_gene_list"], that is not actually contemplated in the export.
This PR fixes this
1. Add one or more genes to the HPO panel by using the dedicated form:
1. Export the panel and see that the genes are written to the export file
**Review:**
> Include also genes from dynamic_gene_list in HPO gene list export

- CHANGELOG.md
- scout/constants/variants_export.py
- scout/server/blueprints/variants/controllers.py
- tests/server/blueprints/variants/test_variants_controllers.py
This PR adds a functionality:
- merges 3 columns relative to the canonical transcript into one: `Canonical_transcript|HGVS|protein_change`
- creates another column for the primary transcript:  `Primary_transcript|HGVS|protein_change`
- Fixes a bug caused by using default genome build 37 when exporting these info from variants page
Partial fix #2398 and possible fix #2429 
1. Go to variantS page, filter and export variants.
2. Check exported transcripts against transcripts specified on each variant's page
**Review:**
> Export primary HGNC transcript in variantS export file

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
As part of https://github.com/Clinical-Genomics/scout/issues/2324 this PR adds the QUAL value to the "variant summary" section of the variants detail page.
At least for Sentieon DNAscope this value is much more informative than GQ, which is always 99...
> Show variant QUAL in summary.

- CHANGELOG.md
- scout/demo/cancer_coverage_qc_report.html
Fix #2442, it wasn't that complicated! Tested on Chome and Safari
1. Load a demo cancer case via config file into a local scout instance:
```
scout --demo load case scout/demo/cancer.load_config.yaml
```
1. Check how the PDF version of the coverage_qc_report looks on master and this branch
**Review:**
> Add lanscape orientation style to demo cancer coverage and QC report HTML file

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
fix #2476
A tiny fix to the annoying issue of a popover showing whenever the mouse is in the case groups panel (no matter where). 
With this PR it shows only if the mouse is over the panel header. My bad, I should have tested better when I touched this code last!
**How to test:**
Check moving the mouse in the case groups panel
**Review:**
> A more discrete case group tooltip

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Remove 2 reports from the sidebar of cancer cases: "mtDNA report" and "Coverage" report
- fix #2480 and fix #2482 
1. Install this branch on clinical-db stage and go to a cancer case. 
2. See the difference in the available reports for the case between master branch and this branch
**Review:**
> Remove mitochondrial and coverage report from cancer cases sidebar

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/clinvar.html
Fix #2491, that is a result if my latest changes in the ClinVar page (PR #2474). The other pages I've changed in that PR are fine, because the code first checks if the variant has a dbsnp id before splitting it.
1. try to add a variant with no dbsnp id to a ClinVar submission in Scout
**Review:**
> fix bug #2491

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/utils.html
Current master contains a bug that caused the page to crash when filtering by SNV variants that don't contain the key `alt_frequency`
Fix #2503 
**How to test -> locally**:
1. From master branch, load demo variants with the command:  `scout setup demo`
2. start the app (from master branch): `scout --demo serve`
3. Go to variantS page (SNV variants) and filter by chromosome (MT chromosome)
4. Notice that the page crashes
5. Switch to this branch and repeat the search, the page should NOT crash
**Review:**
> Bugfix 2503

- CHANGELOG.md
- docker-compose-dev.yml
This PR adds a simple modified docker compose to use local build dir instead of docker hub images for scout web and cli.
1. `docker-compose -f docker-compose-dev.yml up`
2. Scout with a demo instance should now be available on port 5000
**Review:**
> Simple Docker compose dev file

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/utils.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- Open variants in new a new window (from variants page) . Fix #2512 
- Open overlapping variants (SNVs and SVs) in a new window, when clicked on a variant page.
1. From variantS page (snvs, svs, strs, cancer vars), when a user clicks on variant link, the variant page is opened in a new window.
2. Check that overlapping variants in variant page (SNVs and SVs) open correctly in a new window. This will be better tested on clinical-db
- Try to open variants from all types.
**Review:**
> Open variant in a new window

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/phenomodel.html
This PR adds functionality to make Phenomodels subpanels collapsible
1. Download branch feature/2338
2. Go to the tab Phenomodels
3. Click on a panel
**Review:**
> Feature: Make Phenomodels subpanels collapsible (#2338)

- CHANGELOG.md
- scout/server/links.py
Fix #2479 --> Change the link from gnomAD v.2 (build 37) to gnomAD 3 (GRCh38) for mitochondrial variants from cases sequenced in build 37. Since MT variants are not aligned using genome build 37, but 38 (kindof).
1. Locally or on clinical-db. 
2. On master, under frequency, notice that all MT variants contain links to gnomAD and that this link doesn't work (it tells you that `Mitochondrial variants are not available in gnomAD v2.1.1`
3. Switch to this branch and see that the gnomAD link works because it points to gnomAD 3 instead of gnomAD 2.1.1
**Review:**
> gnomAD 2 --> 3 for MT variants

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
Fix #2534 
The database document of a real rerunned case looks like this (example: https://scout.scilifelab.se/cust003/15029):
A non-rerunned case that gets the same `rerun` label looks like this (example: https://scout.scilifelab.se/cust003/46):
This PR is fixing this behavior.
- Locally, on master branch, load a case and re-create the database situation shown in the second figure above.
- Make sure that this branch doesn't show the case as rerun in the case list page.
**Review:**
> Improved check if case was rerunned

- CHANGELOG.md
- scout/server/blueprints/dashboard/controllers.py
- scout/server/blueprints/dashboard/forms.py
- scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
- scout/server/blueprints/dashboard/views.py
- tests/server/blueprints/dashboard/test_dashboard_controllers.py
Fix #2550 by refactoring the dashboard filters.
Changes from master:
- When first landing on the dashboard page now, it **takes a long time to load since it's already performing a search** (one that you might not even be interested in). Now you land quickly on a blank page, where you can decide what to search for.
- There is a **bug in current master due to the fact that the user is allowed to perform a free search on the query filter** (try to write "whatevs" in that field and see the result. 
- I'm changing the dashboard web page so that the free text field mentioned above can't give error, since it's used together with a select specifying the type of search for the term.
Basically from this:
To this:
- **Flashing a message when no result is returned instead of crashing**
- Moving to …
> Refactor dashboard searches 

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/constants/case_tags.py
- scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
- Small fix in dashboard template: see this comment https://github.com/Clinical-Genomics/scout/pull/2551#discussion_r617424400
- Allow filtering by Analysis track both on cases page and dashboard
1. Install on a local instance of Scout.
2. Check that dashboard page, panels and filter query looks fine.
3. Try filtering cases and dashboard data by analysis track (option should be visible in the select) and the query should work
**Review:**
> Filter cases by track, in cases and dashboard pages

- CHANGELOG.md
- scout/adapter/mongo/hgnc.py
- scout/server/blueprints/genes/controllers.py
- scout/server/blueprints/genes/views.py
- tests/adapter/mongo/test_gene_handler.py
This PR fixes a bug where the user could not search for genes from grch38 in `/genes`
1. goto `/genes`
2. search for "NOTCH2NLA" (in grch37 and 38)
3. search for "NOTCH2NLC" (in grch38)
- Genes should be found regardless of genome build
- Should only show one hit per gene, regardless if a gene is present in multiple genome builds
**Review:**
> /api/v1/genes queries all genome builds by default

- CHANGELOG.md
- scout/constants/__init__.py
- scout/constants/clinvar.py
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/clinvar.html
Fix #2570.
Description of ClinVar data fields is here: https://www.ncbi.nlm.nih.gov/projects/clinvar/ClinVarDataDictionary.pdf
In this document they mention that the models of inheritance to be used are in this document: https://ftp.ncbi.nlm.nih.gov/pub/GTR/standard_terms/Mode_of_inheritance.txt
1. Pin a variant and check that the inheritance model field is displayed correctly in the ClinVar form.
2. Save submission and export it to file.
3. Check that inheritance model is correct on exported file or that is missing if no model was selected
**Review:**
> Import and use standard models of inheritance defined in ClinVar constants

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
fix #2585  
This bug is caused by an error in the code that handles the loop through the primaty transcripts of a variant. When the variant has no primary transcripts the page crashes.
**Review:**
> Fix bug causing exported variants to crash when one of the variants has no primary transcripts

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/build/case.py
- scout/models/case/case.py
- tests/conftest.py
`genome_version` is a field that gets populated every time a case is created from parsing a yaml file. Our prod cases have a None value for this key and the key/value is not used anywhere downstream in the app anyway. Fix #2578
**Review:**
> Remove parsing of case `genome_version`, since it's not used anywhere downstream

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/utils.html
Fix #2588
1. Go to variantS page 2 and dismiss some variants. When page redirects you should still be on variantS page 2
**Review:**
>  Redirect to last visited variantS page when dismissing variants from variants list

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
This PR fixes the padding inside (matching causatives, matching managed variants) panels #2542 
I mocked data locally and it works as it should.
1. After deploying to stage
2. Go to: https://scout-stage.scilifelab.se/cust002/F0016354/9a045de2b8925769a83dcbf638910f5b
The text on both panels (Matching causatives, Matching managed variants) should align like the screenshot.
**Review:**
> Remove padding from (Matching causatives from other cases) panel

- CHANGELOG.md
- requirements.txt
- scout/constants/indexes.py
- scout/server/blueprints/institutes/views.py
- scout/server/blueprints/login/controllers.py
- tests/server/blueprints/login/test_controllers.py
To apply to an existing installation, one will also need to
```
scout index --update
```
I haven't checked yet, but something reminds me that perhaps it is best just to add the same indices manually to prod when the time comes. We should perhaps also take a quick peek at current indices before running an update on stage. These ones should be fine, but there could be some other pending change that will slow things down more for a bit. Over the long weekend would actually not be at all bad for that.
1. test user events view
2. test causatives view
3. test a case_verb intense view, like hovering over compounds to shade for dismissed ones
Take a screenshot and attach or …
> Fix causatives view

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/query.py
- scout/adapter/mongo/variant.py
- scout/server/blueprints/variants/views.py
- tests/adapter/mongo/test_query.py
Gene filter since v4.21 used gene panel hgnc symbols for filtering, instead of the panels assigned on load. This harmonises well with gene symbol queries and arbitrary lists. However, if a gene symbol changes, even if hgnc_id stays the same, queries will miss the gene. Manually added search symbols go through validation checks. To avoid similar issues in the future, always gene filter with hgnc_id.
1. Filter demo case with the test1 panel. Note a gene.
2. Re-symbol the gene in a panel, e.g. 
3. Before checking out this branch, filter with the gene of choice and note that you no longer find the gene with the panel, but can find it with manual lookup of its actual hgnc symbol (e.g. "POT1")
4. Apply patch and note that the gene list filter is working …
> Fix #2614 - always use hgnc_id for gene filter

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
Fix #2618 
Fix a typo causing the display of an error every time a patient is matched against external MatchMaker nodes. It's not really a bug in the matching (which occurs), it's just saying an error occurred.
1. Install the branch on scout stage (clinical-db)
2. Go to any case as a user that has MatchMaker permissions (grant yourself permissions using the command line if you are not one)
3. Add a case with variant and/or phenotypes to matchmaker and match it again one or more external nodes
4. The matching should not return error
**Review:**
> Fix mme match external

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
Fix #2623
Prevent the variantS page to crash when a variant_obj document to be updated is too big (> 16 MB). Display instead a warning message.
I have no idea why this size error occurs tho!
1. Go on clinical-db stage and try to display the variantS page from this case: https://scout-stage.scilifelab.se/cust003/2015
1. Master branch should crash
2. This branch should display all variants and the problematic variant with a warning
**Review:**
> Prevent crashing when updating too large variant documents

- CHANGELOG.md
- scout/server/blueprints/institutes/views.py
Fallback for hgnc_symbol-lacking variants for causatives sorted.
**Review:**
> Sort strings

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/tx_overview.html
This fixes an issue when the variant view would crash if a gene hasn't a primary transcript
**Review:**
> Fixed crash when gene hasnt a primary_transcript

- CHANGELOG.md
- scout/server/blueprints/variants/static/form_scripts.js
- scout/server/blueprints/variants/templates/variants/str-variants.html
Some issues remained / arose with filter lock with the new release candidate.
1. A js error on the STR filters (no chr_pos to split) disabled both populating chr and filter lock
**Review:**
> chr pos split js safer for STR view

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
- scout/server/blueprints/alignviewers/views.py
- scout/server/blueprints/variant/templates/variant/variant.html
Tentative fix #2636
1. Install on stage and check that tracks from this variant work: https://scout-stage.scilifelab.se/cust003/14022/e4f6bda7d7150a2c455ee12e6a41e2c9
**Review:**
> Send partial file data to igv.js when visualizing sashimi plots with splice junction tracks

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/str-variants.html
This PR adds:
A Pedigree panel on the STR page when the length of (case.madeline_info & case.individuals) > 1
**Review:**
> Add a Pedigree panel in STR page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/institutes/templates/overview/causatives.html
- scout/server/blueprints/variant/templates/variant/variant.html
This PR adds:
1. Update and style STR case report.
When opening a general report as a web page:
When downloading a general report as a PDF:
STR variants pinned & marked causative:
Variant page (without angle brackets):
**Review:**
> Update and style STR case report table

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- tests/server/blueprints/variants/test_variants_controllers.py
Fix #2649
1. On clinical-db stage go to a case that has research variants
2. From research variants page look for a gene that is not in case clinical list (DNAH14?)
3. Make sure you get no warnings
**Review:**
> Switch off non-clinical gene warnings when filtering research variants

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
1. For a case with pinned or causative deleted / no longer loaded variants, Scout should no longer crash
**Review:**
> Fix #2655 - dont populate deleted pinned/causatives

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- scout/server/static/bs4_styles.css
This PR adds:
Fix the height of all dropdowns in Clinical SNV and INDELs view to be able to select an option from a dropdown in search without the new "bar" (static position)  overlap the dropdown.
I tested it on (Region Annotations, Functional Annotations), and its works as it should.
**Review:**
> Gene panel dropdown height

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
Fix #2664.
- Change color of message of the warning message when gene is not in gene panels to blue
- Clearer warning messages in general
1. Install on stage or locally and do filter variants using the HPO list, gene names and gene HGNC Ids
**Review:**
> Clearer warnings in variants filters, gene search

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
Fix #2663.
Hover on the popup and you'll see this:
**Review:**
> Popup to explain why there are missing links in Loqus observations panel

- CHANGELOG.md
- scout/constants/indexes.py
Attempting to solve #2665 for Lund. Adding back an index for variant_id to the constants, that is used when unrolling the query cursor into a list. An alternative might be to try to recast the positional ids to case id containing document ids, but that will take a bit of error prone logic. Solna still has variant_id in prod, though it was so to speak deprecated, and it is confirmed to take hits on causatives search. It is still slow, but at least one order of magnitude faster than in Lund.
**Review:**
> Case index

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
- scout/utils/ensembl_rest_clients.py
- tests/conftest.py
- tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
- tests/utils/conftest.py
- tests/utils/test_ensembl_rest_clients.py
While working on another bug I've realized that when you click on the splice junctions, the igv view is not centered over the gene (the gene is there, but generally relegated to a small part of the view):
Master branch:
This branch fixes this bug and the gene view becomes like this:
1. Run` scout setup demo` and check the splice junctions of any variant
**Review:**
> Fix splice junction tracks not centered over genes when variants are in gene build 37

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/tx_overview.html
This just adds some template code to show ensure that the MANE refseq transcript is shown first in the list of refseq transcripts, hightlight it with a badge, and show the transcript version number.
Before:
After
> Highlight and show version number for RefSeq MANE transcripts

- CHANGELOG.md
- scout/demo/cancer.load_config.yaml
- scout/server/blueprints/cases/templates/cases/case.html
This PR adds a functionality: rename cancer clinical variants button more clearly to indicate the cancer (somatic) and constitutional (germline) variants.
1. add variants files to regular, cancer and research to a cancer track case e.g. in `scout/demo/cancer.load_config.yaml`
```
vcf_cancer: scout/demo/cancer_test.vcf.gz
vcf_cancer_sv: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz
vcf_snv: scout/demo/cancer_test.vcf.gz
vcf_sv: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz
vcf_snv_research: scout/demo/cancer_test.vcf.gz
vcf_sv_research: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz
vcf_cancer_research: scout/demo/cancer_test.vcf.gz
vcf_cancer_sv_research: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz
```
Also check an RD case to make …
> Fix #2510 - cancer case variants button names

- CHANGELOG.md
- scout/build/case.py
- scout/server/blueprints/variants/controllers.py
- tests/build/test_build_case.py
Fix #2608
1. Edit demo case config file with a gene panel that doesn't exist (example: `gene_panels: [panel1, hello]`)
2. Load the case with `scout setup demo` command or load it manually with `scout --demo load case scout/demo/643594.config.yaml --update`
3. Master branch should crash, this branch should load the case with a warning.
**Review:**
> Show a warning if case config file has missing panels, do not crash

- CHANGELOG.md
- scout/demo/cancer.load_config.yaml
When the demo cancer case is loaded in current master loads the somatic variants as germline variants and the somatic variants lists are empty
1. In a local Scout instance, master branch, load the cancer demo case and make sure that the loaded variants are not somatic
2. Remove the case and load it again using this branch. The variants loaded should be shown as somatic variants
**Review:**
> Fix demo case load config file to show available VCF fields and load only somatic SNVs and SVs

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_sma.html
- scout/server/blueprints/cases/templates/cases/individuals_table.html
This PR fixes.
Change the sex symbols into letters (F/M):
1. Run Scout locally (symbols-female-male) branch
2. Open a case
1. In the Individuals table: Sexs should be with letters (F,M)
2. Open SMN CN: Sexs should be with letters (F,M) in SMN Copy Number status - Individuals table
**Review:**
> Change Female/Male symbols to letters (F,M)

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/variant/templates/variant/tx_overview.html
- scout/server/blueprints/variant/templates/variant/utils.html
This PR adds:
- Sort icon to all tables with sortable fields
- A tooltip to all sort icons with a title
- Change the cursor to a pointer when hovering over the sortable fileds
1. On the branch sortable-filelds#1641
2. Open a case to test Gene panels 
3. Open variant page to test (RefSeq transcripts, Genes, Transcripts, Proteins)
**Review:**
> Added sort icon to all tables with sortable fields

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/clinvar.html
Fix #2520
Transcript list on ClinVar submission should show the same refseq transcripts that are shown in variant overview
**How to test: local instance of Scout**:
1. Marster branch, take this variant: http://localhost:5000/cust000/643594/0f630f3e151fa6a29513814688174a36
2. Pin the variant and go to the clinVar submission page: 
3. You'll notice that variant tx overview in variant page (count the number of distinct Refseq IDs, second column):
and variant ClinVar transcrips in the ClinVar form:
are different in number.
4. Switch to this branch and number of transcripts should be the same
**Review:**
> Expand list of refseq trancripts in ClinVar submission form to reflect those in variant tx overview

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/institute_sidebar.html
Fix #2708
Fix style and rename one sidebar element on Institute page. 
From this:
To this:
**Review:**
> Rename and fix style of `All SNVs and INDELs` institute sidebar element 

- CHANGELOG.md
- scout/server/templates/bootstrap4.html
This PR adds:
A loading spinner to all pages when the page is loading.
1. Install on clinical-db stage
2. Navigate from one page to another.
A loading spinner should appear until the page loads completely.
**Review:**
> Display a loading icon until the page loads completely

- scout/commands/load/case.py
- tests/commands/load/test_load_case_cmd.py
Print stack trace for even more command line errors. These changes are uniform with #2701.
_I'm having a hard time figuring out a good way to force a failure naturally, but got stuck. Any ideas?_
**Review:**
> Print Stacktrace for More Exceptions When Loading

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/views.py
- tests/server/blueprints/institutes/test_institute_api.py
- Creates an API endpoint to retrieve the list of available institutes for a logged user
- Moved some content of institutes flask endpoint from views to controllers 
1. Install locally 
2. Using the demo scout instance navigate to the list of institutes and make sure the page looks normal
3. While being logged in Scout, type in your browser the following url: `http://localhost:5000/api/v1/institutes`. It should return json data
4. Log out from Scout and run the same request. You should be redirected to the login page.
**Review:**
> Institutes api v1 endpoint

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/views.py
- scout/server/utils.py
- scout/utils/convert.py
- tests/server/blueprints/institutes/test_institute_api.py
- tests/server/blueprints/institutes/test_institute_controllers.py
- Created an API endpoint for institute cases
- Created a jsonconverter function in server utils to be used in all APIs whenever data objects are not json-serializable
1. On clinical-db, using the browser go to an institute page and make sure it contains the list of cases as usual  (for instance: https://scout-stage.scilifelab.se/cust002/cases)
2. go to the https://scout-stage.scilifelab.se/api/v1/institutes/cust002/cases and make sure it returns the same data, but in json format
**Review:**
> Institute cases api & server.utils.jsonconverter

- CHANGELOG.md
- scout/utils/ensembl_rest_clients.py
- tests/utils/test_ensembl_rest_clients.py
This bug showed up on Github, but seemed to work locally. Could not find the package that differed -which is my suspected root cause. Reference #2766.
Pytests on Github run by Coveralls would fail at `tests/utils/test_ensembl_rest_clients.py::test_test_query_biomart_38_xml`. All test should now pass.
a. Checkout and run `pytest tests/` on your local machine
b. Pytests on Github are started automagically 
All Pytests pass.
**Review:**
> Bugfix: XML Query Replies not Percent Encoded

- CHANGELOG.md
- docs/admin-guide/indexes.md
This PR  fixes a bug.
The documentation for indexes referred to a non-existing command.
```
% scout view indexes
2021-08-04 09:50:20 newmexico.local scout.commands.base[98102] INFO Running scout version 4.36
2021-08-04 09:50:20 newmexico.local scout.commands.base[98102] DEBUG Debug logging enabled.
Usage: scout view [OPTIONS] COMMAND [ARGS]...
Try 'scout view --help' for help.
Error: No such command 'indexes'.
```
This is now corrected:
```
% scout view index
2021-08-04 09:51:01 newmexico.local scout.commands.base[98122] INFO Running scout version 4.36
2021-08-04 09:51:01 newmexico.local scout.commands.base[98122] DEBUG Debug logging enabled.
2021-08-04 09:51:01 newmexico.local scout.commands.view.index[98122] INFO Running scout view index
collection	index
2021-08-04 09:51:01 …
```
> Fix Typo In Documentation

- CHANGELOG.md
- scout/server/blueprints/public/views.py
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/config.py
Fix a typo in SHOW_OBSERVED_VARIANT_ARCHIVE config param
1. Test locally in the 3 scenarios:
- No SHOW_OBSERVED_VARIANT_ARCHIVE param in config file
- SHOW_OBSERVED_VARIANT_ARCHIVE = True in config file 
- SHOW_OBSERVED_VARIANT_ARCHIVE = False in config file
1. Test on clinical-db stage and you should see archived observations.
2. Test locally and try the scenarios above
Archived observations panel should be shown when SHOW_OBSERVED_VARIANT_ARCHIVE is present and set to True
**Review:**
> Fix typo in SHOW_OBSERVED_VARIANT_ARCHIVE config param

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/phenotype.html
Fix #2789. Perhaps not the best fix ever, but it's an easy one.
The problem in flashing an error message is that the `case build `vs `gene build` is done in the adapter, here: https://github.com/Clinical-Genomics/scout/blob/1aefda23ee6c595c6047be140b8db407fd20527f/scout/adapter/mongo/case.py#L449
and from there it is a bit difficult to flash message to the web page..
**Review:**
> Explain that only genes with same case build can be added to dynamic HPO list

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variants/templates/variants/indicators.html
Fix #2794 and fix #2796
1. Check content of issues mentioned above
1. Check the behavior of [this variant](https://scout-stage.scilifelab.se/cust000/20190327_cancer/cancer/fa6eed9d98cb537ec1220df514c005eb?cancer=yes) in master branch and this branch.
**Review:**
> Fix previously tiered style in variantS and display again previously tiered and matching causatives in cancer variant

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/components.html
Fix #2797.
There is an extra ">" in the tooltip of the gene cell in cancer variantS page.
Before:
After:
**Review:**
> remove typo from tooltip title

- CHANGELOG.md
- scout/adapter/mongo/managed_variant.py
- scout/server/blueprints/managed_variants/controllers.py
- scout/server/blueprints/managed_variants/forms.py
- scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
Fix #2788
- Attempt at fixing the weird looking chromosome build on managed variants filter form 
- Added the code to be able to filter managed variants by chromosome coordinates
- Deactivate managed variants filter by chromosome build, since build can't be assigned when managed vars are created (yet)
1. Install on clinical-db stage and try to filter managed variants with different parameters
**Review:**
> Fix managed vars filters 

- CHANGELOG.md
- tests/server/blueprints/cases/test_cases_controllers.py
This PR adds a functionality, removes a deprecation warning:
```
tests/server/blueprints/cases/test_cases_controllers.py::test_phenotype_genes_matching_phenotypes
1079
/home/runner/work/scout/scout/tests/server/blueprints/cases/test_cases_controllers.py:80: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
```
Install
Deprecation warning for `/test_cases_controllers.py:80` is removed.
**Review:**
> Remove Deprecation Warning: mongo.insert -> insert_many

- CHANGELOG.md
- scout/commands/update/genes.py
Removed a line in update genes command that triggers also the update indices command
**Review:**
> Update genes command will not trigger an update of database indices any more

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/variant.html
Fix #2811 
1. Apply ACMG classifications many times to a RD variant and/or cancer variant. 
2. Make sure that all these classifications are shown in a field under the "Classify" button
**Review:**
> Restore ACMG classification history in a scrollable div

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/cases/templates/cases/individuals_table.html
- scout/server/blueprints/variants/static/form_scripts.js
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
Fix #2806
- Locally, on master branch case page, try to download the PDF delivery report or the PDF general report (RD case) or the Coverage & QC report (cancer case). After they are downloaded the loading spinner won't stop spinning on case page
- Switch to this branch and the loading spinner won't be triggered by the file download
**Review:**
> Avoid case reports triggering the loading spinner

- CHANGELOG.md
- docs/admin-guide/server.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/config.py
- scout/server/links.py
- tests/server/test_links.py
- tests/server/test_server_utils.py
This PR continues on the last PR #2815, renaming the SHOW_ALAMUT_CONFIG introduced there to HIDE_ALAMUT_CONFIG and moving it to links py instead of the jinja code.
**Review:**
> Rename hide alamut

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/variant/templates/variant/components.html
Partial fix to #2826, specifically addressing the first error: link to other causatives not working in variant page
1. Locally, on master branch, load the other demo case with the command `scout --demo load case scout/demo/643595.config.yaml`
2. Go to case 643595 and mark the POT1 variant as causative
3. Go to case 643594, POT1 variant, you'll see that it has an other causative matching variant, but the link doesn't work
4. Switch to this branch and check that the link works
**Review:**
> Fixes link to other causative variants on variant page

- CHANGELOG.md
- scout/server/blueprints/cases/static/case_images.js
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variants/controllers.py
- scout/server/links.py
Partial fix for #2826, issue n.3. COSMIC IDs are correctly saved to database for cancer variants but just one ID is used to create links to cosmic
1. Locally on master branch go to the first variant of demo cancer case, TP53 (you should load demo cancer case first)
2. Make sure that it contains only one link to COSMIC
3. Switch to this branch and you should be able to see 4 COSMIC links for 4 different cosmic IDs (hover on the buttons to see the actual id). These links should work.
**Review:**
> Allow multiple COSMIC links for a cancer variant

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/utils.html
This fixes that MitoMap and HmtVar links are being displayed when using hg38 genome build. The issue was accidentally introduced in v4.37.
> Fixed MitoMap and HmtVar links for hg38

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/variant.html
Partial fix to #2835 (point2) **--- NOTE THAT CURRENT CANCER VARIANTS ONLY HAVE clinsig, (#2836) --**
1. Install on stage or locally
2. Check that ClinVar classification is now well visible on the cancer variant summary
**Review:**
> Make ClinVar classification more evident in cancer variant page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/cases/templates/cases/individuals_table.html
Fix #2829. What I've done in this PR is basically replacing all the changes from #2810 (target="_blank") with "download". Looks like it's working on Chrome and Safari.
1. On a local instance of scout, use Safari as browser.
2. Go to demo case page and download the following files:
-  general report
- delivery report
- coverage qc report (is in the cancer case)
- HPO gene list (2 buttons)
- VCF2Cytosure
**Review:**
> Do not open new browser tabs when downloading files

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/variant.html
You were right @dnil, this is very similar to the another bug. They're both resulting from the splitting of the variant page into variant page and cancer variant page. I could have fixed it together with the other bug but when I created the branch I didn't know that it was kind of the same.
Fix #2848
1. On local demo igv track selection on variant page is broken.
2. On this branch the selection should be working
3. Check variant pages for all types of variants
**Review:**
> Reitroduce available igv tracks on variant page

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/buttons.html
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/variant.html
Fix #2847 
1. On a local master, note that splice junctions button is not visible on variant page
2. Switch to this branch and the button re-appears
**Review:**
> Reintroduce missing splice junctions button on variant page

- CHANGELOG.md
- scout/parse/variant/transcript.py
- tests/parse/test_parse_transcripts.py
Fix #2844 
COSMIC IDs for this variant are stored in a CSQ key named `COSMIC` (at the transcript level) and not together with the SNPs ID with the key `EXISTING_VARIATION`
1. Load on stage a case containing this structure of CSQ (the test case from the issue would be perfect)
2. Check that the variant from the issue has a COSMIC ID
**Review:**
> Collect COSMIC IDs from CSQ field named COSMIC

- CHANGELOG.md
- scout/commands/load/exons.py
Fix #2852. We don't want indexes being automatically updated after another cli command. We want to have control on when they should be updated.
**Review:**
> Stop updating database indexes after loading exons via command line

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #2854
1. On local demo case, MASTER BRANCH, pin a variant and then go to case page.
2. From case page, mark it as True positive or False positive.
3. Note that no validation badge shows on the side of the variant
4. Switch to this branch and the badge show show.
5. Reset variant validation status (by selecting "Not validated") and the badge should disappear
**Review:**
> Display validation status badge also for not Sanger-sequenced variants

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
Fix #2807.
- Moved  Frequencies, Severity and Local observations panels up in variant page
- Moved Frequencies and Local observations up in SV variant page 
1. Install the branch on stage and check the difference with master branch for SNV variant and SV variant pages (RD cases).
**Review:**
> Moved Frequencies, Severity and Local observations panels up in RD variant page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #2884 
Unifies the styles of pinned and causative variants on case page
1. Classify a variant with ACMG criteria (for example pathogenic)
2. Pin it
3. Mark it as causative
4. Go on variant page both on master branch and this branch and see the difference
**Review:**
> Unify style of pinned and causative variants' badges on case page

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/templates/utils.html
This removes the automatic insertion of a space after a punctuation mark in comments. (fix #2891)
1.  write the following comment "foo!doo?moo.crow,flow"
The displayed comment should be "foo!doo?moo.crow,flow"
**Review:**
> Removed padding after punctuation in comments

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
This PR mildly rearranges the variant(s) pages
**Review:**
> Adjust some margins, rearr gt and omim cards

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/utils.html
Fix #2951 
1. Find a case with a BND SV variant on clinical-db stage
2. Confirm bug described in #2951 
3. Install this branch
4. Make sure that bug is fixed
**Review:**
> Fix UCSC links coordinates for SV variants with start chrom != end chrom

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #2950 
1. Look for a BND variant in a case on clinical-db stage
2. Confirm bug described in #2950 
3. Install this branch and make sure that the variant naming is correct
**Review:**
> Fix human readable variants name in case page for SV variants with start chrom != end chrom

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
This PR adresses a layout issue with the variant page.
I have (re)added a couple of reactive steps, going from single to two- or three-column design. Severity predictions have been moved down on the page, reflecting their relatively smaller contribution to the total variant assessment, and placed closer to the conservation card.
**Review:**
> More reactive steps on variant page - fix #2934 tentatively.

- CHANGELOG.md
- scout/adapter/client.py
Give Scout more time to connect to the database, by increasing the serverSelectionTimeoutMS to 30K, default value according to the MongoDB documentation (https://docs.mongodb.com/manual/reference/connection-string/#server-selection-and-discovery-options)
1. Start a default instance of Scout and make sure it's populated with data and pages work as usual.
**Review:**
> Increase serverSelectionTimeoutMS MongoDB params to 30K

- CHANGELOG.md
- scout/adapter/mongo/panel.py
Fix #2982 
**How to test-->Locally**:
1. On master branch, create a new gene panel which contains only gene TP53. Name it for instance `TP53_panel`.
2. Edit the load config file for the demo cancer case by adding these 2 lines:
```
default_gene_panels: [TP53_panel]
gene_panels: [TP53_panel]
```
3. Load demo cancer case into scout demo with the command: `scout --demo load case scout/demo/cancer.load_config.yaml`
4. Go the the demo cancer case's variants page and check it works. 
5. From MongoDB compass, remove the new gene panel.
6. Reload the cancer variants page and the page will crash
7. Switch to this branch and the page should load instead.
**Review:**
> Fix to cancer variants page crashing when default gene panel was deleted

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
This PR fixes a typo tx_overview function (variant controllers) that is causing a bug in current master. Thanks @mhkc for notifying the problem!!! 
**Review:**
> Fix startswith typo in tx_overview function (variant controllers)

- CHANGELOG.md
- scout/server/blueprints/panels/controllers.py
- scout/server/blueprints/panels/views.py
Codefactor check is flagging the current  `panels` endpoint as too complex and this function can be easily simplified!
It's just a refactor PR, with no code added or removed.
1. Start a local instance of Scout and try to add and modify genes for a gene panel
**Review:**
> Reduce complexity of panels endpoint by moving some code to the panels controllers

- CHANGELOG.md
- requirements.txt
flask-ldap3-login was just released to fix [this dependency issue](https://github.com/nickw444/flask-ldap3-login/issues/75#issuecomment-970715102) caused by the upgrade of WTForm to v3.0. This is a better fix than what we have for [the issue in Scout](https://github.com/Clinical-Genomics/scout/issues/2961) I think!
1. Tested here: https://github.com/nickw444/flask-ldap3-login/issues/75#issuecomment-970385810
**Review:**
> Update requirements to use flask-ldap3-login>=0.9.17 instead of freezing WTForm

- CHANGELOG.md
- scout/server/blueprints/panels/controllers.py
- scout/server/blueprints/panels/views.py
Fix #2995 
1. Locally, from within the MongoDB compass, remove the 'maintainer' key from the demo panel. Try removing the panel
2. On clinical-db, try removing one of the old panels that has no 'maintainer' key
**Review:**
> Fix removing old gene panels with no 'maintainer' key

- CHANGELOG.md
- requirements.txt
Fix #3003
1. Create a new conda env and install both scout and the requirements-dev libs
2. Run `pytest -x`
**Review:**
> Freeze PyMongo lib to version<4.0 to keep supporting previous MongoDB versions

- CHANGELOG.md
- scout/adapter/mongo/hgnc.py
- scout/adapter/mongo/panel.py
- scout/build/panel.py
- scout/commands/update/genes.py
Fix #2823
1. Locally, download the necessary files to update the OMIM panel:
`scout download everything --api-key #########`
1. Update the local database by loading all genes (both 37 and 38):
`scout update genes -f .`
1. From master branch, time the creation of the OMIM panel using the following command:
`time scout --demo update omim --genemap2 genemap2.txt --mim2genes mim2genes.txt --institute cust000`
**Write down how much time it took**
1. From MongoDb compass, remove the newly created panel.
2. Switch to this branch and repeat step 3
The creating of the panel from this branch should be consistently faster.
**Review:**
> Speed up OMIM panel creation by collecting only gene info light

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/views.py
Fix #2997
The fate of Phenomizer is uncertain, and for the time being the server is down:
1. Locally, reproduce the bug by adding `PHENOMIZER_USERNAME` and `PHENOMIZER_PASSWORD` to the demo config file. You could assign these params any values since, but could also use [the Scout prod ones](https://github.com/Clinical-Genomics/servers/blob/650245a1b7d1b30da0d5da0de1c150216887960f/config/clinical-db.scilifelab.se/scout.conf.py#L24)
2. Start the app and go the demo case page
3. Click on the phenomizer button in the phenotypes panel:
4. The page should crash
5. Switch to this branch and it should display a red flash message with an error instead.
**Review:**
> Avoid case page crash on Phenomizer queries timeout

- CHANGELOG.md
- scout/adapter/mongo/index.py
- scout/commands/index_command.py
- tests/commands/test_index_cmd.py
Update/build indexes for specific collections, without doing it for all collections.
Example: scout (--demo) index --update -c gene -c transcript --update
Locally, we have a goof bug to test the PR with --> #3009
**Review:**
> Specify which collection(s) update/build indexes for

- CHANGELOG.md
- scout/commands/update/genes.py
Fix #3009 
1. Locally, with the demo instance.
2. Setup a demo database
3. Genes and txs collections should be indexes:
4. On main (😃) branch, update genes with the command` scout --demo update genes`
5. Bye indexes (except for _id).
6. Switch to this branch and setup a demo instance from scratch (`scout setup demo`)
7. repeat step 4. 
8. Indexes should not be deleted
**Review:**
> Do not drop genes and txs collections on genes update

- CHANGELOG.md
- scout/commands/update/hpo.py
Fix #3015 
1. Locally, set up a demo instance
2. Check that the hpo terms collection has several indexes
3. On main branch, run `scout --demo update hpo`
4. Make sure indexes are gone (except for _id)
5. Repeat from one from this branch
6. After updating the hpo terms, indexes should be retained
**Review:**
> Do not drop HPO terms collection when updating HPO terms via the cli

- CHANGELOG.md
- scout/commands/update/disease.py
There are no indexes for the the OMIM terms collection, so this is more to avoid a bug when we introduce indexes for it.
1. From this branch, run the command `scout --demo update diseases --api-key ############`
**Review:**
> Do not drop disease terms collection when updating diseases via cli

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/hgnc.py
- scout/commands/load/variants.py
- scout/commands/view/aliases.py
- scout/server/blueprints/variants/controllers.py
- tests/adapter/mongo/test_gene_handler.py
Fix #3024. This should fix the bug, but perhaps the functionality might be improved to return all variants that have TAP1 as gene symbol or TAP1 as an alias.
1. Load on scout stage and look for variants in TAP1 or TAP2 in case that contains these variants
**Review:**
> Fix variants searching by symbol and alias

- CHANGELOG.md
- scout/server/blueprints/genes/views.py
Fix #3028 
1. Locally, main branch, start the server with `scout --demo serve`
2. In another terminal window, run `curl localhost:5000//api/v1/gene`
3. You should get an error
4. Switch to this branch and repeat step 2
5. You get a formatted json error with a message
6. Check also that request with a gene param works as it should, run: `curl localhost:5000//api/v1/genes?query=pot1`
**Review:**
> Fixed genes API endpoint to return a json formatted error when request is malformed

- CHANGELOG.md
- scout/demo/643594.config.yaml
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
Fix #2990 
Display genes track beneath each splice junctions track in igv.js browser instead of just one at the bottom of the page.
1. Setup a demo database with the modified case config file
2. Go the whichever snv and check the RNA tracks
3. Each one should have a gene track beneath
**Review:**
> Display genes beneath each splice junction track

- CHANGELOG.md
- scout/server/blueprints/panels/controllers.py
- scout/server/blueprints/panels/templates/panels/panels.html
- tests/conftest.py
Fix #3043
1. Locally, launch a demo instance
2. From main branch, try to edit demo panel by uploading a file with genes, as shown in #3043. The page should crash
3. Switch to this branch and repeat. It should work now
**Review:**
> Fix editing gene panels and replace "csv" with "text" on gene panels page

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/config.py
- scout/server/extensions/loqus_extension.py
- tests/server/conftest.py
- tests/server/extensions/test_loqusdb_api_extension.py
- tests/server/extensions/test_loqusdb_exe_extension.py
fix #3048
Start Scout also if a loqusdb instance is not reachable. But show a warning on variants pages:
1. Install on clinical-db stage and make sure scout runs and shows the warning described above all all variants pages
**Review:**
> Decouple scout from broken loqusdbapi instances

- CHANGELOG.md
- scout/server/blueprints/panels/controllers.py
- scout/server/blueprints/panels/views.py
- tests/server/blueprints/panels/test_panels_views.py
This PR adds a functionality: gene panels JSON REST API. Will return all versions of a named panel, including update dates as key `dates`. This date can be compared to the date (and if desired version and later actual gene changes) on the monitored case `case.panels[i].updated_at` for matching `panel_name` in `case.panels[i].panel_name`. 
1. Attempt to retrieve a demo panel via the public API 
```
$ curl http://localhost:5000/api/v1/panels/panel1 
[{"_id": "5ef44f61d020103d9c9ad74e", "panel_name": "panel1", "institute": "cust000", "version": 1.0, "date": "2016-12-09T00:00:00", "maintainer": [], "display_name": "Test panel", "description": null, "genes": [{"hgnc_id": 7481, "symbol": "MT-TF"},
```
Take a screenshot …
> Gene panels api endpoint - fix #3001

- .github/workflows/tests_and_cov.yml
- CHANGELOG.md
CI testing now is a bit faster, but splitting tests by groups makes it so that there are some groups (for instance group 5) that contain slower tests than other groups. Randomizing group contents should re-distribute slower tests into all groups, making them a but more balanced. This way the entire process should be faster.
1. Check the automatic tests in the GitHub actions
**Review:**
> Speed-up CI tests further by randomizing test groups contents

- CHANGELOG.md
- scout/export/variant.py
- scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
- Fixes the export of validated variants with no "genes" document key (fix #3077) from the dashboard
- Better button style for the function
- Stops the loading page spinner after the validated variants are downloaded using the button above (fix #3079 )
**How to test, locally**:
Reproduce in master branch by:
- Editing a SNV of your choice from demo case by adding a coupe of new key/values (note that the second value is a boolean):
- Remove completely the key/value "genes" from the same variant.
- Go to the dashboard, "variant statistics" and click on  "download all verified variants for your cases"
- The page should crash
**Review:**
> Fix exporting from dashboard validated variants with missing "genes" key 

- CHANGELOG.md
- scout/utils/dict_utils.py
- tests/utils/test_dict_utils.py
This PR adds a functionality: add a file for dictionary utils. This functionality already exists in the code base. This is an effort to gather it in one place for reusability. Future pr:s can refactor and start using this utility file.
Pytests should pass
Usage example:
```
>>> import dict_utils
>>> a = {'asd': 12, 'a': 123, 'k': 33, '1': None, '2': []}
>>> dict_utils.remove_nonetype(a)
{'asd': 12, 'a': 123, 'k': 33, '2': []}
```
**Review:**
> Add Utils for Dictionaries

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/query.py
- scout/constants/case_tags.py
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/static/form_scripts.js
- Allow filtering institute cases using multiple HPO terms: fix #2690
- Fix searching gene variants specifying one or more HPO terms: fix #3073
**Preparing for test**:
1. Locally, load a second case in scout demo: `scout --demo load case scout/demo/643595.config.yaml`
2. Assign one or more HPO terms to this case, for instance: HP:0012444
3. Note that demo case 643594 has already assigned a couple of phenotypes
**Testing**:
1. On main branch, make sure that filtering cases by multiple HPO terms doesn't work in:
- Cases page (http://localhost:5000/cust000/cases)
- Dashboard (http://localhost:5000/dashboard)
- Gene variants (http://localhost:5000/cust000/gene_variants). In this page even searching with one term is broken
2. Switch to this branch and try the pages above by filtering with one …
> Filter institute cases using multiple HPO terms - Fixed gene variants search with HPO terms

- CHANGELOG.md
- scout/adapter/mongo/hgnc.py
- scout/server/blueprints/institutes/forms.py
- scout/server/blueprints/institutes/views.py
- scout/server/blueprints/variants/controllers.py
- tests/server/blueprints/institutes/test_institute_views.py
Fix #3030
This function was still used in 2 places:
- Variants filter, searching for variants matching a gene symbol list provided in an uploaded file. This functionality is broken at the moment
- Institute pages, gene variants search (Search SNVs and INDELs). In this case I'm proposing a change to the code that will **simplify** and speed-up the variants search
1. From master branch, create a simple txt file containing a list of gene symbols, some of which don't exist in the database: example:
POT1
ELN
HELLO
Provide this file for filtering variants in a demo instance and make sure that the functionality is not working as intended.
2. Switch to this branch and make sure that the filtering works
3. Go to institute page, gene variants functionality and search for the same …
> Remove hgnc_genes_find_one function, fix code that used it and bug in variants search form

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
ATM gene view:
Main branch:
This branch:
1. Locally, first search for MT variant and open it in the IGV browser.
2. Then go to another gene 
3. On clinical-db, open any variant from a case with cram files
**Review:**
> Increase the height of the genes track in the IGV viewer

- .github/workflows/vulture.yml
- CHANGELOG.md
- scout/models/variant/variant.py
I had it in mind since a while, and I finally tested running [Vulture](https://github.com/jendrikseipp/vulture) over our repo.
By setting the confidence value param to 80% (--min-confidence ) I've found a bunch of imports and variables that are not used.
This PR:
- Adds search for variables and imports that are not used, within the modified code of any PR.
- The new GitHub action checks if some code is unused with 80% confidence. The tests doesn't fail but the output might be useful to improve the code.
**Review:**
> Introduce Vuture GitHub action to identify unused code - Action Only -

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/views.py
1. search for some gene variants, and take note of or adapt HPO terms so that you have one owned by your home institute and one owned by another institute, but where your home institute is a collaborator.
2. limit to HPO terms, and note that you now only see variants where owner matches
3. apply patch, and note that also collaborators variants are again visible
**Review:**
> Collaborator hpo gene variants

- CHANGELOG.md
- scout/constants/variants_export.py
- scout/server/blueprints/variants/controllers.py
- tests/server/blueprints/variants/test_variants_controllers.py
The GERP conservation boolean we store for variant page display is not so informative. The user will at some point benefit more from actually using the likes of `bcftools` to query an annotated original VCF, so adding all possible annotations is hardly mandatory. Versioning of databases and tools becomes an issue with exported sheets.
1. pick a case, download variantS and note the indicated columns are present.
2. try both single and multiple sample cases as genotype is for each individual
**Review:**
> Add export fields

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/buttons.html
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
Fix #3105 
<details>
</details>
1. Install on cg-vm1 or locally and make sure these links are visible while …
> Reintroduce links to dbSNP, Beacon and SweGen in RD variant summary panel

- CHANGELOG.md
- scout/server/blueprints/variants/views.py
Fix #3109
<details>
</details>
1. Install master branch in cg-vm1 
1. As an admin, go to the dashboard and run …
> Export verified variants from all institutes when user is admin

- CHANGELOG.md
- Dockerfile
- Dockerfile-server
After unfreezing the cyvcf2 dependency the process of installing the dependency became much faster.
This means that we could modify the base images used in both Scout Dockerfile to be generical python images (with virtual env) instead of python+venv+cyvcf2 images
<details> …
> Change Dockerfile builder images to install latest cyvcf2 during Dockerfile build

- CHANGELOG.md
- scout/adapter/mongo/base.py
A minimal PR. This PR fixes a typo and ordering of instance variables of `adapter/mongo/base.py`
<details>
</details>
**How to …
> Fix Typos and Ordering in adapter/mongo.base.py

- CHANGELOG.md
- scout/server/blueprints/variants/static/form_scripts.js
Silence a couple of annoying Codefactor warnings introduced by last PR
<details>
</details>
1. Make sure that …
> Disable ESLint warnings for JS functions located on an external file

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/cases/views.py
Partial fix for #3125 
<details>
</details>
1. Add one of more phenotypes to a case
2. Create an HPO panel
3. …
> Export clinical and research HPO gene panels using PDFKit

- CHANGELOG.md
- scout/server/blueprints/panels/templates/panels/panel.html
- scout/server/blueprints/panels/views.py
This PR:
- Library switch (PDFKit instead of Weasyprint) for downloading gene panels reports (fix #3125 )
- Fixes the loading spinner that keeps spinning after loading a gene panel report
- Loading of gene panel reports is much faster now
<details> …
> Export of PDF gene panel report using PDFKit

- CHANGELOG.md
- README.md
- requirements.txt
Since we have switched to PDFKit, remove the WeasyPrint dependency
<details>
</details>
1. how to test it, …
> Remove WeasyPrint and Flask-WeasyPrint lib requirements

- CHANGELOG.md
- scout/server/blueprints/alignviewers/partial.py
- scout/server/blueprints/alignviewers/views.py
Tentative fix #3128, only the crash part.
I couldn't reproduce locally, so any idea is welcome! My idea is to pass an empty path to the function that servers the file, so it will return "file not found" instead. Basically it will except here: https://github.com/Clinical-Genomics/scout/blob/679bcd1098cdf95010a75b7c56cec9e458e97adc/scout/server/blueprints/alignviewers/partial.py#L54
<details> …
> Attempt at fixing file system not mounted IGV crash

- CHANGELOG.md
- scout/server/blueprints/cases/views.py
- scout/server/utils.py
Fix #3144 :
- Introduce default page margins on exported PDF reports
- Decrease fonts of gene names text in HPO genes reports
<details>
1. Make sure the branch is deployed: `systemctl --user status …
> PDF page margins and smaller HPO genes reports fonts

- .github/workflows/vulture.yml
- CHANGELOG.md
- scout/parse/models.py
Some model types in pydantic parsing are incorrect or could have better (or none) values
<details>
</details> …
> Fixed some Pydantic case parsing model types and default values

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/views.py
- scout/server/utils.py
- tests/server/blueprints/cases/test_cases_controllers.py
- Reintroduce coverage report in the PDF-exported case general report (fix #3142)
- Smaller content in PDF-exported general report
<details>
1. Make sure the branch is deployed: `systemctl --user status …
> Reintroduce coverage report in PDF general report of RD cases

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/cases/views.py
- tests/server/blueprints/cases/test_cases_templates.py
This PR adds a functionality or fixes a bug (fix #3130).
Test for existence of reports before adding link to action bar.
<details>
1. Make sure the branch is deployed: `systemctl --user status …
> Test for report existence - Fix #3130

- CHANGELOG.md
- scout/adapter/mongo/managed_variant.py
- scout/adapter/mongo/variant.py
- scout/server/blueprints/managed_variants/controllers.py
Fix #3160 
- Introduced ignore case in the search by description
<details>
</details>
1. Load 2 variants into …
> Fixed managed variants search by description

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/cases.html
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/clinvar.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
This PR adds a functionality or fixes a bug - see issue #3171. Some time ago we relabelled cancer variantS pages somatic variantS, but we never did that for the variant pages. This looks a little silly when navigating back and forth. Also institute was missing from the navigation bar on variant pages, perhaps to save space, perhaps due to omission. 
<details> …
> Unified somatic cancer variant navigaion labels

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/verification_controllers.py
- tests/server/blueprints/variant/test_variant_controllers.py
- Removes a param that is never used in a function
<details>
</details>
1. how to test it, possibly with real …
> Removed unused  add_compounds param from variant controllers function

- CHANGELOG.md
- scout/constants/igv_tracks.py
It seems the most common pipes use the legacy hg19_1kg_decoy, whereas we have a vanilla hg19 for IGV.js for build 37. This is mostly fine, but today we ran into a locus where it wasn't. Cram checksums did not check out for a small segment #3180. 
<details> …
> Fix #3180 - use 1kg_decoy as default hg19 IGV.js genome

- CHANGELOG.md
- scout/adapter/mongo/panel.py
- scout/server/blueprints/panels/views.py
I still don't understand how some user ended up with a malformed panel id as in #3185. My best intuition is could be related to a panel file upload during the server file storage downtime. The log entry points to a hospital NAT IP user POSTing a panel.
There seems to be little reason to crash if someone happens to malform the panel id, e.g. simplest case by editing the request URL in the browser. Here is a try-except version with a flash and redirect instead:
<details>
1. …
> Panel id except

- CHANGELOG.md
- scout/constants/__init__.py
- scout/constants/phenotype.py
- scout/parse/hpo_mappings.py
- scout/utils/scout_requests.py
Fix #3191 by replacing the link to the resource
<details>
</details>
1. Locally, run: scout --demo download …
> Fix missing HPO resource link

- CHANGELOG.md
- scout/server/blueprints/genes/views.py
Fix #3181 --> Genes (all present only in build 38) are uploaded but can't be searched in genes page
<details>
</details>
**How …
> Fix gene search form when gene exists only in build 38

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/models/variant/variant.py
- scout/parse/variant/variant.py
- scout/server/blueprints/variant/templates/variant/variant_details.html
- tests/parse/test_parse_variant.py
Fix #3197 
<details>
</details>
1. Load a newish case on stage
nr. of old obs and …
> Fixed parsing of old frequency obs

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
Fix #3208
The problem is that the js code to create chromograph images is called on case page onload even regardless of the case individuals having chromograph images or not
<details>
1. Make sure the …
> Fix broken javascript code when case Chromograph data is malformed

- CHANGELOG.md
- scout/server/links.py
Fix #3209.
ARX and HOXA13 get shallow links to the respective db loci lists, since the GnomAD and STRipy pages have their own nomenclature for those atm. I would not be surprised to see them make landing/joint pages for those in the future, esp if we find more such genes, but this will solve the issue for now.
<details> …
> Shallow link two STR loci

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/institutes/templates/overview/cases.html
- scout/server/blueprints/institutes/templates/overview/causatives.html
- scout/server/blueprints/institutes/templates/overview/clinvar_submissions.html
- scout/server/blueprints/institutes/templates/overview/filters.html
- scout/server/blueprints/institutes/templates/overview/gene_variants.html
- scout/server/blueprints/institutes/templates/overview/institute_settings.html
- scout/server/blueprints/institutes/templates/overview/phenomodel.html
- scout/server/blueprints/institutes/templates/overview/phenomodels.html
- scout/server/blueprints/institutes/templates/overview/users.html
Remove the extra subscript "cases" from the institute display name on the navbar from some of the pages to unify.
<details>
1. Make sure the branch is …
> Unify cases nav links - Fix #3211

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/links.py
Variant page gene deep link to PanelApp via gene symbol.
<details>
</details> …
> Fix #3223 - add PanelApp gene link

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/institutes/templates/overview/causatives.html
- scout/server/blueprints/institutes/views.py
- scout/server/blueprints/variant/templates/variant/components.html
When marking partial causative, variant can be seen on causatives view
and as a matching causative
also, on the variant level:
compared to main:
Especially the latter is a little worrying, but afaik at least cust002 rarely use partial.
<details>
1. Start …
> List partial causatives

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/constants/case_tags.py
- scout/server/blueprints/dashboard/controllers.py
- scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
- scout/server/blueprints/institutes/static/form_scripts.js
- scout/server/blueprints/institutes/templates/overview/cases.html
- tests/adapter/mongo/test_case_handling.py
Fix #3221
- Add filtering of cases by OMIM terms in both cases and dashboard pages
- Introduce placeholder, to give case query example in dashboard page 
<details>
1. Make sure the branch is deployed: …
> Filter cases by OMIM terms in cases and dashboard pages

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/variant/templates/variant/utils.html
- Fix Partial causative assignment in cases with no OMIM or HPO terms (fix #3226)
- Partial causative OMIM select options in variant page (the ugly visualization of OMIM options is due to the change of how diagnoses are saved in case document)
<details> …
> Fix mark partial causative

- CHANGELOG.md
- scout/adapter/mongo/variant.py
Fixes (partially) #2984 
<details>
</details>
**Expected …
> Decrease complexity of code in scout/adapter/mongo/variant to silence codefactor complaints

- CHANGELOG.md
- codecov.yaml
FIx #3244
- Make codecov test fail if coverage goes down by 0.3% (should we make it 0.5% instead?)
- Avoid those annoying comments saying coverage went down on many lines of code
<details>
1. Make sure …
> Created a codecov yaml file

- CHANGELOG.md
- requirements.txt
- scout/server/app.py
- scout/server/extensions/__init__.py
Fix #3271 
<details>
</details>
1. Deployment on cg-vm1 should work
The functionality …
> Remove flask-debugtoolbar that uses deprecated Jinja2 code

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/utils.html
Old cases contain a field `diagnosis_phenotypes` as a list of integers. That field has been recently modified and it is dictionary now.
This PR fixes a variant page crashing when case had old `diagnosis_phenotypes` format. Fix #3260
<details> …
> Fix variant page crashing when OMIM terms are list of integers

- CHANGELOG.md
- requirements.txt
Fix #3278. 
Freeze temporarily Werkzeug until [v.0.6 of flask_login](https://github.com/maxcountryman/flask-login/blob/264ae9707ef3597c9377016e1cd2bf3f1a3ccc39/CHANGES#L21) is out.
<details>
1. Make …
> Freeze temporarily Werkzeug to v.2.0 to fix deprecated safe_str_cmp import

- CHANGELOG.md
- scout/parse/matchmaker.py
- scout/server/blueprints/cases/templates/cases/case_report.html
Fix #3258 
Main branch, a pinned SV variant with many genes looks like this:
Same variant using this branch:
<details> …
> List gene names densely in general report for SVs that contain more than 3 genes

- CHANGELOG.md
- scout/constants/igv_tracks.py
Show transcript numbers on IGV.js refSeq gene track entries.
<details>
</details> …
> Switch refSeq transcripts

- CHANGELOG.md
- scout/constants/variant_tags.py
- scout/server/blueprints/cases/templates/cases/case_report.html
Tentative fix #3285 
<details>
</details>
**Expected …
> Fix  mismatch between SV n.genes in case report and SV variants page

- CHANGELOG.md
- requirements.txt
- scout/server/blueprints/alignviewers/views.py
- scout/server/blueprints/cases/views.py
- scout/server/blueprints/panels/views.py
- scout/server/blueprints/variants/views.py
Partially fixing all send_file deprecation warnings in #3294. 
In the end of March Flask 2.1 was released. When Flask 2.2 will be released all the warnings we have will become bugs!
<details>
1. Make …
> Fix send_file deprecation warnings that will turn into bugs with Flask 2.2 release

- CHANGELOG.md
- tests/utils/test_ensembl_rest_clients.py
Fixed last deprecation warning in the list in #3294 
Main branch:
This branch:
**Review:**
> Remove stream argument deprecation warning in tests

- CHANGELOG.md
- tests/commands/load/test_load_region_cmd.py
Partially fixes #3294 ---> tests/commands/load/test_load_region_cmd.py::test_load_region
/Users/chiararasi/Documents/work/GITs/scout/scout/adapter/mongo/variant_loader.py:408: UserWarning: no intervals found for b'scout/demo/643594.clinical.SV.vcf.gz' at 2:114647537-114720173
for nr_variants, variant in enumerate(variants):
Run: `pytest tests/commands/load/test_load_region_cmd.py`
On main branch:
On this branch:
**Review:**
> Handle `no intervals found` warning in load_region test

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/templates/overview/causatives.html
- scout/server/blueprints/institutes/views.py
- scout/server/blueprints/variant/utils.py
- Fix #3259  --> Display cDNA and prot changes in causatives table
- Moved causatives code from causatives views to a dedicated controller
Before:
After:
<details>
1. Make sure the branch is deployed: …
> cDNA and protein changes displayed in institute causatives table

- .github/workflows/vulture.yml
- CHANGELOG.md
- scout/server/app.py
- scout/server/config.py
- tests/server/conftest.py
Might be safer to log out a user after an amount of minutes of inactivity. **Users get logged out after a month (!) of inactivity at the moment**. That's because a month is the default value when you don't set any session value.
<details> …
> Configure an optional session timeout - now you get logged out after a month of inactivity!

- CHANGELOG.md
- scout/demo/999-99.test.cgh
- scout/demo/cancer.load_config.yaml
- scout/server/blueprints/cases/templates/cases/individuals_table.html
Fix #3121 --> Download VCF files from cancer case page
<details>
</details>
1. Locally, run `scout setup …
> Show and download .cgh files in cancer case page

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/blueprints/alignviewers/views.py
- tests/server/blueprints/alignviewers/test_alignviewers_views.py
Fix #3325 
**remote_cors** endpoint is only supposed to serve resources specified in config.py file, `CLOUD_IGV_TRACKS`. It can anyway used to return resources that are either on the same server as scout, or on other servers.
For instance, a file on the very scout server: https://scout-stage.scilifelab.se/remote/cors/https://scout-stage.scilifelab.se/public/static/logo-scilifelab.png
This PR checks makes sure that the endpoint returns only a resource saved in session["igv-tracks"]
<details>
1. `sudo -iu …
> Protect remote_cors from Server-Side Request Forgery

- CHANGELOG.md
- scout/server/blueprints/genes/controllers.py
Genes in build 37 and 38 can be updated separately, so instead of collecting a random gene to see when gene collection was updated, use date of last inserted gene.
<details>
1. Make sure the branch is …
> Gene collection update time corresponds to last gene creation date

- CHANGELOG.md
- docker-compose.yml
Demo cancer case is already loaded when setting up the Scout demo instance [now](#3296) but `docker-compose up` still contains the command to load it, so it has an error at the moment:
<details>
1. Make …
> Remove load demo cancer case in Docker Compose

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/static/bs4_styles.css
Fix #3166
<details>
</details>
1. On cg-vm1 (scout-stage) note that the PDF report of [this …
> Do not break text elements across pages when exporting reports to PDF

- CHANGELOG.md
- scout/server/blueprints/public/templates/public/index.html
Fix #3349 
1. Try login with an LDAP user
Password shouldn't be visible during typing
**Review:**
> Fix password visibility in LDAP login form

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/views.py
Fix #3362 
<details>
</details>
1.  Install on stage (cg-vm1) and try to create a PDF report for [this …
> Fix error in case PDF report when no pedigree can be created

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- tests/commands/export/test_export_cases_cmd.py
This is the action part. I had a brief look around, and do not see anything that should break from this. Compare #2644. We already have relaxed the condition on having a causative with partial causatives. This fills a niche for causation that we may yet not have a variant category for (UPD, SMN, RNA-expression, ...). Sometimes these go with a known other variant as well, sometimes not.
When we are at it, solve part of #2644; block the Archive button when there are Causatives.
<details>
1. `ssh …
> Fix #3360 - allow marking case solved

- CHANGELOG.md
- scout/commands/base.py
- scout/parse/case.py
> Deprecation warnings for soon to be gone features

- CHANGELOG.md
- scout/demo/cancer.load_config.yaml
- scout/server/blueprints/cases/templates/cases/individuals_table.html
Fix #3392 
From this:
To this:
<details> …
> Fix alignment of low tumor purity badge in cancer case page

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/indicators.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
A couple of hovers trigger statements had been missed on bootstrap5 upgrade or subsequent merges. Thanks @genecracker! 
<details> …
> Fix #3395 - reactivate hover on variantS comments popover

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/cases.html
Fix #3391 
Change from this:
To this:
<details> …
> Represent different tumor samples as vials in cases page

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/acmg.html
- scout/server/static/bs_styles.css
The classification summary was hidden by the sticky navbar. One could play with offsets and have the secondary-flow below the navbar, but I'm not sure it helps anyone much? Here is a suggestion to just keep it scrolling with the page.
<details>
- Run the command `paxa` and follow the instructions. Make sure to …
> Drop classification float

- CHANGELOG.md
- scout/server/blueprints/public/templates/public/index.html
- scout/server/static/bs_styles.css
Fix #3424 
From this:
To this:
<details> …
> Do not apply visited link style to any button

- CHANGELOG.md
- scout/constants/case_tags.py
- scout/demo/cancer.load_config.yaml
- scout/parse/models.py
> Add panel-umi tag option

- CHANGELOG.md
- scout/server/blueprints/dashboard/controllers.py
- scout/server/blueprints/institutes/controllers.py
> Remove leading and trailing spaces from cases search in cases and dashboard

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/causatives.html
> Fix #3442 - lighten gene symbols on causatives

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #3447 
Main branch (white on white):
This branch:
<details>
1. (optional) Find out …
> Fixed visibility of Sanger ordered badge in light mode

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #3459
From this:
To this: (tested locally with a connected beacon instance)
<details>
1. `ssh …
> Fix align of elems on the beacon submission modal

- CHANGELOG.md
- scout/server/blueprints/panels/controllers.py
Fix #3472
To reproduce the error:
- Go to gene panels
- Pick a panel
- Using a malformed gene panel file (**missing the first column**, hgnc id, for a gene for instance), click on 
- Then update it with corrupted panel:
<details>
- Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the …
> Fix error updating/replacing a gene panel from file with a corrupted/malformed gene panel file

- CHANGELOG.md
- scout/export/variant.py
> Fix validated variants export when gene has no transcripts

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
When trying to access the variant details page for a ranked cancer variant, a HTTP 500 was returned. From the stack trace it looked like it was isolated to the rendering of the rank score panel.
I was looking into making a test case for this, but gave up when it looked like I would have to set up a parallel test track with fixtures and all in order to get that working. I'd be happy to contribute to this, but before diving into that I'd like to see that my suggested changes make sense to start with.
<details>
<summary>Stack trace</summary>
```
2022-06-30 09:12:34 vs842 scout.server.blueprints.variant.views[14764] DEBUG Variants view requesting data for variant cfc2d0bd61fad4e05fc2d5e2590aecf3
2022-06-30 09:12:34 vs842 …
```
> Fix HTTP 500 for ranked cancer variants

- CHANGELOG.md
- scout/parse/variant/genotype.py
> Fix parsing of variant.FORMAT DR key in parse variant file

- CHANGELOG.md
- scout/server/blueprints/cases/views.py
- tests/server/blueprints/alignviewers/test_alignviewers_views.py
- tests/server/conftest.py
Fix #3510 and things broken by Flask updated to version 2.2 (https://flask.palletsprojects.com/en/2.2.x/changes/#version-2-2-0)
<details>
1. `ssh …
> Compatibility fixes for Flask 2.2

- CHANGELOG.md
- scout/server/app.py
Fix #3519 
For reference => https://flask.palletsprojects.com/en/2.2.x/config/?highlight=json_sort_keys#JSON_SORT_KEYS
<details>
1. …
> Fix deprecated JSON_SORT_KEYS param in app settings

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/phenotype.html
Fix #3529 
From this:
To this:
<details> …
> Assign phenotype less cramped on Case page

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/templates/overview/causatives.html
- scout/server/blueprints/institutes/templates/overview/utils.html
- scout/server/blueprints/institutes/views.py
- Fix #3528
- Fix links to variants in verified and causatives page to reflect the different types of vars
<details>
1. `sudo -iu …
> Causatives and validated using the same macro + fixed links to single variants

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/institutes/templates/overview/cases.html
Fix #3538.
Locally or on stage, compare the behavior when you try to filter cases by pinned genes.
<details>
1. `sudo -iu …
> Fix broken filter cases by pinned gene

- CHANGELOG.md
- scout/server/blueprints/panels/templates/panels/panels.html
Test in particular that there are no downstream ill effects of hyphens like dots - compare #2400.
<details>
1. `ssh …
> Fix #3548 - allow hyphens as well in panel id

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/links.py
- tests/server/test_links.py
> JAX CKB link in cancer variant page

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/server/blueprints/cases/templates/cases/utils.html
Hiding variant details a bit longer may or not be good, but linking to the wrong kind of page is just confusing - and e.g. a random STR match may not display well as it was. Reusing macros is nice.
<details>
- Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource …
> Matching SV links

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/dashboard/controllers.py
> Fix case search with string containing escapable chars

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
> Expandible region anno for variants with many genes

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/utils.html
> Fix #3568 - HPO SVs: fix one button, add another

- CHANGELOG.md
- scout/server/blueprints/panels/templates/panels/panel.html
From 
To
<details>
1. (optional) Find out …
> Fix #3579 - chanjo report labels

- CHANGELOG.md
- scout/server/blueprints/alignviewers/partial.py
This PR fixes a bug where Scout responded with duplicated response header when returning a BAM file causing a 502 error.
Response headers without the fix
```
Content-Type: text/html; charset=utf-8
Content-Length: 26
Content-type: application/octet-stream
Accept-Ranges: bytes
Content-Range: bytes 3285-3310/45531713695
Content-Length: 26
```
Response headers with fix
```
Content-type: application/octet-stream
Content-Length: 26
Accept-Ranges: bytes
Content-Range: bytes 3285-3310/45531713695
```
1. Print headers before and after alteration, (`print(resp.headers)`)
2. Ensure that IGV can display the alignment track
1. The Content-Type and Content-Length header should be overwritten and not appended
3. IGV can display alignment tracks again
**Review:**
> Set response headers instead of appending them

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
Fix #3581 
Added Coverage overview to HPO dynamic panel:
<details> …
> Add link to HPO panel coverage overview on Case page

- CHANGELOG.md
- scout/server/blueprints/alignviewers/partial.py
- scout/server/blueprints/variant/templates/variant/components.html
> Fix visited gene coverage button link style

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
> Round CADD and GnomAD values in variants export files

- CHANGELOG.md
- scout/server/blueprints/panels/templates/panels/panels.html
Fix #3593 
https://user-images.githubusercontent.com/28093618/191482322-e0aaf495-b91b-4f7c-8852-315b9cd4e253.mov
<details>
1. `sudo …
> Checkbox to show/hide removed gene panels from Panels page

- CHANGELOG.md
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
Fix #3595 
- Removes option for filtering cancer SVs by Tumor alt AF and Normal AF
- Modifies a tooltip already present to explain why tumor VAFs are missing
<details>
1. `ssh …
> Remove option for filtering cancer SVs by Tumor alt AF and Normal AF

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
This PR adds a functionality or fixes a bug: hides links to coverage reports if the scout case is configured for _cancer_.
<details> …
> Hide Links to Coverage If Cancer Track

- CHANGELOG.md
- scout/server/blueprints/managed_variants/controllers.py
This PR adds a functionality. Now Scout will not crash, but instead display an error message when trying to load a badly formatted tsv-file.
<details>
1. `ssh …
> Catch Crash For Badly Formatted TSV-Files

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/institutes/templates/overview/phenomodel.html
- tests/commands/load/test_load_research_cmd.py
- tests/commands/update/test_update_case_cmd.py
> Fix phenomodels typeahead

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/parse/variant/callers.py
Before: 
After:
<details>
1. (optional) …
> Fix #3620 - fix adding callers on load

- CHANGELOG.md
- scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
Fix partially #3619 
<details> …
> Fix missing preselected chromosome when editing a managed variant

- CHANGELOG.md
- scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
Fixes partially #3619
<details> …
> Prepopulate variant type and subtype when editing a managed var

- CHANGELOG.md
- scout/constants/igv_tracks.py
- scout/server/config.py
Fix #3561 --> Do not use our figshare dbVar track any more, but pull the same track from [trackhubregistry](https://trackhubregistry.org/)
<details>
1. `ssh …
> Updated clinical SVs igv.js track (dbVar) and added example of external track from trackhubregistry

- CHANGELOG.md
- docs/admin-guide/loading-variants.md
- docs/user-guide/variants.md
- scout/parse/variant/callers.py
- tests/parse/test_parse_callers.py
`svdb_origin` is now parsed in addition to `FOUND_IN` and `set`.
<details> …
> Fix #3629 - svdb_origin tags

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/clinvar.py
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/forms.py
- scout/server/blueprints/institutes/templates/overview/cases.html
- tests/adapter/mongo/test_clinvar_handler.py
Introduce a new checkbox on cases page to filter by cases with variants contained in ClinVar submissions (fix #849):
<details>
1. …
> Filter cases by submitted to ClinVar

- CHANGELOG.md
- scout/adapter/mongo/institute.py
- scout/server/blueprints/institutes/controllers.py
The issue here is that `getlist` will return the `[]` also if the control does not exist on the form, not `None`. Actually check if user is admin, else set it to `None`.
<details>
- Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server …
> Loqus priv

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/constants/case_tags.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/dashboard/controllers.py
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/templates/overview/cases.html
- Fix #3633 
- Fix #3605 
- Moved code to assign case status from sidebar to main case page:
<details>
1. …
> New 'ignored' case status and display number of cases by status in case page

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/forms.py
- scout/server/blueprints/institutes/templates/overview/cases.html
- tests/adapter/mongo/test_case_handling.py
Fix #3646 --> Filter cases for cases with RNA data
Adds a checkbox on cases filter to filter for cases using these conditions:
```
EXISTS_NOT_NULL = {"$exists": True, "$nin": [None, ""]}
query = {
"owner": owner,
"$or": [
{"gene_fusion_report": EXISTS_NOT_NULL},
{"individuals.splice_junctions_bed": EXISTS_NOT_NULL},
{"individuals.rna_coverage_bigwig": EXISTS_NOT_NULL},
],
}
```
These conditions might eventually be expanded when we add new RNA-seq data, for instance RNA multiqc etc
<details>
1. Fist book your testing time using the paxa software installed on …
> Search for RNA cases

- CHANGELOG.md
- README.md
There is a broken GitHub actions-associated badge on README page:
This PR fixes it.
<details> …
> Fix broken workflow badge on README page

- CHANGELOG.md
- scout/server/blueprints/clinvar/form.py
- scout/server/blueprints/clinvar/templates/multistep_add_variant.html
Dropdowns and plain text on the explicitly white background now hopefully visible everywhere, even in dark mode!
<details>
1. …
> Fix #3677. Dark mode for add ClinVar variant

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/panels/templates/panels/panel.html
- scout/server/blueprints/panels/templates/panels/panel_pdf_case_hits.html
> Fix #3679 - panel extent report truncated lines

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
Fix this badge on case page:
To be like this:
and this:
<details> …
> Make Safe variant matching badge more visible on case page

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/form.py
- scout/server/blueprints/clinvar/templates/multistep_add_variant.html
Fix #3699 
When condition ID changes in ClinVar form:
- Reset the list of conditions already provided
- Modify conditions placeholder to reflect the format of the condition ID
I'm not adding any validation that the provided values for the conditions are consistent with the condition ID type, just a simpler explanation of the expected values. On the other hand all the other values in this form are not validated either. **Validation of these values will be performed in the future by the ClinVar API**, which will return specific error messages when validation fails.
<details>
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scou …
> Reset and change placeholder for conditions in ClinVar when condition ID changes

- CHANGELOG.md
- tests/server/blueprints/api/test_api_views.py
There are 2 API endpoints that are [not well covered](https://app.codecov.io/gh/Clinical-Genomics/scout/blob/main/scout/server/blueprints/api/views.py) by tests. This PR adds simple tests for them
<details> …
> Tests for API endpoints

- CHANGELOG.md
- scout/server/links.py
I'm sure I made some kind of mistake in the reference files for Stranger, but let's fix the general issue in Scout and have it just show poorly for starters instead of crash.. 😊 
<details>
1. (optional) Find out …
> Fix STR source link generation

- CHANGELOG.md
- scout/adapter/mongo/variant_events.py
> Avoid duplicate causatives and pinned variants

- CHANGELOG.md
- scout/constants/clinvar.py
- scout/server/blueprints/clinvar/form.py
- scout/server/blueprints/clinvar/templates/multistep_add_variant.html
- scout/server/blueprints/clinvar/views.py
Fix #3715. Fixes also the order of the items in that select, which now is random.
<details> …
> Only ACMG terms in ClinVar clinsig when user selects ACMG 2015 as assertion criteria

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
- scout/constants/clinvar.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/clinvar_submissions.html
- scout/server/blueprints/clinvar/views.py
- scout/server/config.py
- scout/server/extensions/clinvar_extension.py
- tests/server/blueprints/clinvar/test_clinvar_views.py
Adds the functionality to send a json submission object to the ClinVar API (fix #2900):
If submission is successful the submission status is set to `submitted` (basically same as closed, but green):
<details> …
> ClinVar submissions via API

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/individuals_table.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/utils.py
Could be tested with latest GENS on stage. Or just check in output that `case_name` is added to the two places where we link out to GENS.
<details> …
> Fix #3705 - use GENS case_name option

- CHANGELOG.md
- scout/server/blueprints/clinvar/templates/multistep_add_variant.html
- scout/utils/scout_requests.py
- tests/utils/test_scout_requests.py
Fix #3724. The problem was that in the try - except block of scout_requests, the except block was raising an exception itself, causing the app to crash.
<details>
1. Stop the …
> Handle connection timeout when sending requests to external web services

- CHANGELOG.md
- scout/server/blueprints/clinvar/templates/clinvar_submissions.html
Fix #3729 
- Added the option to validate any type of submission:
Main branch:
This branch:
<details> …
> Validate all submissions regardless of their status

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/phenotype.html
This PR adds fixes a bug.
<details> …
> Fix #3733 - stop spinner on json export

- CHANGELOG.md
- scout/server/blueprints/cases/static/case_images.js
This PR adds changes chromograph display to only restrict view of sex chromosomes to X only for designated females. All other (male, other and unknown) show coverage for both.
<details> …
> Show chrY also for sex unknown - Fix #3750

- CHANGELOG.md
- requirements.txt
- scout/server/blueprints/variant/templates/variant/buttons.html
- scout/server/blueprints/variant/templates/variant/components.html
The REViwer button now targets a new blank window, and it is also shown on the str variant page.
Working on stage as well.
<details>
1. Stop the …
> Fix #3755 - REViewer button on variant page

- CHANGELOG.md
- scout/commands/load/case.py
- scout/load/all.py
> Deprecate load_scout - fix #2204.

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/views.py
> Fix #3766 - add other matching variants for SVs

- CHANGELOG.md
- scout/adapter/mongo/acmg.py
- scout/models/variant/variant.py
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/views.py
- tests/server/blueprints/variant/test_variant_controllers.py
- tests/server/blueprints/variants/test_variants_views.py
> Deleting last ACMG turns off variant evaluation

- CHANGELOG.md
- scout/adapter/mongo/variant_events.py
- scout/constants/variant_tags.py
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/indicators.html
- scout/server/blueprints/variants/templates/variants/utils.html
- tests/adapter/mongo/test_variant_events.py
Fix #2414. 
Adds options for risk factors in line with ACMG recommendations to keep this outside the classification, and consider separating into different categories for the strength of evidence for the risk increase (RF, likely RF and uncertain RF).
These are shown as usual manual ranks, e.g.:
In order to make them more useful, this PR allows to show them on matching variants from other cases, on the variantS list:
And then with details on the variant page:
All pretty much as for the matching tiered variants from the cancer side.
<details>
1. Make sure the PR is pushed and available on [Docker …
> Manual rank updates: add risk factor, show on matching variants in other cases

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/institutes/controllers.py
- tests/server/blueprints/variant/test_variant_controllers.py
Fix #3771  - Show only causative and not matching causatives
<details>
1. Start the …
> Fix causatives page

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
> Somatic matching classified

- CHANGELOG.md
- scout/server/links.py
This PR adds a functionality or fixes a bug (well, or a changed API on another resource, but to the effect of the usability it becomes bugged as the recipient API is not versioned, at least not when making get requests).
<details> …
> Fix #3808 - VarSome link to hg19

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
This PR changes a functionality. Blank window open on matching cases.
<details>
1. …
> Open matching cases in new windows - Fix #3810

- CHANGELOG.md
- scout/server/blueprints/variants/views.py
Fix #3818 
The specific problem is that from research variantS page, after filtering with the variantS filter, the type of variant (clinical, research) is not collected correctly and defaults to clinical. This way the variant numbers are taken from the wrong category.
<details> …
> Fix research vars counter

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/cases.html
Show all case categories, to make sure the case counters are displayed, and mildly edit the "No cases found" statements to hopefully nudge the user to search for actually desired categories.
<details>
1. (optional) …
> Fix #3823 - always show case categories

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/clinvar_submissions.html
- New breadcrumb option to mark an open or closed submission as submitted
- Improved sorting of ClinVar submissions  and layout (accordion)
<details> …
> Fix ClinVar sorting and update submitted status

- CHANGELOG.md
- scout/constants/clinvar.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/multistep_add_variant.html
Fix #3829 
- Fixed visibility of SV type in ClinVar submission form
- Try to pre-populate the SV type select given the SV subtype
<details> …
> Clinvar sv fixes

- .github/workflows/build_and_publish.yml
- .github/workflows/keep_a_changelog.yml
- .github/workflows/linting_and_fixing.yml
- .github/workflows/linting_only.yml
- .github/workflows/server_stage_docker_push.yml
- .github/workflows/tests_and_cov.yml
- .github/workflows/vulture.yml
- .github/workflows/woke.yml
- CHANGELOG.md
- Updated version of several GitHub actions used in workflows
- Updated deprecated version of Ubuntu in GitHub action
<details> …
> Updated actions and Ubuntu versions in GitHub actions

- CHANGELOG.md
- scout/models/variant/variant.py
- scout/server/blueprints/panels/templates/panels/panels.html
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/utils.py
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/utils.py
- scout/server/blueprints/variants/views.py
- Fix #3794: browser support for visibility:collapse is rather sketchy, with a lot of them only accepting certain elements, and essentially just doing visibility:hidden instead, giving the empty-line phenomenon in the panelS list. Use bootstrap collapse instead.
Instead of blank lines for the hidden ones.
- Fix #3793: this was a bit more complicated than anticipated, since several aspects of the panel view on e.g. the variantS page relies on the case version of the panel, which will not have been updated with recent panel hiding/removal since the time of case creation. Add updates.
Looks like before with the case panel active: 
Then if we remove the panel, count drops and the removed panel is not shown.
Also, from the same issue, on the variant …
> Hide panels improvements

- CHANGELOG.md
- tests/server/blueprints/panels/test_panels_views.py
> Fixed gene panel test pointing to the right function

- CHANGELOG.md
- scout/build/panel.py
- scout/demo/643594.config.yaml
- scout/models/panel.py
- scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
- scout/server/blueprints/variant/utils.py
This shows comments from panel genes on the variant page:
Edited here:
This solves the issue in a traditional Scout fashion. I can't help feel that much as with gene panel gene content, this as well as the other panel gene things, like disease transcript, would benefit from refresh from current panels when visiting an older case. Different PR.
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call …
> Fix #3776: show panel gene comments on variant page

- CHANGELOG.md
- scout/adapter/mongo/event.py
Fix #3899 . The problem happens when a user has two tabs open on the same case/variant. If they remove the comment in a tab and then they try to edit the comment in the other tab, then the page crashes.
<details> …
> Fix editing non-existing comments

- CHANGELOG.md
- scout/server/extensions/phenopacket_extension.py
> Fix #3893 - missing phenopacket

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #3953
Without causatives or pinned:
With Causatives and pinned:
<details>
1. Start …
> Fix ugly causatives panel on Case page

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
Fix #3949. Track color now as per the bigbed by default, thanks to the IGV.js team!
<details> …
> Use IGV.js 2.15.8 - fix default ClinVar track color

- .github/workflows/build_and_publish.yml
- CHANGELOG.md
Update a couple of actions to use fixed release versions instead of deprecated "master" branches (compare  https://github.com/pypa/gh-action-pypi-publish).
<details> …
> Fix pypi action

- CHANGELOG.md
- scout/constants/igv_tracks.py
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
Fixes locus search by giving genome id to the IGV reference track. The added benefit is a display of the id on the browser, making it easier for the user to keep track with several windows and genomes open.
<details> …
> Fix #3970 - IGV locus search fix by giving reference id

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/commands/delete/delete_command.py
- scout/server/blueprints/cases/templates/cases/utils.html
Click here:
Before:
After:
Also fixed a couple of minor missing MEI variant types (variant deletion +`keep` option, region load). Region load in particular has basically no effect right now as we dont rank MEI yet. 
<details>
1. `ssh …
> Fix prettylink MEI - fix #3974

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/views.py
- tests/server/blueprints/cases/test_cases_templates.py
As @dnil got to see last week, our Scout instance did not show the assigned user correctly in the case view. This is what we had:
After digging around, it seemed to be due to the user ID not being the same as the user email. We are using LDAP for login, and would like to keep the ID separate from the email. This PR addresses this issue by making sure that the user ID is used when assigning a user to a case, and that the assigned users are fetched properly when the case is processed for viewing.
I noticed more places where emails are used like user IDs, but decided to only modify the bare minimum to solve this particular problem. Hopefully this doesn't introduce any issues elsewhere. Looking forward to your feedback!
**Review:**
> Fix assigned name when id is different from email

- CHANGELOG.md
- requirements.txt
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
Fix #4013 - build now called hg38 instead of GRCh38 at IGV. 🙄
<details> …
> Change id of reference to match IGV locus search. Fix #4013.

- CHANGELOG.md
- docs/admin-guide/containers/container-deploy.md
Out docs state that to run a dockerized version of scout on Mac you should use the following command:
`docker run --rm --expose 5000 -p 5000:5000 clinicalgenomics/scout scout --host docker.for.mac.localhost -db scout-demo  serve --host 0.0.0.0`
But the image is compiled under linux and using a recent version of Docker the command fails with the error:
```
WARNING: image with reference clinicalgenomics/scout was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
docker: Error response from daemon: image with reference clinicalgenomics/scout was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
```
This is a simple fix to the docs so it's running again on Mac (arm) computers:
<details>
<summary>Testing on cg-vm1 …
> Fix admin docs to run docker scout on Mac - Arm processor

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/models/variant/variant.py
- scout/parse/variant/frequency.py
- scout/parse/variant/variant.py
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/blueprints/variant/utils.py
- tests/parse/test_frequency.py
This PR adds a functionality: archive loqus frequencies for Balsamic, plus reintroduction of Swegen frequencies since Balsamic has them. Balsamic cases will be annotated with three different loqus archives:
- RD (germline) - essentially same as RD, with slightly different key names
- Cancer Germline - loqus archive for Balsamic calls for normal samples
- Cancer Somatic - loqus archive for Balsamic calls for somatic samples
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). …
> Balsamic frequencies

- CHANGELOG.md
- scout/server/blueprints/variants/views.py
Before:
After:
<details>
1. Start the …
> Fix #2786 - constrain variant_type on variantS view requests

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/links.py
Adds a link that in particular @47KW wanted. Aside from colouring the values, I think it will be useful for 1) compute on slightly larger indels 2) includes pangolin scores.
Links from here:
to here:
<details>
1. …
> Fix #4058 - add SpliceAI link

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/cases.html
This PR is pure QoL.
Adjust column widths on caseS page. Especially OMIM-AUTO and PANELAPP-GREEN are relatively panel long names, causing the default panel column to wrap rather frequently.
<details> …
> Fix column width - fix #4071

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #4104
Same case as in issue, after the fix:
<details> …
> Escape protein names in case general report

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
Another fix to a bug previously created by me 😆 
Fix potential bug when loading a case general report with a variant that has no protein_sequence_name
<details>
1. Stop the …
> Fix potential missing protein name bug

- CHANGELOG.md
- requirements.txt
- scout/adapter/mongo/base.py
- scout/adapter/mongo/variant_loader.py
https://github.com/Clinical-Genomics/scout/issues/4076
<details> …
> unfreeze PyMongo

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
The images loaded with scout <= 4.71 don't show up. For example on this case -> https://scout-stage.scilifelab.se/cust000/F0006358-mip7
- Check also this test on latest version:  https://github.com/Clinical-Genomics/scout/pull/4125#issuecomment-1768401950
<details>
1. `ssh …
> Fix displaying custom case images loaded with scout version <= 4.71

- CHANGELOG.md
- scout/server/app.py
- tests/server/test_app.py
> Fix jinja2 filter rendering long integers

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- Fix the fact that caseS and case page  aresucking up all memory
- Partially reverting #4100
<details> …
> Tentaive fix to server hanging

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/mei-variants.html
- scout/server/blueprints/variants/templates/variants/str-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- tests/server/test_app.py
The spacing delimiter is now slightly thinner, and all `human_longint`s are wrapped in a non-ws-wrapping style `<span>`.
I guess due to the safe filter, needed for html rendering of the thin space, it is recognised as a long number at least on my OS, and browser reaction is much like to a phone number. Copying is also kind of ok, though it will include spaces so still break some connectivity - but we ideally also don't want users to copy-paste, right. 😬 
<details>
1. Fist book your testing time using the Pax …
> Fix #4152 - dont split large numbers, use thin space

- CHANGELOG.md
- scout/adapter/mongo/omim.py
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/variant/utils.py
- Speed up variant page by collecting only inheritance key/values from disease terms
<details> …
> Speed up variant page by projecting inheritance in disease terms query

- CHANGELOG.md
- scout/server/links.py
GnomAD links broken for build 37.
leding to the now default nomad grch38:
✅ with patch
goes back to trusty bad old grch37.
<details>
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman …
> Fix #4190 - GnomAD web service defaults to hg38

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
Fix #4176 
- Removed cytoband
- Added link to literature
- Added ref repats count
- Added a color to better classify STR (full mutation, pre-mutation, normal)
<details>
1. …
> Clearer STRs on case general report

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/utils.html
…s and updated changelog
This PR adds red colour to verified badge when false positive, for true positives the badge remains green
<details> …
> Verified badge is red if false positive

- CHANGELOG.md
- scout/models/case/case_loading_models.py
- tests/parse/test_parse_case.py
Fix #4197 
1. Locally. branch main, remove `family_name` from demo config file. Run `scout setup demo`
2. Switch to this branch and try again `scout setup demo`
1. Main branch should not load the case and display validation error
3. This branch should load the case with a display name equal to case id (internal_id)
**Review:**
> Fix missing family name parsing

- CHANGELOG.md
- scout/server/blueprints/clinvar/templates/clinvar/clinvar_howto.html
This PR prevents the img in ClinVar hoot-modal to overflow in smaller screens. 
fixes  #4199
<details> …
> Added responsiveness to ClinVar howto image

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/utils.html
Fix #4205 
Specifically:
-  "x" button to remove a case from a group sometimes is not visible, based on the clicked status:
- Fix remove the case from a group whenever it has been already removed in another browser tab (fix #4205 )
<details> …
> Fix remove case from group if case has been already removed in another tab

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/links.py
Partially fixing #4210 - just the Decipher link for now
<details> …
> Added Decipher button to SNV/MEI and str variant page

- CHANGELOG.md
- tests/conftest.py
- tests/server/blueprints/cases/test_cases_views.py
- Adds fixtures for RNA fusion case
- Adds a test for fusion case page
<details>
1. …
> Add test and fixtures for RNA fusion case page

- CHANGELOG.md
- scout/commands/update/case.py
- tests/commands/update/test_update_case_cmd.py
Update case with path to mei and research mei variants
Fix #4229 
<details>
1. Start …
> Update case document with path to mei variants

- CHANGELOG.md
- scout/adapter/mongo/filter.py
- scout/constants/__init__.py
- scout/constants/variant_tags.py
- scout/server/app.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variants/controllers.py
- tests/server/test_app.py
Attempt at adding info on variants category and type for audited filters on case report (fix #4219):
<details> …
> Audit filters specifics on case report

- CHANGELOG.md
- scout/adapter/mongo/variant_loader.py
- scout/build/variant/genotype.py
- scout/server/blueprints/variants/controllers.py
The issue with a compound variant in multiple genes was that when aggregating the region and function annotations, we add a gene name with a colon to them, so they do not directly work in the comparison. The set disjunct is not totally perfect, but now at least does what it was intended to do: variants will not be dismissed if any of the genes have a functional annotation or region annotation that match the filter.
See issue as well, but in debug terms, before:
And after:
✅ The filter does not dismiss the compound:
<details>
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-se …
> Compound follow multi gene

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/static/bs_styles.css
When you open pages like the cases of an institute or the variantS from a case, you no longer see which ones were visited because the visited link color looks like the un-visited link.
This was caused by #4236, which was an attempt to fix an error introduced by #4217.
In this PR I am:
- Reverting global css styles as they were before #4217 (fix #4245)
- Fixing the style of the visited external links buttons on variant page instead
<details> …
> Revert global styles and fix variant buttons style instead

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/parse/variant/variant.py
- scout/server/blueprints/variants/templates/variants/fusion-variants.html
- Closes #4271
- Do not save fusion variants-specific key/values in other types of variants
<details> …
> Parse and show RNA fusion found_db key/values

- CHANGELOG.md
- scout/parse/variant/variant.py
- Converts RNA fusions variants `tool_hits, fusion_score` keys from string to numbers - Fix #4281 - 
<details>
1. Stop the …
> Fix type of some RNA fusion variant keys

- CHANGELOG.md
- scout/parse/variant/variant.py
- scout/server/links.py
- scout/utils/convert.py
- Fixes #4288 
- Renamed the `get_mei_info` to `set_mei_info` function to be consistent with the other functions
<details>
1. …
> Fix removing of None key/values before saving parsed variants

- CHANGELOG.md
- requirements.txt
See https://github.com/Clinical-Genomics/scout/issues/2252 for some background.
Looks all good after upgrading to 15.0.1:
```
(scout39n) ➜  scout git:(main) ✗ pip install -U -r requirements.txt
...
Requirement already satisfied: coloredlogs in /usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (14.0)
Collecting coloredlogs
Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
...
(scout39n) ➜  scout git:(main) ✗ pytest tests/commands/download/test_download_ensembl_cmd.py
=============================================================================================================== test session starts ========================================================================================== …
```
> Unfreeze coloredlogs

- CHANGELOG.md
- scout/server/blueprints/phenomodels/templates/phenomodels.html
- Fix #4304 
Main branch:
This branch:
<details> …
> Fix missing phenomodels icon

- CHANGELOG.md
- docker-compose.yml
This PR adds a functionality or fixes a bug
If you try to run the dockerized version of scout as described in the instructions on an ARM processor you get the following error:
```
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/jose/rfc7517/__init__.py", line 10, in <module>
scout-cli          |     from ._cryptography_key import load_pem_key
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/jose/rfc7517/_cryptography_key.py", line 1, in <module>
scout-cli          |     from cryptography.x509 import load_pem_x509_certificate
scout-cli          |   File "/venv/lib/python3.8/site-packages/cryptography/x509/__init__.py", line 7, in <module>
scout-cli          |     from cryptography.x509 import certificate_transparency
scout-cli          |   File …
```
> Fixed missing cryptography lib error with Docker on ARM processor

- CHANGELOG.md
- requirements.txt
- scout/models/case/case_loading_models.py
- Closes #4135. After a recent fix we are no longer storing images in the database, so the error occurring in the issue is no longer happening, but this PR introduces an additional check that the custom images provided in the config file have valid paths.
<details>
1. `ssh …
> Validate custom image paths when a case is loaded

- CHANGELOG.md
- requirements.txt
- scout/server/app.py
- scout/server/blueprints/institutes/templates/overview/utils.html
- Add REVEL score, REVEL rank and SpliceAI scores to Causatives and Validated variants page (fix #4311)
- Round the CADD score to the second decimal number (fix #4314 ) on the same pages
<details> …
> Add REVEL, REVEL rank and SpliceAI scores to causatives and validated pages

- CHANGELOG.md
- scout/adapter/mongo/panel.py
- scout/server/blueprints/institutes/controllers.py
> Fix #4322 - ClinVar submitters cleared with unpriv saving

- CHANGELOG.md
- scout/server/blueprints/institutes/forms.py
- Fix #4335 and #4325
<details>
1. Start …
> Fix None search as default case search in cases form

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
> Fix removing the same ClinVar variant from 2 different tabs

- CHANGELOG.md
- scout/server/blueprints/institutes/templates/overview/utils.html
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/fusion-variants.html
- Fix #4313
Causatives page on main branch:
<hr>
Causatives pages on this branch:
<details> …
> Fix missing genes, links and functional anno for fusion variants in causatives and verified pages

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/blueprints/variant/views.py
- tests/server/blueprints/variant/test_variant_controllers.py
- The case_obj parameter is never used in the observations function, so this PR is removing it from there and whererever the function is invoked from
<details> …
> Remove unused parameter in server/blueprints/variant/controllers/observations

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/components.html
- Partially fixing #4342 - second checkbox
Main branch:
<hr>
This branch:
<details> …
> Fix archived local obs not visible on cancer variantS page

- CHANGELOG.md
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
- scout/server/blueprints/clinvar/views.py
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- Allow users to submit using a custom ClinVar API ID if no key is saved for their institute (closes #4324)
- Allow to reset ClinVar submission ID to None (closes #4350)
<details> …
> Allow ClinVar submissions with custom API keys and allow resetting submission ID

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
- scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
- scout/server/blueprints/clinvar/views.py
- Partially fixing  #4326 
<details>
1. …
> Show user that created a ClinVar submission, when available

- CHANGELOG.md
- scout/parse/orpha.py
- tests/parse/conftest.py
- tests/parse/test_parse_disease_terms.py
- tests/parse/test_parse_orpha.py
When adding disease_terms to the database terms extracted from orphadata files had the hgnc-id of linked genes saved as a string. Disease_terms extracted from omim files had the hgnc-id saved as a number. 
This PR converts the hgnc-id extracted from orphadata files to a number before saving it to a disease object
<details>
1. …
> Genes for orpha disease_terms are now saved as int, matching the format for omim disease_terms

- CHANGELOG.md
- requirements.txt
- scout/utils/ensembl_biomart_clients.py
- tests/commands/download/test_download_ensembl_cmd.py
- tests/utils/test_ensembl_biomart_cients.py
- Fix #4403 - Do not install schug which has a lib conflict with chanjo-report
<details> …
> Replace schug dependency with requests to schug web

- CHANGELOG.md
- scout/adapter/mongo/variant.py
> Fix show matching partial causatives on variant page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
> Fix #4418 - report division-by-zero on depth 0

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
Adds MEI subtype / element annotation to variant page. Looks like we already represent the other things we parse to some degree (frequency, GT/depth/clipping), and there is not much more in the file yet. I think we are good until @kristinebilgrav has more news for us, on e.g. https://github.com/kristinebilgrav/TELLR.
Display 
without breaking e.g. SNVs
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to …
> Fix #4435 - add MEI element name to variant page

- CHANGELOG.md
- scout/server/links.py
- Fix #4447 - update base decipher url
Looks good on demo at least, and with manual tests for 38.. 😊 
With the old Sanger URL, we end up on their landing page today:
<details> …
> Update Decipher base urls

- CHANGELOG.md
- scout/commands/base.py
- tests/commands/test_base_command.py
This
instead of 
.
Perhaps clearer if we pick a command that does no INFO logging:
Before:
After:
<details> …
> Fix #4396 - reset default loglevel to INFO

- CHANGELOG.md
- scout/build/genes/transcript.py
- scout/models/hgnc_map.py
- scout/parse/ensembl.py
- scout/parse/hgnc.py
- tests/conftest.py
- tests/parse/test_parse_ensembl_transcripts.py
- This will make the MANE info available for old variants more up-to-date, since it's collected from latest gene/transcripts records in the database
- Would also help to achieve #4431
- We could use this info instead of relying on VEP annotations when parsing variants
<details>
1. `ssh …
> Parse and save MANE transcripts info when updating genes in build 38

- CHANGELOG.md
- scout/server/blueprints/genes/templates/genes/gene.html
- On gene page, display MANE badges, if available
Example with PRDM16 gene:
Example with ERCC& gene:
<details>
1. Stop the …
> Display MANE badges on gene pages

- CHANGELOG.md
- scout/server/blueprints/api/views.py
- tests/server/blueprints/api/test_api_views.py
> Fix #4157 - add pin API endpoint

- CHANGELOG.md
- scout/adapter/mongo/disease_terms.py
- scout/server/blueprints/diagnoses/controllers.py
- scout/server/blueprints/diagnoses/static/diagnoses.js
- scout/server/blueprints/diagnoses/templates/diagnoses/diagnoses.html
- scout/server/blueprints/diagnoses/views.py
This PR adds the option of searching the disease_terms in the database instead of loading all diseases. 
This is a fix for #4427
<details> …
> Add option to search disease_terms in database to diagnosis page

- CHANGELOG.md
- scout/adapter/mongo/case_events.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/phenotype.html
- scout/server/blueprints/cases/views.py
- scout/server/blueprints/phenomodels/templates/phenomodel.html
- tests/server/blueprints/cases/test_cases_views.py
This PR replaces several instances in the case page where "omim" was used in ids, function names and variable names which also handles orpha terms. This is a fix for #4428.
<details> …
> Replace "omim" with "disease" in case page query search and related functions

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/variants/views.py
- Closes #4473 
Main branch:
This branch:
<details> …
> Add button for displaying STR variants occurring in the dynamic HPO panel on case page

- CHANGELOG.md
- scout/server/blueprints/cases/views.py
- tests/server/blueprints/cases/test_cases_views.py
Adds a route to the case view for unique `case_id`. Intended for use with Gens specifically.
<details> …
> Reroute case no institute

- CHANGELOG.md
- scout/adapter/mongo/event.py
- scout/server/blueprints/cases/controllers.py
ACMG VUS have `acmg_classification == 0`. We are careful to use `"$exist"` when querying db, but this apparently slipped in checking on the variant - maybe in a refactor.. 
<details> …
> Fix #4480 - show ACMG VUS on general report

- CHANGELOG.md
- scout/server/blueprints/phenomodels/controllers.py
- scout/server/blueprints/phenomodels/templates/phenomodel.html
- tests/server/blueprints/phenomodels/test_phenomodels_views.py
This PR adds the possibility to include orpha disease checkboxes to phenomodels. A radio button for selecting orpha_terms have been added to the phenomodels page. The form and functions previously in place for omim checkboxes have been renamed omim-> diseases and adapted to handle both orpha and omim terms.
This PR closes  #2159
<details>
1. `ssh …
> Fix orpha phenomodels

- CHANGELOG.md
- scout/server/blueprints/institutes/static/select2_darktheme.css
- scout/server/blueprints/institutes/templates/overview/institute_settings.html
This PR adds custom css to make multi selects in institute settings have dark mode styles.
This closes #3985
<details> …
> Apply dark mode styling to multi selects rendered by select2

- CHANGELOG.md
- scout/server/blueprints/variants/views.py
- Fix #4506, it's a bug present for all variant types, no just the fusion ones
<details> …
> Fix search for variants in genes present only in build 38 returning no results

- CHANGELOG.md
- scout/server/blueprints/api/views.py
✅ API call is now ok:
<details>
1. Start …
> More API pin fix

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- Link to chanjo2 coverage report for genes of the HPO panel. Other partial fix for #4000 
<hr>
<details> …
> Link to chanjo2 coverage report for genes of the HPO panel:

- CHANGELOG.md
- scout/constants/__init__.py
- scout/constants/clinvar.py
- scout/models/clinvar.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/form.py
- scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- tests/server/blueprints/clinvar/test_clinvar_views.py
- tests/server/conftest.py
- Closes #4373, see specifically the [last comment](https://github.com/Clinical-Genomics/scout/issues/4373#issuecomment-1918737418)
<details> …
> Add a new 'Explanation for multiple conditions` field in ClinVar form when a variant has more that one condition ID

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/gene_panel.html
This PR adds a functionality by replacing the default order of panels in the panel-table on case-page. This PR contains changes to render the panels in the table with the default panel in the first row of the table, followed by all other panels for the case in alphabetical order. 
In addition the option to sort the table depending on if the panel is the default or not has been added.
This PR closes  #4526
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are …
> Panel-table on case-page initially renders default panel in first row

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/constants/indexes.py
- tests/adapter/mongo/test_query.py
- Fix https://github.com/Clinical-Genomics/scout/issues/4533
<details> …
> reintroduce and slightly modify variant rankscore sort index

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
This PR closes #4546 by adding the same condition for rendering table Data containing inheritance information as was already present for the corresponding header. This applies to a #panel-table, in the case_report for cancer cases 
<details>
1. `ssh …
> Remove of table data  (without header) for inheritance in case_report if cancer case

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
This PR fixes a bug which caused the text "All pinned variants are described among the causative variants" to be displayed when this was not the case.
This PR closes #4547
<details> …
> Text claiming all pinned variants are represented in causatives is now only rendered if this is true

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/templates/cases/utils.html
This PR adds some space between <li> in some tables as well as replaces some <td> width attributes (deprecated in html5) with corresponding inline styles. Some <br> have been moved as to not render twice for the last child in a card as well as for unifying the structure of variant_content for different variant types. The aim for the change was to unify the visual expression of the nested tables in the case_report cards and to improve readability.
<details> …
>  Harmonization of case report spacing for some lists and #panel_tabels

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/utils.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
This PR adds a tooltip for the "combined score" header in the compounds table. For technical reasons the tooltip is conditionally rendered so it's not included when the table is itself displayed in a popover.
This PR closes #4560
<details> …
> Added tooltip for combined compound score

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
This PR adds a functionality or fixes a bug. Replaces blank (and partly faulty) frequencies card on the STR variant page with a card with locus details previously shown on the variantS page, plus lifting variant specific db links to the top of the page.
<details>
1. `ssh …
> Fix #4568 - add a STR details panel to the variant page

- CHANGELOG.md
- scout/server/blueprints/phenotypes/templates/phenotypes/hpo_terms.html
- Closes #4558
- Adds pagination to the HPO terms, which otherwise takes forever to load
<details> …
> Pagination and nr HPO terms on Phenotypes page

- CHANGELOG.md
- scout/adapter/mongo/disease_terms.py
> Typehead diseases when query contains source substring

- CHANGELOG.md
- scout/server/blueprints/clinvar/controllers.py
> Fix end coordinates in ClinVar for indels

- CHANGELOG.md
- scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- fix #4581
**I've considered the suggestion to force users to only provided conditions already assigned to the case, but I like the idea that they can also use other ontologies outside OMIM and ORPHA**, so I've opted to do a string is number check, see code.
<details>
1. `ssh …
> Stricter control over ClinVar condition IDs provided in ClinVar form

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/utils.py
- scout/server/blueprints/variants/utils.py
- Fix #2733 -> Use latest gene panel for panel overlap in variantS, variant view and case report
<details> …
> Use latest gene panel for panel overlap in variantS, variant view and case report

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/panels/templates/panels/panel.html
> Avoid chanjo2 queries when there are no genes available for stats

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- FIx #4607 --> Case with variants in ClinVar and variants pinned but not loaded, like this --> https://scout-stage.scilifelab.se/cust000/F0006358-mip7
<details> …
> Fix case crashing when evaluating ClinVar vars among pinned not loaded variants

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_bionano.html
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/templates/cases/case_sma.html
- scout/server/blueprints/cases/templates/cases/individuals_table.html
- scout/server/blueprints/cases/templates/cases/utils.html
Trying again with no slashes in the branch name.
Adds warning icon when sex is not confirmed in case tables. Close #4621 . I looked for locations in the code where `ind.confirmed_sex` is used.
It might be that our geneticists also want warnings for non male/females, but I'll ask them for more details and if so, come back with another issue / PR.
Suggestions are extra welcome as this is my first Scout-PR. On the code but also on PR etiquette. I see the testing checklist, but I guess it is for Stockholm devs with access to that environment.
Tested for the trio in the demo data. After updating the "confirmed_sex" field to "false" in the mongo db as such:
```
db.case.findOne({}, {individuals: 1})
{ …
```
> Non confirmed sex warning

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/str-variants.html
I was so sure I tested that? Sorry! 😊 
<details> …
> Fix #4624 - show ExHu STR sizes again

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
> Fix MT-report crash when one of the samples is not in chanjo db

- CHANGELOG.md
- scout/adapter/mongo/hgnc.py
- scout/load/panel.py
- scout/parse/panel.py
- tests/adapter/mongo/test_gene_handler.py
- Fix [this issue](https://github.com/Clinical-Genomics/scout/issues/4070#issuecomment-2136766038)
Note that there are some genes that are missing Ensembl IDs in PanelApp, for instance [KCNJ18](https://panelapp.genomicsengland.co.uk/panels/entities/KCNJ18) (only by chance this gene is present only in build 38 in scout)
The problem is that scout relies on Ensembl gene - HGNC ID  mappings to load the genes in PanelApp panels
<details> …
> Fix PanelApp panel not saving genes with empty `EnsembleGeneIds` list

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
This PR speeds up a slow controller, partially addressing #4655.
<details>
1. Start the …
> A small projection on panels, and use sets instead of explicit loops

- CHANGELOG.md
- scout/adapter/mongo/institute.py
- This is a fix also present in #4658
<details> …
> Optimise safe genes by avoiding duplicates when collecting genes from many panels

- CHANGELOG.md
- scout/adapter/client.py
- scout/adapter/mongo/variant.py
- scout/commands/base.py
- scout/parse/disease_terms.py
- scout/parse/omim.py
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case.html
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/cases/views.py
- scout/server/extensions/beacon_extension.py
- scout/server/extensions/phenopacket_extension.py
- scout/server/static/bs_styles.css
- tests/server/blueprints/cases/test_cases_controllers.py
I added a very simple hiding functionality for matching causatives. They will now only show (and compute) on the case page if requested. 
And clicking it:
I'm sure this could be rather smoothly done in js as well with a request to fill in that part of the document and does the compute in a new api endpoint. But simple can be good. Thoughts?
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs …
> Small event projection

- CHANGELOG.md
- Dockerfile
- Dockerfile-server
- We tried this before but had to revert because of [chanjo-report](https://github.com/Clinical-Genomics/scout/issues/4101). Now that issue should be solved!
<details> …
> Upgrade python to 3.11 in the Dockerfiles

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/extensions/loqus_extension.py
- tests/server/extensions/test_loqusdb_api_extension.py
- Closes #4669
<details>
1. Start the …
> Flash an alert when loqus instance is not reachable

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/variants/controllers.py
- tests/adapter/mongo/test_variant_handling.py
> Safer variant updates in variantS controllers

- CHANGELOG.md
- scout/server/extensions/chanjo_extension.py
- tests/adapter/mongo/test_variant_handling.py
- Closes #4675. Don't try to import the chanjo-report lib unless `SQLALCHEMY_DATABASE_URI` is present in settings
<details>
1. …
> Clearer chanjo-report error message only when needed

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/adapter/mongo/variant_loader.py
- scout/constants/file_types.py
- scout/load/all.py
- scout/server/links.py
- scout/utils/sort.py
- tests/utils/test_sort.py
The load order was perturbed last week with 4.83 introducing sets of file type categories, to accommodate nf-core raredisease MT VCFs. Introducing an alpabetical sort will work around the problem encountered in #4682 in the sense that SNVs will be loaded before SVs, and in particular `cancer` before `cancer_sv`, and the collision resolution should be consistent.
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you …
> Workaround fix #4682 - sort case file load order alphabetically

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- Fix #4695 
- Fix sorting of the select default panels dropdown - as discussed in #4695 
Marking this as a bug fix as the display of the "removed" badge was there once upon a time, but now only for the default panels. Refactored a little to do the panel hiding check separate from the default panel check and latest panel genes update.
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is …
> Sort select default

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
Close #4698 
Show (Removed) after removed panels in dropdown.
Tested by adding two panels, adding them to the test case, and loading it into Scout. And then removing one of the panels.
<details> …
> Show (Removed) after removed panels in dropdown

- CHANGELOG.md
- scout/parse/variant/variant.py
REVEL score is collected as the maximum REVEL score from all of the variant's transcripts (closes #4693 )
<details>
1. Stop the …
> REVEL score deep parsing

- CHANGELOG.md
- scout/parse/variant/transcript.py
- Closes #4714 --> Try to parse to float only GNOMAD POPMAX values that are numerical
<details> …
> Try to convert to float only GNOMAD POPMAX values that are numerical

- CHANGELOG.md
- scout/parse/variant/callers.py
> Fix #4729 - check caller keys also from FOUND_IN and SVDB_ORIGIN before adding

- CHANGELOG.md
- scout/constants/clinvar.py
- scout/server/app.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/config.py
- scout/server/extensions/clinvar_extension.py
- tests/server/blueprints/clinvar/test_clinvar_views.py
- Closes #4611
<details>
1. Start the …
> Option to override the ClinVar API URL to test against ClinVar 'apitest'

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
- Fix #4734 - spliceJunction tracks
Before:
❌ 
✅ After:
- Fix #4737 
Click 
Before: crash email
After: no crash
<details>
1. Stop …
> Fix #4734 - spliceJunction height offset

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/parse/variant/frequency.py
- scout/server/blueprints/variant/utils.py
- tests/parse/test_frequency.py
- Closes #4742
<details>
1. Start the …
> Parse and show CoLoRSdb frequencies

- CHANGELOG.md
- scout/server/links.py
> Fix ExAC links

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- Simplify and apply CSS style to custom IGV tracks tables
<details> …
> Revert table style and remove font awesome from IGV template

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
Not super pretty without genes, but the user can now at least opt to disable them without making the view go down.
<details>
1. …
> Fix #4769 - users can disable gene track and still see sashimi view

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/blueprints/variant/views.py
- Closes #4770 - Now you can enable or disable whichever track you want
<details> …
> Respect igv tracks settings

- CHANGELOG.md
- scout/constants/igv_tracks.py
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- Fix #4782 with igv.js alias files
<details> …
> Fix #4782 - explicit igv.js chr alias option

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/extensions/chanjo_extension.py
- scout/server/extensions/matchmaker_extension.py
- tests/server/blueprints/cases/test_cases_controllers.py
- tests/server/extensions/test_chanjo_extension.py
- Move chanjo-specific code to the chanjo extension instead of having it on the cases controllers - Simplify before addressing #4836 
<details> …
> Move the code to collect MT copy number stats for MT report to the chanjo extension

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- tests/conftest.py
- tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
- tests/server/blueprints/alignviewers/test_alignviewers_views.py
Fix #4835 - use OMICS variant with a surrounding window for IGV view locus 
Help out finding aberration causes by centring in on the OMICS variant if given.
<details> …
> Igv locus make fix

- CHANGELOG.md
- scout/constants/disease_parsing.py
- scout/parse/omim.py
- scout/utils/convert.py
- scout/utils/date.py
- Fix #4851 - string escape warnings on tests
Before:
<details> …
> Fix string pattern warnings

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
- scout/server/templates/report_base.html
Hide ORPHA inheritance patterns on general report, as they can be misleading. Compare note on variant view. 
Also added colored badges for the OMIM inheritance models for consistency with the variant page.
Before: 
After:
<details>
1. …
> Fix #4862 - ORPHA inheritance patterns hidden

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/constants/indexes.py
> Subject id search

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/individuals_table.html
Gens button enabled also on cancer individuals table (if gens integration is enabled).
<details> …
> Fix #4884 - enable Gens balsamic button

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- Display coverage report in the side panel of any case with or without associated gene panels - at least one case sample should have a d4 file
- This PR is used in a combo with [this chanjo2 PR](https://github.com/Clinical-Genomics/chanjo2/pull/347)
<details>
1. …
> Chanjo2 report available for cases without gene panels

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- Fix #4895 
Before: 
After:
<details>
1. …
> Fix #4895 - missing STR source crash in general report

- CHANGELOG.md
- scout/constants/acmg.py
- scout/server/blueprints/variant/templates/variant/acmg.html
It turns out the SVI PVS1 flowchart is basically included in the Tayoun publication which we already link. I held off on that, but included other guidelines that were discussed in the GMCK-RD meeting, ie for RNA on PVS1/PM6, as well as in trans and *de novo* semi-quantitative approaches (PS2, PM3).
<details>
1. `ssh …
> Fix #4907 - add more ACMG ClinGen SVI links

- CHANGELOG.md
- scout/utils/acmg.py
- tests/utils/test_acmg.py
- Fix #4926 
✅ 
<details>
1. Start the …
> Fix benign moderate modifiers

- CHANGELOG.md
- scout/constants/acmg.py
- scout/server/blueprints/variant/templates/variant/acmg.html
- scout/server/blueprints/variant/views.py
- scout/utils/acmg.py
- tests/utils/test_acmg.py
- Fix #4906 
Thanks to @4WGH for highlighting this and for a good discussion on potential pairs.
<details> …
> Fix #4906 - warn on potentially conflicting ACMG terms.

- CHANGELOG.md
- scout/constants/acmg.py
- scout/server/blueprints/variant/templates/variant/acmg.html
- scout/server/blueprints/variant/views.py
- scout/utils/acmg.py
- tests/utils/test_acmg.py
This PR adds a functionality: Bayesian point sums for an alternative ACMG classification, and temperature for VUS.
- Fix #4909 
Ok! I will brush up the visuals and add some tests, but kinda looks promising! 🌶️ 
<details> …
> Fix #4909 - Tavtigian Bayesian point sums

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
- Tentative fix #4951 
<details>
1. Start …
> Fix downloading gene variants for genes with no symbol

- CHANGELOG.md
- scout/models/case/case_loading_models.py
- Fix #4970. Notice that panels already has checks for empty values. The custom images dict is a little bit more involved, since it gets reformatted a bit into its member class objects before the offending crash. Ignoring empty ones on parsing appears to successfully leave the main key unset on db, fixing the issue.
Tested on local, with normal `custom_images`, `custom_images` set to `{}` and for a case config without `custom_images`.
<details> …
> Fix #4970 - empty custom images dict does not crash on load

- CHANGELOG.md
- scout/server/utils.py
- Fix #4974 - don't crash on missing cram files for one sample
<details> …
> Fix #4974 - crash on missing aln file for one of the inds

- CHANGELOG.md
- scout/commands/export/variant.py
- Fix #4969 - specifically the variants mentioned there.
First we confirmed on db that the variants were input as noted in the issue. For the future, this can be adressed in #4972. 
Here we ensure that each of
- `ALT=""`
- `REF=""`
- `ALT = "del"` or `"ins"` (rather than `<DEL>` or `<INS>`). 
are converted to sensible values during VCF export.
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call …
> Fix #4969 - adress the VCF output of given managed variants

- CHANGELOG.md
- scout/server/blueprints/cases/views.py
- Closes #4979 
<details>
1. Start the …
> /api/v1/hpo-terms handles pymongo OperationFailure errors

- CHANGELOG.md
- scout/parse/variant/genotype.py
For the vast majority of all variants, even for cancer this appears a non-issue. Larger variants are more susceptible, and in particular some dubious SNVs that VarDict still passes in the SNV file instead of marking as SVs. But they are clinically important, the current guesstimate for ref-alt allele depth is not very good and the fix is easy.
Before 
After
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are …
> Triallelic cancer VAF

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- Fix #5012 - cancer SV spinner does not stop - missing form validation
<details> …
> add form validate for cancer svs

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/utils.html
- Closes #5004  --> I have reasoned that it is better to add MANE tags down in the transcripts table **because a SV variant can have many genes and we don't want the variant page swamped with refseq transcritps, which will happen if we introduce the `RefSeq transcripts` panel as we have on SNV variant page**
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server …
> Add MANE badges to the long list of transcripts on variant page

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/utils.py
- Fix #4974 for a more general situation (any and all files can be missing)
<details> …
> Missing track item pt2

- CHANGELOG.md
- scout/parse/variant/clnsig.py
> Fix typing error when using python 3.9

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/utils.py
- Fix #5049 - The specific issue is due to the presence of the index but the lack of the bam
<details> …
> Fix missing track round3

- CHANGELOG.md
- scout/adapter/mongo/panel.py
- scout/constants/indexes.py
- tests/server/blueprints/cases/test_cases_controllers.py
- Closes #5066 
<details>
1. Start the …
> Add panel indexes and better version check when editing a panel

- CHANGELOG.md
- scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
This PR fixes a bug:
- Fix #5070 
<details>
1. Start the scout service with the branch …
> Fix #5070 - WTS SNVs and SVs buttons open on new tab

- CHANGELOG.md
- scout/server/blueprints/variant/utils.py
> Fix #5075 - variant filters is redecorated

- CHANGELOG.md
- scout/server/blueprints/variant/utils.py
I'll do a couple of uploads as well to be more sure.
While better:
It was again, due to a typo in the fix for the redecoration issue:
Fixed again:
<details> …
> Fix typo in callers redecoration fix

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/components.html
- On variantS page, when a variant has more than one gene, then the gene panel badge reflect the panels each gene is actually in (fix #5087)
<details> …
> Fix multigene panels count

- CHANGELOG.md
- scout/server/links.py
> Fix UCSC hg38 link

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/utils/acmg.py
- Closes #5099
<details>
1. Start the …
> Add ACMG VUS Bayesian score / temperature on case reports

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/components.html
- Fix #5126
Tested on local research variants
<details> …
> Fix tooltips on variants not overlapping with any gene panels

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- Fix #5128
Trying to retain some of the proportion of emphasis between chr-pos and var-counts:
<details> …
> Fix #5128 - visibility of muted vaf counts, position on cancer variantS

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
> Fix #5129 - show chromosome on each BND end if diffent

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
- scout/server/blueprints/variants/templates/variants/components.html
This PR refactors an existing functionality, and harmonises display between SNV and SV somatic variantS view alleles.
Also saw one more muted item on the cancer_sv variant line, the Manta SOMATICSCORE. Added a tooltip for those that have not been here since day 1 of that. 😊 
<details>
1. `sudo -iu …
> Refactor and follow up on #5128 fix also for SVs

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/adapter/mongo/variant.py
- tests/adapter/mongo/test_query.py
- Tentative fix #5127
<details>
1. Start …
> Add complexity to SV queries when SV is BND

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
> Fix #5153 - general report ACMG temperature respects criteria term modifier

- CHANGELOG.md
- scout/parse/omim.py
- scout/utils/link.py
- uv.lock
It's not easy when it's not easy I guess. But I'm tempted to say "trivial" post hoc. Old aliases could contain lower case letters in the HGNC `previous_symbols`, which would then not match gene symbols (that are now mandated to be upper case).
❌  Before:
✅ After:
<details>
1. `ssh …
> Fix odd hgnc gene inheritance

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/views.py
- Adds a link to assign a quick ACMG classification to SV variants (SVs and cancer SVs) - Closes #5074
<details>
1. Stop the …
> Simple ACMG classification for SVs

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- Closes #5152
<details>
1. Start the …
> Skip variant genotype matching check when matching causative is found in case with one sample

- CHANGELOG.md
- scout/constants/gene_tags.py
- scout/parse/panelapp.py
- Fix #5170. This bug is likely happening because the inheritance models have a slightly different naming in the other PanelApp API
<details> …
> Fix save PanelApp inheritance models

- CHANGELOG.md
- scout/adapter/mongo/managed_variant.py
- scout/adapter/mongo/query.py
- scout/server/blueprints/managed_variants/forms.py
- scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
- scout/server/blueprints/variants/forms.py
> Fix query by coordinates - start coordinate must be >=1

- CHANGELOG.md
- scout/parse/variant/compound.py
- Fix #5008 
Before: 
After:
<details>
1. …
> Fix #5008 - genmod compounds could be prefixed by chr string

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/utils/ccv.py
Closes issue #5143 
<details>
1. Start the …
> Report ccv score/temperature on case report 

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variants/templates/variants/cancer-variants.html
> Truncate long HGVS descriptions on cancer SNVS and SNV pages

- CHANGELOG.md
- docs/admin-guide/loading-case.md
- scout/demo/cancer.load_config.yaml
- Fix #5184 - Avoid calling ranking function for a case without ranking.
<details> …
> Skip calling rank function for the demo case without ranking

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/links.py
- Including some additional info for SNVs and cancer SNVs - closes #5003
<details> …
> Add severity predictions and functional annotation on case report for SNVs and cancer SNVs

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/str-variants.html
> Fix #5194 - display STR variant filter status on variantS page

- CHANGELOG.md
- scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
- scout/server/blueprints/clinvar/views.py
- tests/server/blueprints/clinvar/test_clinvar_views.py
- Discontinue ClinVar submissions via CSV files and support only submission via API: removed buttons for downloading ClinVar submission objects as CSV files. (closes #5196)
<details> …
> Discontinue ClinVar submissions via CSV files

- CHANGELOG.md
- scout/constants/acmg.py
- scout/utils/acmg.py
- Warning and reference to Bieseker et al 2024 when using PP1/PP4 and BS4 in ACMG classifications
- Warning to not to use PP4 criterion together with PS2/PM6 in ACMG classifications with reference to the SVI Recommendation for _de novo_ Criteria (PS2 & PM6)
- closes #5101 
<details>
1. `ssh …
> More acmg conflicts warnings

- CHANGELOG.md
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
- scout/server/blueprints/clinvar/views.py
- scout/server/extensions/clinvar_extension.py
- tests/server/blueprints/clinvar/test_clinvar_views.py
- tests/server/conftest.py
- tests/server/extensions/test_clinvar_extension.py
How the feature works:
- Adds the possibility to delete an already processed submission, by clicking on a button. What happens then:
- scout calls the ClinVar API to retrieve the status of the submission, it the status is 'processed':
- Scout downloads a submission summary. if the status in this summary is "Success":
- Scout extracts the ClinVar accession number (SCVxxxxxxx)
- Sends a request to PreClinVar with the accession to send a request to the ClinVar API for removal
- Closes #5029
<details>
1. Fist book …
> Remove successfully processed submissions from ClinVar

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/server/blueprints/variant/views.py
- Fix #5178
Before:
After:
<details>
1. …
> Re-raise on load rollback

- CHANGELOG.md
- pyproject.toml
- scout/server/blueprints/variant/views.py
- uv.lock
<details>
1. Start the scout service with the branch to test: `systemctl --user start …
> Minor release 4.96

- CHANGELOG.md
- scout/commands/update/individual.py
- scout/exceptions/database.py
- scout/models/managed_variant.py
- scout/models/omics_variant.py
- scout/parse/variant/variant.py
- scout/server/app.py
- scout/server/extensions/beacon_extension.py
- scout/server/extensions/bionano_extension.py
- scout/server/extensions/chanjo_extension.py
- scout/server/extensions/matchmaker_extension.py
- scout/server/templates/layout.html
- Close #5193 ? - Could be expanded later, this is a very simple fix.
<details> …
> Add software version and link to the GitHub release on the top left dropdown

- CHANGELOG.md
- scout/adapter/mongo/omics_variant.py
- scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
- scout/server/blueprints/omics_variants/views.py
- scout/server/blueprints/variants/forms.py
- Option to sort WTS outliers by p_value, Δψ, ψ value, zscore or l2fc (closes #4989)
<details> …
> Sort WTS outliers by p_value, Δψ, ψ value, zscore or l2fc

- CHANGELOG.md
- scout/utils/ensembl_biomart_clients.py
- Fix parsing of Ensembl resources. While working on #5204, I've realised that the only missing gene after the parsing is MT-TP - I'll include comments in the PR code, to explain why I think this happens
<details>
1. …
> Fix parsing of entire Ensembl documents - including MT-TP gene

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variant/utils.py
- Closes https://github.com/Clinical-Genomics/scout/issues/4991
- Adds pLI scores on SNV and cancer SNV pages
<details>
1. Stop …
> pLI scores on SNV and cancer SNV pages

- CHANGELOG.md
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- Closes #5231
<details>
1. Start the …
> Preselect MANE SELECT transcripts in the ClinVar multistep form

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/omics_variants/views.py
- Fix #5237 
Looks good on local:
Added shortcut for clinical filter HPO WTS on case page.
Looks ok also for narrow pages.
<details>
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman …
> Fix #5237 - enable HPO searches on WTS outlier page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/chanjo2_form.html
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/extensions/chanjo2_extension.py
- tests/server/extensions/test_chanjo2_extension.py
- Fix  #4955
- Fix #376 
So far, so good:
<details> …
> Complete coverage indicator chanjo2

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/templates/variants/utils.html
- Improved SNVs and SVs filter (RD & cancer cases) - now supporting size thresholds (≥ or < a specified base pair length): fix #5223 
<details> …
> Variants filter by size

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/cases/views.py
- scout/server/blueprints/omics_variants/views.py
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/views.py
> Fix #5258 - stop clinical filter HPO when dynamic gene panel is emptied

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/server/blueprints/variants/templates/variants/utils.html
- Fix variantS query when:
-  Excluding ClinVar CLINSIG 
- Prioritise ClinVar is NOT checked
- Secondary search is on (for instance variants shorter than 2 bases)
<details>
1. (optional) Find out which scout branch …
> Fix exclude ClinVar + secondary filter

- CHANGELOG.md
- docs/admin-guide/panelapp_panels.md
- Document the option to collect green genes from any panel when updating the PanelApp green genes panel
<details>
1. Stop the …
> fix docs for PanelApp green genes cli

- CHANGELOG.md
- pyproject.toml
> Version 4.98

- CHANGELOG.md
- docs/admin-guide/load-config.md
- docs/admin-guide/updating-individuals.md
- scout/build/individual.py
- scout/commands/update/individual.py
- scout/models/case/case_loading_models.py
- scout/server/utils.py
- tests/build/test_build_individual.py
- tests/parse/test_parse_case.py
I dunno, we could consider only showing these on particular endpoints (e.g. paraphase from the SMN view etc) but they do lend information where they exist. The aln tracks could perhaps be shrunk down to fewer (250-300?) px by default, but we could also take this as is without adding more complexity, and adjust later if it becomes an issue.
<details>
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on …
> Additional LRS alns: paraphase and de novo

- CHANGELOG.md
- scout/constants/igv_tracks.py
- scout/demo/643594.config.yaml
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
I especially like the coverage one, since it gives a Quick Look at larger deletions etc and a bit more context when zooming in and around, without having to jump back and forth between IGV and gens when evaluating more complex SVs.
<details>
1. `sudo -iu …
> Fix #1386 - reenable tracks after track security improvements

- CHANGELOG.md
- tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
- tests/server/blueprints/alignviewers/test_alignviewers_views.py
- Closes #5317
<details>
1. Start the …
> Mock Ensembl liftover in igv tracks tests

- CHANGELOG.md
- scout/adapter/mongo/institute.py
- scout/server/blueprints/institutes/controllers.py
- tests/adapter/mongo/test_institute_handler.py
- tests/commands/update/test_update_institute_cmd.py
- Fixes #5306 
<details>
1. Start the …
> Institute settings reset

- CHANGELOG.md
- scout/constants/variant_tags.py
- tests/adapter/mongo/test_variant_events.py
> Fix #5316 - RF and other default color tags hard to see

- CHANGELOG.md
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- scout/server/blueprints/clinvar/views.py
- scout/utils/hgvs.py
- Closes #5299 
<details>
1. Start the …
> Avoid HGVS validations in CLinVar form for non-MANE transcripts for variants in build 38

- CHANGELOG.md
- scout/utils/ensembl_rest_clients.py
- tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
- tests/server/blueprints/alignviewers/test_alignviewers_views.py
- tests/server/blueprints/variant/test_variant_views.py
- tests/utils/conftest.py
- tests/utils/test_ensembl_rest_clients.py
- Closes #5323
<details>
1. Start the …
> Fix liftover

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/utils.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/mei-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/utils.html
- scout/server/blueprints/variants/templates/variants/variants.html
- tests/adapter/mongo/test_query.py
- Fix #5252 - add gene overlapping for SVs
- Fix #3955 (and eg dupe #4132) - add gene overlapping for MEIs
- Fix #2195 - actually partially fix; a genmod 2hit model, similar to the inheritance aware compounds will be great eventually.
Feels really nice on demo. Caveat would likely be the aggregated query time. This is one of those things that we could start doing somewhat asynchronously - ie when someone hovers over, we could fetch the tooltip contents via api. For proper compounds, especially with compound filters active, we would need to be rid of the button, but for most variant types and genes we would now some kind of second match, no? There is surely at least some SV covering the whole chr... 🙄 
<details>
<summary>Testing on cg-vm1 server …
> sv overlaps

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/login/controllers.py
- scout/server/blueprints/login/views.py
- scout/server/blueprints/public/templates/public/index.html
- scout/server/config.py
- tests/server/blueprints/login/conftest.py
- tests/server/blueprints/login/test_views.py
- Closes #5315
<details>
1. Start the …
> Keycloak login

- CHANGELOG.md
- scout/commands/download/ensembl.py
- scout/utils/ensembl_biomart_clients.py
- tests/commands/download/test_download_ensembl_cmd.py
- Closes #5352 
Tested locally:
- Genes 37 🆗 
- Genes 38 🆗 
- Transcripts 37 🆗 
- Transcripts 38 ❌ - incomplete file
<details>
1. …
> Ensembl data integrity check

- CHANGELOG.md
- scout/commands/update/panelapp.py
- scout/constants/panels.py
- scout/load/panelapp.py
- tests/commands/update/test_update_panelapp_green.py
> Custom ID/name for PanelApp updates

- CHANGELOG.md
- pyproject.toml
- uv.lock
This PR marks a new Scout release. We apply semantic versioning. This is a minor release since it adds features, fixes issues and changes code and behaviour in a backwards compatible manner.
<details> …
> Version 4.99

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/components.html
- Fixes #5350 
<details>
1. Start the …
> Fix ugly Alamut button on variant page

- CHANGELOG.md
- scout/adapter/mongo/query.py
> Fix #4057 - allow matching part of compounded SV subtype

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/acmg.html
- scout/server/links.py
- Partially fix #4048 - add link to CSPEC. They do have JSONs for retrieval and use in adapting the whole ACMG page, but that is a big project, which will need to be revamped considerably when ACMG v4 goes live: it is in an early pilot stage right now.
<details> …
> Partially fix #4048 - add links to cspec

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/gene_panel.html
- scout/server/blueprints/panels/templates/panels/panel.html
- Closes #4893 - chanjo2 reports already open in new tabs, but case gene panels don't
<details> …
> Clearer case panels tabs

- CHANGELOG.md
- scout/commands/load/research.py
This PR adds a functionlity or fixes a bug.
- Closes #5216
<details> …
> Respect case rank score threshold when uploading research variants

- CHANGELOG.md
- scout/adapter/mongo/query.py
- scout/constants/__init__.py
- scout/constants/query_terms.py
- scout/server/blueprints/variants/forms.py
- scout/server/blueprints/variants/templates/variants/utils.html
- tests/adapter/mongo/test_query.py
- Closes #5305 
<details>
1. Start the …
> Filter cancer SNVs by oncogenicity

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- Closes #5374
<details>
1. Start the …
> Fix general report to show all dismissed variants (not pinned or causatives) only among the dismissed

- CHANGELOG.md
- scout/adapter/mongo/variant.py
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/utils.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/components.html
- scout/server/blueprints/variants/templates/variants/utils.html
- tests/adapter/mongo/test_query.py
- Closes #4796
Display gene-matching WTS ouliers on variantS pages:
And on variant page:
<details> …
> Display gene-matching WTS outliers on DNA variants pages

- CHANGELOG.md
- scout/adapter/mongo/omics_variant.py
- scout/adapter/mongo/variant.py
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/templates/variant/cancer-variant.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- scout/server/blueprints/variant/templates/variant/utils.html
- scout/server/blueprints/variant/templates/variant/variant.html
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/components.html
> Fix #5383 - scope of overlapping functions

- CHANGELOG.md
- tests/server/blueprints/variants/test_variants_controllers.py
- Some tests invoking the variants controller's [def variants](https://github.com/Clinical-Genomics/scout/blob/9dfbf5bf59d011bf90d38e63963440dee0ea0b16/scout/server/blueprints/variants/controllers.py#L126) function are failing when runned by themselves.
I suspect that they fail because they work with a mocked database (real_variant_database) that works fine as long queries are like this: adapter.variants(params). But when they invoke the variants controllers then there is this function to collect [overlapping vars](https://github.com/Clinical-Genomics/scout/blob/9dfbf5bf59d011bf90d38e63963440dee0ea0b16/scout/server/blueprints/variants/controllers.py#L152) that calls stuff and in the end [an adapter …
> controllers.variants tests in the app context

- CHANGELOG.md
- scout/adapter/mongo/variant_loader.py
- scout/commands/load/research.py
- Displays clearly which file is being used for loading research variants
- **Does NOT fix** #5408, but makes it easier to debug 
<details> …
> Clearer messages when loading vars

- CHANGELOG.md
- pyproject.toml
- scout/parse/ensembl.py
- Fix https://github.com/Clinical-Genomics/scout/issues/5434
<details> …
> Fix parsing of Ensembl lines - safely avoid lines with chromosome separators

- CHANGELOG.md
- scout/adapter/mongo/case.py
- scout/constants/file_types.py
- tests/adapter/mongo/test_load_adapter_case.py
> Fix #5450 - patched file read order from #5411

- CHANGELOG.md
- tests/adapter/mongo/test_sanger_validation.py
New release branch:
- Another fix for #5383
- Same as #5391
<details> …
> Fix failing test

- CHANGELOG.md
- scout/server/blueprints/cases/controllers.py
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/utils.py
- scout/server/blueprints/variants/controllers.py
> Fix #5454 - long STRs display on case page

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
This PR fixes an issue where the assignees for a case wouldn't be visible in the list of cases. This is exactly the same fix as for #3979, but here it wasn't as apparent that something was missing.
> Show assignees in case list when user ID is different from email

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
> Remove observations when removing ClinVar variant

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
> Fix chanjo2 full coverage check for variants without genes

- CHANGELOG.md
- scout/server/blueprints/login/views.py
> Fix #5469 - let flask login deal with clearing session itself in its time

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/templates/overview/cases.html
- scout/server/blueprints/login/controllers.py
- tests/adapter/mongo/test_case_group_handling.py
- Fix #4705 
"Dismiss" color caseS that were not featured in search explicitly, but included "only" for being in an always-show category.
Works also when the situation is more complex, as e.g. multiple matches and some in "solved" cases that already have a highlight.
<details>
1. `ssh …
> Fix #4705 - Dim cases from always-show categories

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- Closes #5473. I'm placing this table on top of the pop frequency one (1000G, ExaC, etc) on purpose because the latter is going to be smaller in the future (see #5474)
<details> …
> Clinvar links on report

- CHANGELOG.md
- scout/adapter/mongo/omics_variant.py
- scout/adapter/mongo/variant_loader.py
> Do not raise error when trying to load missing omics files

- CHANGELOG.md
- pyproject.toml
- uv.lock
<details>
1. Stop the service with current deployed branch: `systemctl --user stop scout@<name_of_currently_deployed_branch>` …
> Release 4.102

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
> Fix problematic pymongo cursor data type

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
> Fix #5506 - dim more cases if no specific case query given

- CHANGELOG.md
- scout/parse/variant/gene.py
> Fix parsing of canonical transcripts for variants outside genes

- CHANGELOG.md
- tests/adapter/mongo/test_query.py
> Improve test for overlapping variants - check overlapping WTS

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
- scout/server/blueprints/clinvar/controllers.py
- scout/server/blueprints/clinvar/views.py
> Fix downloading of json ClinVar submission with no observation data

- CHANGELOG.md
- scout/adapter/mongo/variant_loader.py
- Fix #5524 - it was just an unnecessary warning
<details> …
> Fix #5524 - dont warn on unset file types on case load

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant_details.html
- Fix #5545 - missing value REVEL and SpliceAI are set to `"-"` at the rendering stage
After, for a variant with missing values (STR):
For comparison and safety, a variant (SNV) with values:
<details>
1. (optional) …
> Fix #5545 - REVEL and SpliceAI missing dash color

- CHANGELOG.md
- scout/server/app.py
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/variant/templates/variant/variant_details.html
> Fix SpliceAI label/color when variant is multigenic

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/utils.html
> Fix collapsing chevron on variantS filters

- CHANGELOG.md
- scout/server/blueprints/alignviewers/controllers.py
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- Fix #5549
The main idea here is to enable autoscaling for tracks like rhocall autozygosity (0-1). We do so by simply removing the fixed default max value of 30 (30x depth). To make the alignment depths comparable at a glance, we instead group them in an autoscaleGroup.
<details>
1. `ssh …
> Igv autoscale

- CHANGELOG.md
- pyproject.toml
- uv.lock
This PR marks a new Scout release. We apply semantic versioning. This is a patch release for reasons.
- Fix #5578 
Before (Version 4.103.1):
After (Version 4.103.2):
<details>
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman …
> Release version 4.103.2

- CHANGELOG.md
- scout/server/blueprints/institutes/views.py
> Sort institute multiselect alphabetically by display name on 'Search SNVs & SVs' page

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/str-variants.html
- Fixes partially #5586 
<details> …
> Fix missing STRs repeat locus when there is not gene set in the variant

- CHANGELOG.md
- pyproject.toml
- uv.lock
<details>
1. Stop the service with current deployed branch: `systemctl --user stop scout@<name_of_currently_deployed_branch>` …
> Patch release 4.103.3

- CHANGELOG.md
- scout/parse/variant/variant.py
> Treat -1 as None when parsing archived local frequencies

- CHANGELOG.md
- scout/build/variant/variant.py
- scout/parse/variant/variant.py
- scout/server/blueprints/variant/templates/variant/variant_details.html
- scout/server/blueprints/variants/templates/variants/components.html
Added:
- Parse `Cancer_Somatic_Panel_Frq` and `Cancer_Somatic_Panel_Obs` keys from VCF INFO field
**OBS: This PR fixes the parsing and displaying of the freq and observations on variant and variantS pages. It does not include the keys into the variants filters - we'll address it in another PR**
<details> …
> Parse cancer somatic panel local freqs

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_sma.html
- scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
- scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
- scout/server/blueprints/variants/templates/variants/fusion-variants.html
- scout/server/blueprints/variants/templates/variants/mei-variants.html
- scout/server/blueprints/variants/templates/variants/sv-variants.html
- scout/server/blueprints/variants/templates/variants/variants.html
- Closes #4833
- Fixes the [''] panel issue
- Opens correctly the link into a new tab
<details> …
> Fix links to SNVs and SVs from SMN page

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/chanjo2_form.html
- Panel data doesn't have associated panels at the moment and when d4 files are provided for these cases the chanjo2 stats are computed as if they were WGS cases, resulting in very low coverage stats. Treating these cases as WES (still incorrect) would help improving the stats 
- This PR has to be used in a combo with a fix for this issue on chanjo2 -> https://github.com/Clinical-Genomics/chanjo2/issues/488, otherwise the stats won't change. But I guess it can be fixed in scout anyway because if you provide a gene list in the request then it would work perfectly
<details>
1. Make sure the PR is pushed and available on [Docker …
> Treat panel analyses as WES when getting chanjo2 stats

- CHANGELOG.md
- scout/adapter/mongo/managed_variant.py
- scout/commands/export/variant.py
- scout/constants/managed_variant.py
- scout/export/variant.py
> Export managed variants CLI now accepts one or more categories

- CHANGELOG.md
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/templates/variants/str-variants.html
- Fix #5586 
Ok, so three-four steps here:
Now `variant.genes` appears repopulated later when discovered missing on variants page load, and not used until later.
For now this kind of solves the issue already with steps 1 and 2 anyone will be hard pressed to find a use case where the variants will not simply be displayed/populated in time. But they will arguably not be fully "finished" until the second reload (compared to fourth before), so we should probably fix it. Just not Friday evening. 😝 
Here is testing with a local case reload, first on main:
❌ no symbols on the loci (will resolve after reloading, converging after four)
✅ with this PR, looks fine from the start, though behind the scenes the db objects will not be fully updated until the …
> Fix #5586 - TRGT_ID loci gets late genes.hgnc_symbol population, and hence strange reload behaviour

- CHANGELOG.md
- Dockerfile
- Dockerfile-server
> Fix Dockerfiles to remove package metadata after installation

- CHANGELOG.md
- scout/commands/base.py
- scout/server/app.py
- scout/utils/config.py
- tests/commands/test_base_command.py
- Refactored how app config file is parsed to have a centralised function only
<details> …
> Centralised config loader for cli and web app

- CHANGELOG.md
- docs/admin-guide/export.md
- scout/commands/export/export_command.py
- scout/commands/export/variant.py
- scout/export/variant.py
- tests/commands/export/test_export_causatives_cmd.py
- tests/commands/export/test_export_causatives_verified_cmd.py
- Clearer CLI export of causative variants. I was confused myself when using it
If you run `scout export --help`
Using this branch, you should be able to use both the option causatives or variants without difference
<details>
1. `ssh …
> Clearer export causatives command

- CHANGELOG.md
- scout/server/blueprints/variant/templates/variant/variant_details.html
- Fix #5676 
With this
- 0 → shows 0
- -1 → shows N/A
- None or missing field → shows N/A
- Undefined frequency → falls through to N/A
<details> …
> Fix negative observations in archived loqus table and refactor

- CHANGELOG.md
- scout/server/blueprints/cases/templates/cases/case_report.html
- scout/server/blueprints/cases/templates/cases/utils.html
- scout/server/blueprints/variant/templates/variant/components.html
- scout/server/blueprints/variant/templates/variant/sv-variant.html
- tests/server/blueprints/cases/test_cases_templates.py
> Expand tx info on SV variants summary (variants with <= 5 genes)

- CHANGELOG.md
- scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
- Fix #5714 
Much better. I tried turning on the "squished" display mode by default as well, like in the tutorials over at Paraphase. It's nice for an overview; perhaps not ideal for looking at a single variant though. Thoughts @fellen31?
<details>
1. `sudo -iu …
> Fix #5714 - change default track options for paraphase alignments

- CHANGELOG.md
- scout/server/blueprints/omics_variants/views.py
- scout/server/blueprints/variants/controllers.py
- scout/server/blueprints/variants/views.py
- Fix #4227 - Now if you click on clinical filter from research variants pages you will get a list of research variants with clinical filter applied, and you won't be redirected to clinical variantS page
<details> …
> Fix research clinical filter buttons

- CHANGELOG.md
- scout/server/blueprints/institutes/controllers.py
- scout/server/blueprints/institutes/views.py
- scout/server/blueprints/variants/templates/variants/utils.html
- tests/server/blueprints/institutes/test_institute_views.py
- Fix #5726
- Fix #5729 
Before: `500 internal error` 
After:
and multiple results:
<details> …
> Fix #5726 - handle pagination on undefined result

- CHANGELOG.md
- scout/adapter/mongo/clinvar.py
> Fixed filtering cases with 'Has ClinVar submissions' checkbox

- .github/workflows/tests_and_cov.yml
- CHANGELOG.md
> Attempt at fixing missing cairo lib

- CHANGELOG.md
- scout/server/blueprints/variants/templates/variants/fusion-variants.html
- Closes #5753 
- Pagination is included in the page and it should work, see [here](https://github.com/Clinical-Genomics/scout/blob/fc88765b7270cc66a91e1e90687759413722f771/scout/server/blueprints/variants/templates/variants/fusion-variants.html#L74)
<details>
1. …
> Display number of fusion vars shown on fusions page

- CHANGELOG.md
- scout/server/blueprints/variant/controllers.py
- scout/server/blueprints/variant/utils.py
- Fix #5752
Looks a lot better, especially visible on e.g. large dups.
Cf the one from the issue after patch:
BNDs, INS and small variants with good ALT alleles were correct, or near correct already, but especially large CNV have quite a distance between end and "end_position". 🙄 It is perhaps time for a display variant class. 😊 
<details>
1. First book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is …
> Fix #5752 - use proper end coord for large SVs in edge gene lookup
