Clinical-Genomics/scout

scout/api/views.py
Some changes to how the inheritance models are being processed:
* sometimes no inheritance model is found
* I found inheritance models in following form: ?Autosomal dominant. So, removed the ?
* I had numerous cases where inheritance models were concatenated with ';'. These are now split up and provided as separate models
* We don't need the 'Isolated cases', so I blacklist them.
=> Improved parsing inheritance models from OMIM

assets/scss/components/_card.scss, scout/core/templates/_macros.html, scout/core/templates/case.html, scout/core/templates/variant.html, scout/models/variant.py
add new macro for external links
move reactome link property to gene ODM
=> show external links per annotated gene

scout/app.py, scout/settings.py
For some reason I removed the logging setup. But that should definitively be added back in there before we lock scout down!
I'm such a mess... :stuck_out_tongue_closed_eyes: 
code review please :smiley: @ingkebil, @moonso
=> Logging setup

Vagrantfile, assets/coffee/components/core-icon.vue, docs/user-guide/pages.md, scout/__init__.py, scout/core/templates/case.html, scout/frontend/templates/index.html, scout/frontend/views.py, scout/templates/layouts/scroll-header.html
=> add HPO disclaimers

CHANGELOG.md, scout/__init__.py, scout/api/views.py, scout/browser/views.py, scout/core/utils.py, scout/core/views.py, scout/helpers.py, setup.py
refactor deprecated get or 404 function
update across modules to handle cases with same id in different institutes
=> Handle multiple cases with the same id

CHANGELOG.md, scout/__init__.py, scout/core/templates/variants.html, scout/core/views.py, setup.py
I'll treat this as a hot fix that takes care of the issues introduced with the latest MIP update
=> Fix filter bugs

scout/core/templates/variant.html, scout/ext/backend/load_mongo.py, scout/ext/backend/utils/get_genes.py, scout/ext/backend/utils/get_mongo_variant.py, scout/models/variant/gene.py, scout/models/variant/variant.py
@robinandeer I fixed the backend so you can merge this when frontend is done.
Please close issue #98 with your commit.
=> Incomplete penetrance

scout/ext/backend/base.py, scout/ext/backend/config_parser.py, scout/ext/backend/load_mongo.py, scout/ext/backend/mongo.py, scout/ext/backend/test_vcf.py, scout/ext/backend/utils/__init__.py, scout/ext/backend/utils/generate_md5_key.py, scout/ext/backend/utils/get_case.py, scout/ext/backend/utils/get_compounds.py, scout/ext/backend/utils/get_genotype.py, scout/ext/backend/utils/get_mongo_variant.py, scout/ext/backend/vcf.py, scout/ext/omim.py, scout/models/case/case.py, scout/models/case/individual.py, scout/models/variant/gene.py, scout/models/variant/transcript.py, scout/models/variant/variant.py
The affected individuals should always appear in the top now
=> Removed import of unicode_literals, fix #157

scout/core/templates/variants.html, scout/models/variant/variant.py
doesn't show indicator for comments if added for another case (locally)
=> fix comments indicator, fix #152

scout/api/views.py
i hope this is the problem but it doesn't make sense that it should've started today..
=> skip report binary in cases api, fix #184

scout/core/templates/case.html, scout/core/templates/variant.html, scout/core/views.py, scout/ext/backend/mongo.py, scout/models/case/case.py
Should just work with the modifications I made
@moonso: I did update the adapter so check that out :)
=> Multiple causative variants

gulpfile.coffee, scout/templates/footer.html, scout/templates/layouts/base.html
I'll merge this now as we need it for working across all branches
Doesn't touch Scout functionality
=> update gulp setup

scout/core/templates/case.html, scout/ext/backend/utils/get_case.py, scout/models/case/case.py
add version to interface
Left to do:
=> add new rank model version attr to case model, fix #150

assets/scss/style.scss, scout/constants.py, scout/core/templates/cases.html, scout/ext/backend/utils/get_case.py, scout/models/case/case.py
=> add analysis type to model and interface, adress #151

requirements/prod.txt, scout/api/views.py, scout/core/templates/case.html, scout/core/views.py, scout/ext/backend/mongo.py, scout/models/phenotype_term.py
+ Link to hpo web
The interface part is done
=> add support for adding omim term in interface

scout/api/views.py, scout/ext/backend/utils/get_mongo_variant.py
=> Fix clinsig

scout/core/templates/variant.html, scout/ext/backend/utils/get_mongo_variant.py, scout/models/variant/variant.py
=> Fix clnsig accs

assets/scss/regions/_case.scss, scout/app.py, scout/core/templates/case.html, scout/core/templates/variant.html, scout/core/views.py, scout/models/case/case.py
Various fixes like showing decimals, highlighting affected samples, causative variant list
=> Feedback fixes

.editorconfig, requirements/prod.txt, scout/core/templates/case.html, scout/core/views.py, scout/models/case/case.py, scout/models/institute.py, scout/settings.py
I think provides basic support now :hamburger: 
It add a link to the default coverage report using information form the gene lists
I'll send a sample report for feedback when merged
=> Sambamba coverage

scout/core/views.py, scout/models/case/gene_list.py
add property to combine name and version of gene panel
=> include display name + version in default coverage report, fix #203

scout/core/templates/gene-panel.html
=> add number of genes to gene panel view, fix #245

scout/core/templates/case.html, scout/core/views.py, scout/ext/backend/event_handler.py, scout/models/variant/variant.py
indicate for pinned/causative variants if sanger has been ordered
this will resolve #252
=> add field "sanger_ordered" to variant model

requirements.txt, scout/ext/backend/mongo.py, scout/login/views.py
In response to #140
Couldn't update to the latest bc of admin interface but it's a first step :stuck_out_tongue_closed_eyes:
=> Mongoengine update

package.json, requirements.txt, scout/core/templates/gene-panel.html, scout/core/templates/variant.html, scout/core/utils.py, scout/core/views.py
Adds links to gene coverage from gene panel page and from variant page
=> add links to gene specific coverage from chanjo

scout/core/templates/variant.html, scout/core/templates/variants.html, scout/ext/backend/utils/get_mongo_variant.py
In response to #102
@moonso: can you check if you populate this field from the VCF?
Also: only show expected column in "clinical" mode
=> show expected inheritance if annotated for a variant

scout/models/case/case.py
This is what you meant, right @robinandeer ?
=> Added index to updated_at. fix #251

requirements.txt, scout/core/templates/gene-panel.html, scout/core/views.py, scout/ext/backend/mongo.py, scout/ext/backend/utils/get_mongo_variant.py, scout/models/case/case.py
I've added an overview for all transcripts in a gene list
You get to it from the gene panel view
=> Transcript cov overview

scout/core/templates/variant.html, scout/core/views.py
Polyphen link
Convert hgnc to upper in server
=> Small fixes

docs/user-guide/using-scout.md
and moved some text into one document.
=> Added information about loqusdb to user-guide

scout/core/templates/_macros.html, scout/core/templates/variants.html, scout/models/variant/variant.py
Please check if it works and update how compounds are handeled in the variants view
=> Changed compound model

assets/scss/components/_header-panel.scss, assets/scss/components/_toolbar.scss, assets/scss/regions/_variants.scss, scout/core/templates/case.html, scout/core/templates/variant.html, scout/core/templates/variants.html, scout/models/case/case.py, scout/templates/layouts/scroll-header.html
remove request research if archived
=> change header color of case to indicate if archived/solved

scout/core/templates/variant.html, scout/ext/backend/utils/get_genes.py, scout/models/variant/transcript.py
Also checks the vep annotation if transcript is canonical
=> Add is_canonical to transcript model

scout/core/templates/variant.html, scout/ext/backend/utils/get_genes.py, scout/ext/backend/utils/get_mongo_variant.py, scout/models/variant/gene.py, scout/models/variant/transcript.py
Parses the Disease_associated_transcript info field of the vcf and adds a list
of manually annotated disease associated transcripts to the gene model
=> Adds disease associated transcripts on gene level

scout/core/templates/variant.html, scout/ext/backend/utils/get_mongo_variant.py, scout/models/variant/variant.py
- Parses spidex annotation from VCF
- Adds spidex score to variant model
- fix #316
=> Adds spidex annotation to backend part

assets/scss/regions/_case.scss, scout/core/templates/variant.html, scout/ext/backend/utils/get_mongo_variant.py, scout/models/variant/transcript.py
- Add is_disease_associated to transcript model
Fix #319
=> Adds disease association on transcript level

assets/scss/style.scss, scout/core/templates/case.html, scout/core/templates/cases.html, scout/models/case/case.py
add shortcut to get missing panel
=> highlight cases affected by panels with missing genes

scout/adapter/case_handler.py, scout/adapter/mongo.py, scout/commands/base.py, scout/commands/cases.py
change logging to be less verbose
=> add "cases" subcommand to rerurn information about cases

scout/adapter/query_handler.py, scout/blueprints/core/forms.py, scout/blueprints/core/templates/variants.html, scout/blueprints/core/views.py, scout/constants/__init__.py, scout/models/variant/variant.py, tasks.py
I send in an int with the query or None
=> add interface part of clinsig search

scout/adapter/gene_handler.py, scout/adapter/variant_handler.py, scout/blueprints/core/templates/variant.html, scout/models/variant/transcript.py, scout/models/variant/variant.py, wsgi_gunicorn.py
=> Integrate the new static models with interface

scout/export/panel.py
@robinandeer , @henrikstranneheim , @emmser export should work when this is merged
=> Fixed problem with exporting panels

scout/adapter/mongo/query.py, scout/constants/__init__.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/sv-variant.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/views.py
=> Added SV variant filter.

scout/adapter/mongo/query.py
Changes 'thousand_genome_frequency' to 'exac_frequency'
=> Fixes type in query

scout/commands/convert.py, scout/server/app.py, scripts/genelist_to_panel.py
Also updates the cli function `convert` to the non mongoengine version of scout
=> Adds script to convert gene lists to gene panels

scout/adapter/mongo/event.py, scout/constants/__init__.py, scout/models/event.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/cases/views.py, tests/adapter/test_event_handling.py
Addresses #423 
Following needs to be added:
=> Adds functionality to handle cohort tags

scout/adapter/mongo/variant.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/variant.html, scout/server/blueprints/variants/views.py
add links and stuff related to frequencies
=> Frequency updates

scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/variant.html
Solves feature request in #523: added Alamut link. 
@parlar: could you test this one on a computer with Alamut http-access enabled and set to the default port 10000? Many thanks!
=> Added Alamut link

scout/server/blueprints/variants/templates/variants/variant.html
=> Added overlapping SV variant type to variant view.

scout/adapter/mongo/variant.py
=> Adds padding of 5000 bases when loading all variants from a gene

scout/adapter/mongo/event.py, tests/adapter/test_event_handling.py
Cases did not change status from solved when unmarking causative.
Fix #575
=> Fixes problem when unmarking causative

scout/adapter/mongo/query.py, scout/commands/base.py, scout/server/app.py
Fix CLINSIG filter - and enable command line debug loglevel without running app in debug mode.
=> Clinsig clinical filter

requirements.txt, scout/server/blueprints/variants/templates/variants/variants.html, scout/server/templates/utils.html
=> Simple comment popover.

scout/commands/setup/setup_scout.py
Solves a typo in `scout setup`
=> Fix bug in setup code

requirements.txt, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/sv-variant.html
Started on #559. SV can now be pinned and marked causative.
=> Sv variant pinning

scout/adapter/mongo/query.py, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/variants.html, tests/adapter/test_query.py
Ok, lets try it this way instead. I've cherry-picked the relevant commits into current master.
=> Fix #577 rebase

scout/server/app.py, scout/server/blueprints/dashboard/__init__.py, scout/server/blueprints/dashboard/templates/dashboard/index.html, scout/server/blueprints/dashboard/views.py, scout/server/templates/layout.html
adds a new view for aggregating data about cases and variants
=> Aggregate dashboard

scout/adapter/mongo/case.py, scout/adapter/mongo/variant.py, scout/commands/load/case.py, scout/demo/643594.config.yaml, scout/parse/case.py, scout/parse/variant/variant.py, scout/server/blueprints/panels/templates/panels/panel.html, scout/server/blueprints/variants/views.py, tests/parse/test_parse_case.py
merge this after the other PRs are in master to revert to the current way the config works
=> Revert family

scout/adapter/mongo/panel.py, scout/constants/__init__.py, scout/constants/acmg.py, scout/parse/case.py, scout/server/blueprints/variants/templates/variants/sv-variant.html
and enable peddy files to be given in the config!
=> Fix small issues

scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/actionbar.html
this better reflects how samples can be part of multiple famlies
=> use sample ids when making link to coverage report

scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/sv-variant.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/variant.html, scout/server/blueprints/variants/templates/variants/variants.html, scout/server/templates/utils.html
..and prepare for adding comments.
=> Fix #628 - show variant tag in SV list.

scout/constants/acmg.py
One. Last. Time. 🕵️‍♀️
Will fix the order of ACMG terms on the variant view.
=> compose acmg map from explicit list

scout/adapter/mongo/case.py, scout/commands/view/case.py
The query for solved cases was not written correct.
Fix #718
=> Fixes error in mongo query

scout/parse/case.py, tests/load/test_load_case.py, tests/parse/test_parse_case.py
Added parse of rank_model_version
Added test of rank_model_version in parsing and loading
=> added parse of rank_model_version to fix #712

scout/server/blueprints/panels/views.py
This should fix the bug #741 , hopefully!
=> fix issue with HGNC id when adding a new gene to a panel

scout/adapter/mongo/query.py, scout/constants/__init__.py, scout/constants/variant_tags.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/variants.html, tests/adapter/test_query.py
New go at solving SPIDEX query without changing db schema, as advertised. 😄
=> SPIDEX query not changing db schema. Fix #693

scout/server/blueprints/variants/templates/variants/variants.html, scout/server/blueprints/variants/views.py
This should fix the issue. The problem was that the HPO genes were not passed to the form by the view.
=> enable hpo filtering for SVs, fix #710

scout/server/blueprints/cases/templates/cases/case_report.html
Fixed a visualization issue. Nothing serious but it looks nicer now when a case doesn't have comments.
=> fixed small visualization issue in case report

scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/cases.html, scout/server/blueprints/cases/views.py
=> Make cases limit changeable.

scout/server/blueprints/cases/templates/cases/case_report.html
Bug fix for the disappeared transcripts for genes in the case report. Realized that they were missing from this page as well!!
=> fixed disappeared transcripts in case report

scout/server/blueprints/cases/controllers.py, scout/server/blueprints/variants/controllers.py
Fixed code for bug when variant passed is a string (variant_id) and not a dictionary
=> bug fix #825

scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/sv-variant.html
Fixed the broken link to ensembl for genes in structural variants
=> fixed missing key for SV ensembl link

scout/server/blueprints/variants/templates/variants/clinvar.html
Shortening as well variant names when the simple_name is longer than 25 characters. Fixed a typo as well.
=> bug fix #853

scout/server/blueprints/cases/templates/cases/case_report.html
Included info on Sanger validation for variants in case report (issue #845) and adding to report only default gene panels (issue #844)
=> Add sanger status and only default panels to case report

scout/server/blueprints/cases/templates/cases/case_report.html
=> improved visibility for SV callers and gene panels in case report

scout/server/blueprints/igv/partial.py, scout/server/blueprints/igv/templates/igv_viewer.html, scout/server/blueprints/igv/views.py
Added the code to send chunks of files to IGV viewer
=> Igv viewer

scout/server/blueprints/panels/views.py
refseq_id was not initialized, easy to fix!
=> Fix missing refseq

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/sv-variant.html, scout/server/blueprints/variants/templates/variants/sv-variants.html
=> dismiss option for SVs

requirements.txt
I don't think that this is the problem, but this way is better I guess
=> fix dependency name, but it should work anyway

requirements.txt, scout/server/blueprints/cases/templates/cases/case_report.html
* Fixed a bug in case report generation for variants which don't have end_chrom key
* Added WeasyPrint dependency
=> fixed a bug and added updated WeasyPrint in requirements

docs/admin-guide/loading-variants.md, docs/user-guide/cases.md
Added a short description of rank model version under "Misc" i Cases document
=> Document rank model

CHANGELOG.md, scout/adapter/mongo/hpo.py, scout/adapter/mongo/index.py, scout/constants/indexes.py, scout/server/app.py, scout/server/blueprints/phenotypes/__init__.py, scout/server/blueprints/phenotypes/controllers.py, scout/server/blueprints/phenotypes/templates/phenotypes/hpo_terms.html, scout/server/blueprints/phenotypes/views.py, scout/server/templates/layout.html
=> made a simple view with search form for HPO terms

CHANGELOG.md, scout/adapter/mongo/panel.py, scout/server/blueprints/panels/controllers.py, scout/server/blueprints/panels/templates/panels/panel.html, scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html, scout/server/blueprints/panels/views.py
A super simple export function to save gene panels to PDF.
=> Export gene panels to PDF

CHANGELOG.md, scout/adapter/mongo/variant_events.py, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/variant.html
=> Makes it possible to reset the Sanger status to "Not validated"

docs/user-guide/variants.md, scout/server/blueprints/cases/templates/cases/case.html
Mostly testing to use the central repo. But does fix #924.
=> Fix #924. Default panel for SV and cancer views.

CHANGELOG.md, scout/adapter/mongo/variant_events.py, scout/server/app.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/cases.html, scout/server/blueprints/cases/views.py, tests/adapter/mongo/test_sanger_validation.py
=> Show sanger situation2

scout/constants/variant_tags.py
=> Capitalise dismiss options. Add an option.

scout/server/blueprints/cases/templates/cases/case_report.html
Improves readability of a long dismissed list.
=> Fix #955 - add gene name to dismissed variants.

.gitignore, CHANGELOG.md, scout/adapter/mongo/panel.py, scout/build/panel.py, scout/commands/load/panel.py, scout/commands/view/aliases.py, scout/load/panel.py, scout/load/setup.py, scout/parse/panel.py, scout/utils/date.py, scout/utils/link.py, scout/utils/requests.py, tests/conftest.py, tests/load/test_load_panel.py, tests/server/conftest.py
=> Adds functionality to load PanelApp genes

requirements.txt
click v7 is fairly recent and differs from the v6
=> Add click dependency to requirements.txt

scout/server/blueprints/cases/templates/cases/case_report.html
Sorting variants present in report by rank!
=> sort report variants by rank (fix #980)

scout/adapter/mongo/variant.py
This is another attempt to speed up the case report creation. Should be tested on stage to check how better it performs (it should help but don't know how much!)
=> Optimized a second query in evaluated_variants

docs/admin-guide/load-config.md, docs/admin-guide/loading.md, scout/build/case.py, scout/demo/643594.config.yaml, scout/models/case/case.py
=> Fix #961: rank_model_version as string.

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html
Fixed a bit the variant view in the report, to accommodate the added info.
=> Added OMIM phenotypes to case report, fix #975

docs/user-guide/cases.md, scout/adapter/mongo/case.py, scout/constants/indexes.py
Friday afternoon fun with Scout. Adds some rather handy candy to the cases search: list cases matching a phenotype, or with some free text word in the case synopsis.
=> Cases with hpo

CHANGELOG.md, requirements.txt, scout/server/blueprints/cases/templates/cases/case_report.html
Improved report code and aesthetics.
=> Improve case report

scout/adapter/mongo/query.py, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/components.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/variants.html, scout/server/blueprints/variants/views.py, tests/adapter/mongo/test_query.py
- Replaces 1000G and ExAC with gnomad filter
- Use gnomad in clinical filter
=> Use gnomad filter

CHANGELOG.md, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/variants.html, scout/server/blueprints/variants/views.py
- Fixed broken download of filtered SNVs
- Created download of filtered SVs (n. max = 500)
- introduced an underscore in field "position+change" in the exported CSV file
fix #952
=> Download of filtered SVs

scout/adapter/mongo/variant.py, scout/commands/export/variant.py, scout/constants/variants_export.py
Made a silly mistake. case should be queried for '_id' and not 'display_name'
=> Query case for '_id' rather than 'display_name'

scout/server/blueprints/cases/templates/cases/cases.html
=> Case search help

scout/adapter/mongo/variant.py, scout/build/variant/gene.py, scout/commands/view/base.py, scout/commands/view/case.py, scout/load/transcript.py, scout/parse/hgnc.py, scout/server/blueprints/variants/templates/variants/components.html, scout/server/blueprints/variants/templates/variants/variant.html
Adds some popup info on the transcripts table at variant level
Fix #1080
=> Display what refseq id that is primary in hgnc

scout/parse/omim.py, scout/server/blueprints/cases/templates/cases/case.html
Fetch "Digenic recessive" from OMIM and show as `DR` wherever applicable
=> Add omim inheritancemodel

CHANGELOG.md, requirements-dev.txt, scout/server/blueprints/variants/templates/variants/sv-variants.html
This way users are forced to input only numbers in "size" field of the SV filter!
=> Number check in variant size filter

scout/constants/so_terms.py
=> Update severe SO_TERMS for clinical filter - SV prompted. Fix #1131

CHANGELOG.md, scout/constants/__init__.py, scout/server/blueprints/variants/controllers.py
I changed the name of the bcftools constant into "Bcftools" otherwise under the gt calls "SAMtools" gets printed twice.
=> show calls from all available callers

scout/server/blueprints/panels/templates/panels/panel.html
It actually seems very possible to use POST for chanjo overview nowadays. Please test with a more complete chanjo db / setup: my local is very demo.
=> Fix #1124 - use POST for overview.

scout/constants/variants_export.py, scout/export/variant.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/views.py, scout/server/config.py, tests/export/test_export_variants.py
=> Expand validated report

scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/views.py
Fix #1150.
Should be tested on stage by looking (why not) at this  variant: /cust003/16068/aa472e7a595ae25d0c499ced46653cb4
=> print an error message when looking for a variant in the wrong case

scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/gene_variants.html, scout/server/blueprints/dashboard/controllers.py, scout/server/blueprints/dashboard/templates/dashboard/index.html, scout/server/blueprints/dashboard/views.py, scout/server/blueprints/login/controllers.py, scout/server/blueprints/variants/templates/variants/components.html
Fixes two known aestethic issues with the gene_variants view.
=> Fix gene variants

scout/commands/update/case.py
@moonso caught you! You can't escape my amazing CLI tests now :D 
Next time write a PR, I know it's a small change, but it broke the function.
=> Fix broken update case command

CHANGELOG.md, CONTRIBUTING.md, README.md
Updated readme and contributing page, describing our branching model system.
**Review:**
=> Branching model

CHANGELOG.md, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/variants/controllers.py
fix #1287
1. Coverage report for patient https://scout-stage.scilifelab.se/cust000/643594-300M has different numbers than coverage stated at the bottom of the downloadable general report: https://scout-stage.scilifelab.se/cust000/643594-300M/pdf_report
1. How to install the branch on clinical-db stage:
```
ssh your.user@clinical-db.scilifelab.se
sudo -iu hiseq.clinical
cd servers/resources/clinical-dbscilifelab.se
bash update-scout-stage.sh check_genreport_panels
```
After installing this branch the numbers on the 2 reports should match
**Review:**
=> Check genreport panels

CHANGELOG.md, README.md, RELEASE.md, requirements-dev.txt
This PR updates release notes on how to build and publish documentation
**Review:**
=> Update release notes

CHANGELOG.md, scout/adapter/mongo/case_events.py, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/blueprints/cases/views.py, tests/adapter/mongo/test_event_handling.py
fix #1327
1. Install the branch locally
1. If the test case is inactive you can make it active by archiving and de-archiving it on the sidebar
1. Assign yourself to the case (sidebar button)
1. When you  If you de-assign yourself (Clark Kent) from the case you should see a confirm window.
1. If you choose 'inactivate' button case will be deactivate
1. Repeat step 2 to activate case again 
1. Reassign yourself to case
1. De-assign yourself from case but this time choose 'do not inactivate' 
1. Case should be still active
1. Make sure that if case is prioritized, when you assign and de-assign yourself to case, you never see the above confirm window and the case stays prioritized.
Take a screenshot and attach or …
=> Confirm inactivate

CHANGELOG.md, scout/utils/convert.py, tests/utils/test_convert.py
There was a problem with converting the string '1.0' to a number
The functionality should be working. Tests are added for the conversion functions.
**Review:**
=> Convert '1.0' to (integer) 1. Fix #1370

docs/admin-guide/annotations.md, docs/admin-guide/load-config.md, docs/admin-guide/loading.md, scout/adapter/mongo/variant.py, scout/adapter/mongo/variant_loader.py, scout/parse/case.py, scout/parse/variant/deleteriousness.py, tests/conftest.py, tests/parse/test_parse_rank_score.py
This PR updates some documentation and docstrings
**Review:**
=> Document with tests

scout/commands/update/genes.py, scout/parse/ensembl.py, scout/utils/link.py, tests/commands/update/test_update_genes_cmd.py, tests/load/test_load_hgnc_genes.py, tests/parse/test_parse_ensembl_exons.py, tests/utils/test_link_genes.py
This PR adds some tests for loading genes without OMIM information or omim api-key
Test coverage should increase
**Review:**
=> Add gene tests

scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/views.py, scout/server/blueprints/variant/controllers.py, tests/server/blueprints/cases/test_cases_controllers.py
Adds tests for cases controllers. Fix #1431 
1. Install on stage
1. Try to open a case report
The case report page should not fail
**Review:**
=> Fixes bug in cases controller. 

scout/build/variant/gene.py, scout/server/blueprints/variants/templates/variants/components.html
1. load a case (e.g. setup a fresh demo)
1. hover over disase gene symbols in the variants table and see that they display OMIM phenotypes
**Review:**
=> Phenotypes popover

CHANGELOG.md, README.md
This PR adds a few more badges to the README.
**Review:**
=> Playing with badges.. X)

scout/adapter/mongo/institute.py, scout/load/institute.py, tests/commands/load/test_load_institute_cmd.py
This PR updates log messages when loading a institute
**Review:**
=> Logs the correct information when loading an institute. Fix #1523

CHANGELOG.md
Forgot to include a fix in the changelog
=> Update CHANGELOG with missing fix

CHANGELOG.md, scout/demo/resources/genemap2_reduced.txt, scout/parse/omim.py, tests/parse/test_parse_omim.py
Fix #1544. 
This should be already working but I'm trying a test with real data-like omim info. Let's see if I manage
1. On a local implementation of Scout run the following command:
`scout --demo update omim --institute cust000 --api-key a_valid_api_key`
The command should run until the end and not return error
**Review:**
=> Fix update omim

CHANGELOG.md, scout/constants/variant_tags.py, scout/utils/link.py
See discussion in the reopened #377.
1. on the variant page, add the new mosaicism tag
**Review:**
=> New mosaicism tag - amendment to Fix #377 

CHANGELOG.md, scout/server/blueprints/variants/controllers.py
1. load research for a full case on stage
1. ensure both SV and SNV research can be opened.
**Review:**
=> Fix #1597: dont use non-existing clinical variants.

scout/parse/variant/frequency.py, tests/parse/test_frequency.py
Fix #1609
This will be tested when uploading a test case from MIP 8.0. 
Unit testing it for now.
**Review:**
=> Added another key GNOMADAF_popmax to parse variant keys

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/clinvar_submissions.html, scout/server/blueprints/cases/views.py
This PR resolves #1636 
1. install on stage
1. follow instructions in #1636 
**Review:**
This is a patch
=> show display name for institute

CHANGELOG.md, scout/adapter/mongo/institute.py, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/templates/overview/institute.html, scout/server/blueprints/institutes/views.py
This PR is a hotfix for institute settings page that doesn't work
1. test on scout stage
**Review:**
=> fix institute settings bug

scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
This PR fixes a quality of life issue that it should be directly visible on case page if research is requested.
1. Install locally
1. Request research on a page and refresh 
**Review:**
=> Show when research is pending. Fix #1454

CHANGELOG.md, scout/parse/case.py, tests/parse/test_parse_case.py
1. tests are testing it
It will now be possible to pass alignment files via the parameter `alignment_path` in load config.
**Review:**
=> Accepts  in load config to pass bam/cram files. Fix #1655

CHANGELOG.md, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/views.py
1. as a non-admin user, open a cancer case and visit the variants page
1. note that it does not activate
1. apply this branch, and note that the same procedure now activates the case.
**Review:**
=> Fix #1702: activate cancer case on viewing variants.

CHANGELOG.md, scout/adapter/mongo/panel.py, scout/commands/load/panel.py, scout/commands/update/omim.py, scout/parse/panel.py, tests/commands/test_convert_cmd.py, tests/commands/update/test_update_omim_cmd.py
This PR adds the functionality to load and update OMIM-AUTO without an omim api-key by using files instead
1. Instal branch
1. run `scout load panel --omim --genemap2 path/to/file --mim2genes path/to/file`
The load functionality should work without api-key
**Review:**
=> Load OMIM from files

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/utils.html
Fix #1724 
1. on sv variants lists (cancer and rd), click on a rank
1. note that you are taken to the corresponding sv variant page
**Review:**
=> Fix #1724 - SV cell rank

CHANGELOG.md, scout/load/all.py
Attempt to load all STRs even if region is requested, as the STR VCF is small and index likely missing.
1. attempt to upload a previously failing case in hasta scout stage with this branch.
**Review:**
=> Fix #1729 - load all STRs also on region load.

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/variant_details.html
bug fix #1730 
1. Install the branch on stage (requires having some actual observations in loqus stage)
1. Make sure that cases where variant was observed are NOT the same as variant's case, repeated all over, like this:
**Review:**
=> Fix observations bug in v4.12

CHANGELOG.md, scout/adapter/mongo/panel.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/views.py, scout/server/blueprints/variant/templates/variant/sv-variant.html, scout/server/blueprints/variant/templates/variant/variant.html, scout/server/blueprints/variant/templates/variant/variant_details.html, tests/server/blueprints/cases/conftest.py, tests/server/blueprints/cases/test_cases_controllers.py
**Prepare**
1. - [x] look at a SV page with local observations active, some cards are scrambled  
1. - [x] Install on stage or local
1. - [x] Repeat above and check that it looks fine
**Review:**
=> Fix problem with scrambled cards in SV view

scout/server/blueprints/variants/controllers.py
Fixes type bug in checking genome build version
=> Correct hgnc 38 mapping

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html
1. how to install it
Check out and install Scout as usual.
- load one cancer config
`scout --demo load case demo/cancer.load_config.yaml  -u`
- load one ordinary config
`scout --demo load case demo/643594.config.yaml  -u`
With two loaded cases, examine and compare them. Note that no Pedigree panel is displayed in the cancer case.
**Review:**
=> Feature remove pedigree 200313

CHANGELOG.md, scout/adapter/mongo/variant.py, scout/server/utils.py, tests/adapter/mongo/test_variant_handling.py, tests/server/test_server_utils.py
This PR fixes a problem when a region VCF can not be created. It adress the same issue as https://github.com/Clinical-Genomics/scout/pull/1806
1. Tests are automated
It should now not be a problem if the VCF does not exist or is not accessible 
**Review:**
=> Handle missing vcfs

CHANGELOG.md, scout/adapter/mongo/case.py, scout/commands/load/case.py
This PR adds as an addendum to #1812, fix #1649. 
1. try re-uploading a case, ideally via stage cg and note the same variant preservation as in #1812.
**Review:**
=> Also allow keep variants on full case reload (cg auto).

CHANGELOG.md, scout/utils/link.py
See #1833. 
1. scout setup
2. note that PRODH has the disease associations of PRODH2
3. install patch, and scout setup
4. note that PRODH now has its own correct disease associations
Before:
After:
**Review:**
=> Alias true

CHANGELOG.md, scout/adapter/mongo/query.py, scout/constants/__init__.py, scout/constants/clnsig.py, tests/adapter/mongo/test_query.py, tests/server/blueprints/variants/test_variants_views.py
=> New revstat filter strings

.github/CODEOWNERS, CHANGELOG.md
Adding codeowners document
**Review:**
=> Added repo codeowners

CHANGELOG.md, scout/server/blueprints/cases/views.py, tests/server/blueprints/cases/test_cases_views.py
This PR  fixes a bug. Fix #1896.
1. on stage, attempt to run phenomizer on a case with phenotypes. Current master will return no custom gene-list. This should.
**Review:**
=> Typo - Fix #1896

CHANGELOG.md, scout/server/blueprints/variant/controllers.py
Bug fix #1903
1. Go to this variant: https://scout-stage.scilifelab.se/cust000/643594-300M/3eb0a3d51fa7fa592e531b37d3cc9c93
1. Click on "Submit to ClinVar"
1. Browser will crash
1. Install this branch and check that the page doesn't crash any more.
**Review:**
=> Clinvar submission: default empty gene list when variant has no genes

.github/workflows/pythonapp.yml, README.md
This PR adds a trigger so that GithubActions run for PRs in forks as well
=> Run workflow on PRs and push

CHANGELOG.md, docs/README.md, docs/blog/new-4.17.md
A Scout blog update, where is also explained how to upload the cytobands (used in a functionality introduced in release version 4.17)
It's not an urgent PR, but it's nice to have it!
**Review:**
=> added a new blog post

CHANGELOG.md, scout/server/blueprints/cases/controllers.py
1. On stage, try to fetch a case chanjo coverage report (that exists), e.g. https://scout-stage.scilifelab.se/cust000/15026-miptest
**Review:**
=> Do verify.

CHANGELOG.md, scout/adapter/mongo/case_events.py, scout/server/blueprints/cases/controllers.py, tests/server/blueprints/cases/test_cases_views.py
Bug fix #1995 
1. Very hard to reproduce since when a rerun is requested then the button disappears, but somehow someone managed to trigger the error
Install on stage and request a rerun for a case
The rerun function should work as expected
**Review:**
=> Existing rerun bug

docs/admin-guide/loading.md, docs/admin-guide/login-system.md, docs/admin-guide/setup-scout.md, docs/user-guide/users.md, scout/server/blueprints/login/views.py
Refreshing docs for user "loading". Also updated old login error message flash.
1. on a demo instance/local instance without OAuth or LDAP, attempt logging in as a non-registered user and note the error message.
**Review:**
=> User load docs refresh.

docs/admin-guide/loqusdb_integration.md
This PR adds documentation related to  #1984
Read it carefully. Are there typos? Does it make sense?
**Review:**
=> Update Documentation For Multiple LoqusDB

CHANGELOG.md
This PR adds a missing line of text in CHANGELOG.
=> Fix changelog 200825

CHANGELOG.md, README.md, docs/admin-guide/server.md
=> Misspelled name..

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/str-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/utils.html, scout/server/blueprints/variants/templates/variants/variants.html
1. check through all variants pages and make sure all pagination buttons (Next, First, final-First) work, and that the corresponding page layout looks ok.
**Review:**
=> Pagination revert

CHANGELOG.md, scout/server/extensions/loqus_extension.py
Viewing variant details with a LoqusDB running in the background. The field total number of cases reflects what is in the LoqusDB.
**Review:**
=> Bugfix loqusdb case count 200903

CHANGELOG.md, requirements-dev.txt
unfreeze mkdocs-material. Don't know why we froze in the first place
**Review:**
=> test unfreeze package

CHANGELOG.md, scout/server/blueprints/variants/controllers.py
=> Missing default panel

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/utils.html, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html
1. look at a BND on the variant view and note if the BP2 button shows and opens IGV on the correct chromosome. Broken on master, works in branch.
**Review:**
=> Fix #2160 - BP2 IGV chrom for variant view

CHANGELOG.md, scout/server/blueprints/genes/templates/genes/gene.html, scout/server/links.py, tests/server/test_links.py
The link to ExAC was broken - or actually going over a slow redirect to their new server - 
Redirected link directly to new page, and also added a link to the corresponding gnomAD page, in waiting for a solution to #1022.
**Review:**
=> Fix pLI link

CHANGELOG.md, scout/commands/delete/delete_command.py
There is currently a bug in printing the deleted variants for each case. This PR is fixing it.
**Review:**
=> Fixed error in delete variants counting when removing vars

CHANGELOG.md, scout/constants/__init__.py, scout/utils/convert.py, tests/utils/test_convert.py
=> Relax three letter conversion

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/cases/templates/cases/phenotype.html, scout/server/blueprints/cases/views.py
Fix #2225, read discussion there to have an idea of what this is fixing
1. Install this branch locally and add/remove OMIM gene IDs in the OMIM Genes panel on case page:
1. Make sure that the functionality of adding OMIM phenotypes is not disrupted.
**Review:**
=> Allow users to add any numerical value in case page, OMIM genes panel

CHANGELOG.md, requirements.txt
This PR adds a functionality or fixes a bug. fix #2252
**Review:**
=> Freeze coloredlogs to save tests

CHANGELOG.md, scout/server/blueprints/cases/static/case_images.js, scout/server/blueprints/cases/templates/cases/case.html
Add bug fix. Jinja function `tojson` crashed when given `undefined`. This patch removes call to `tojson` as it is no longer in use.
```
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case.html", line 456, in block "scripts"
{{case.chromograph_prefixes|tojson}},
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/init.py", line 376, in tojson_filter
return Markup(htmlsafe_dumps(obj, **kwargs))
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/init.py", line 290, in htmlsafe_dumps
dumps(obj, **kwargs)
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/init.py", line 211, in dumps
rv = _json.dumps(obj, …
```
=> Bugfix: Chromograph_prefixes to json. ref: #2265

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
1. open the igv view, possibly with different variants and track sets - look around for anomalies
**Review:**
=> Update IGV.js to 2.7.4

CHANGELOG.md, README.md
This PR adds to the README file an updated description of the Google OAuth 2.0 connection parameters. Fix #2283 
Nothing to test, it's a documentation fix.
**Review:**
=> Fix Google OAuth 2.0 login demo params in README file

CHANGELOG.md, docs/admin-guide/README.md, docs/admin-guide/breaking.md, requirements-dev.txt
This PR adds a page to the docs.
1. open page and confirm readable
**Review:**
=> Fix #2318 - breaking changes page

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/clinvar.html
Fixes a couple of problems in the ClinVar submission page.
- For variants having multiple genes for instance this one: https://scout-stage.scilifelab.se/cust003/15001/01fc608966a1fb60233a119eb651de00
- for all variants, since one of the inheritance models select options was broken
- PS: this PR is not fixing #2322,  because so far I haven't understood why the submission for that variant (same variant as in this PR) is not working.
1. Check the difference in a ClinVar submission between master and this branch for the variant above
**Review:**
=> Fix ClinVar submission inheritance option and multiple gene display

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html, scout/server/blueprints/alignviewers/views.py, tests/server/blueprints/alignviewers/test_alignviewers_views.py
This PR tempfixes a bug.
**Review:**
=> Revert CORS anywhere

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/utils.html
Negative IGV coordinates causes view to hang. See PR #2356 for discussion.
**Review:**
=> Do not do negative IGV coords.

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
New update from IGV fixing our issues! Neato!
**Review:**
=> IGV.js 2.7.5 - fix #2170 fix #2323

CHANGELOG.md, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/components.html
=> Show clinvar on variant s

CHANGELOG.md, scout/utils/scout_requests.py
=> Update HPO dl URL

CHANGELOG.md, scout/constants/variant_tags.py
Add a VUS manual variant tag.
**Review:**
=> Fix #2379 - include VUS variant tag

CHANGELOG.md, scout/adapter/mongo/case.py
Fix #2405 
1. switch to this branch on a local instance of Scout or on a stage server
1. Assign yourself to a case 
1. Search cases by assigned user name, user surname or full name
All the types of searches should return results
**Review:**
=> Search cases by assignee name, surname of full name

CHANGELOG.md, scout/server/links.py
Thanks @dnil for the previous review. Immediately after I made it available for review I've realized that this is a better solution, sorry!
**Review:**
=> fix to the fix (missing end_chrom)

CHANGELOG.md, Dockerfile, README.md, docs/README.md, mkdocs.yml, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html, scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html, scout/server/blueprints/panels/templates/panels/panels.html, scout/server/templates/layout_bs4.html
This PR updates the docs URL in README
Link should work
=> Update docs url

CHANGELOG.md, docs/admin-guide/annotations.md, tests/parse/conftest.py, tests/parse/test_parse_transcripts.py
Expand documentation including the gnomAD field.
1. No test, it's documentation
**Review:**
=> Add gnomAD annotation field in admin guide

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/institutes/templates/overview/clinvar_submissions.html
Fix #2461 - column headers.
**Review:**
=> ClinVar cosmetics

CHANGELOG.md, scout/adapter/mongo/case.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/views.py, scout/server/blueprints/variants/views.py, scout/server/utils.py, tests/build/test_build_variant.py, tests/commands/conftest.py, tests/conftest.py
This PR refactors a few files, mainly with code duplication, to satisfy the most glaring hotspots that CodeFactor keeps complaining about every time these files are touched.
1. check touched functionality and test results to ensure it is still as before
**Review:**
=> Codefactor hof

CHANGELOG.md, scout/server/blueprints/institutes/forms.py, scout/server/blueprints/institutes/templates/overview/phenomodel.html, scout/server/blueprints/institutes/templates/overview/phenomodels.html, tests/server/blueprints/institutes/test_institute_views.py
=> Feature: Phenomodels language adjustment (#2337)

.github/workflows/linting_and_fixing.yml, CHANGELOG.md
This PR removes the somewhat naive attempt at a modifying iSort action. We may return to that at some point, but checks only for now.
**Review:**
=> iSort check only

.github/workflows/build_and_publish.yml, CHANGELOG.md
This PR adds a functionality: auto deploy docs on release
1. how to test it: release a release and check that the docs are updated (or test by moving it to trigger on push once if it looks good to the reviewer?)
**Review:**
=> Deploy docs action

CHANGELOG.md, scout/server/blueprints/variants/forms.py
Fix #2563
1. Try to filter variants of all type by chromosome and chromosomal intervals
2. All searches should work fine
**Review:**
=> Fix cancer variants filter by chromosome

CHANGELOG.md, scout/adapter/mongo/hgnc.py, scout/commands/load/panel.py, scout/server/blueprints/alignviewers/controllers.py, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/forms.py, tests/adapter/mongo/test_diagnosis_handler.py, tests/adapter/mongo/test_matchmaker.py, tests/adapter/mongo/test_variant_handling.py, tests/load/test_load_variant.py, tests/server/blueprints/alignviewers/test_alignviewers_controllers.py, tests/server/blueprints/cases/test_cases_views.py, tests/server/blueprints/institutes/test_institute_views.py, tests/server/blueprints/managed_variants/test_managed_variants_views.py, tests/utils/test_utils_matchmaker.py
Hoping to fix #2565 
1. Install on clinical-db stage and go to a case with bam files (this one for instance: https://scout-stage.scilifelab.se/cust000/643594-300M)
2. Go to the igv view of any variant (no chrom variants!) and look for the gene from case described in #2565 
**Review:**
=> Upgrade igv.js to version 2.8.1

.github/workflows/build_and_publish.yml, CHANGELOG.md
1. simply wait for next release? 
**Review:**
=> Fix publish docs include

CHANGELOG.md, scout/adapter/mongo/query.py, scout/constants/query_terms.py, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/utils.html, tests/adapter/mongo/test_query.py
Fix #2591
Introduced a couple of checkboxes to filter cancer variants and get those in ClinVar and Cosmic:
1. Switch to this branch locally and load demo cancer case
2. Filter using the new checkboxes
**Review:**
=> Filter cancer variants by "is in ClinVar" and "is in Cosmic"

.wokeignore, CHANGELOG.md, docs/user-guide/panels.md, scout/demo/643594.config.yaml, scout/demo/643595.config.yaml, scout/demo/ADM1059A1.test.cgh, scout/demo/ADM1059A2.test.cgh, scout/demo/ADM1059A3.test.cgh, scout/server/blueprints/variant/templates/variant/variant.html, tests/adapter/mongo/test_event_handling.py, tests/adapter/mongo/test_panel_handler.py, tests/build/test_build_case.py, tests/commands/delete/test_delete_cmd.py, tests/commands/test_base_command.py, tests/conftest.py, tests/load/test_load_report.py, tests/server/blueprints/cases/conftest.py, tests/server/blueprints/cases/test_cases_controllers.py, tests/server/blueprints/cases/test_cases_views.py, tests/server/blueprints/institutes/test_institute_controllers.py, tests/server/blueprints/login/test_views.py, tests/update/test_update_panel.py
Fix code as suggested by woke (fix #2604)
**Review:**
=> Fix woke issues

CHANGELOG.md, scout/server/blueprints/institutes/views.py
Mark an old STR causative e.g. on stage: note crash with master, and working with patch:
**Review:**
=> Fix sorted lambda for old STRs

CHANGELOG.md, scout/constants/__init__.py
This adds GATK as a caller for SV and cancer SV variants
**Review:**
=> Added GATK to SV/ cancer SV list

CHANGELOG.md, scout/constants/indexes.py
=> Add a new index in hgnc collection for gene_symbol

CHANGELOG.md, scout/server/blueprints/variants/controllers.py
Some changes I didn't manage to add to a previous PR since I've merged it by mistake!
**Review:**
=> Clearer warnings 4 gene search - 2 -

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
1. zoom and scroll a bit to confirm that gene symbol labels follow the updating view
**Review:**
=> Update IGV to 2.8.5 - Fix #2592

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/variant/templates/variant/sv-variant.html
Updated the url for Gens buttons be compatible with Gens v2
**Review:**
=> Updated Gens url to support Gens v2.0

CHANGELOG.md, docs/admin-guide/load-config.md
This PR adds a functionality by updating documentation. 
+ correct indentation levels
+ remove duplicate
Install patch.
`Load-config.md` should be updated with the new config parameters *rna_coverage_bigwig* and *splice_junctions_bed*.
**Review:**
=> Update Load Config Documentation

CHANGELOG.md, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/views.py, tests/server/blueprints/cases/test_cases_controllers.py, tests/server/blueprints/cases/test_cases_views.py
=> Case report API

CHANGELOG.md, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/views.py
- Fix #2776
- Cleaner case view by moving code to controller
1. Install the branch on stage
2. Go to this case: https://scout-stage.scilifelab.se/cust101/F0007523-2
**Review:**
=> Bug fix #2776

CHANGELOG.md, scout/constants/__init__.py
This PR adds a functionality - DeepVariant caller tags.
**Review:**
=> Add DeepVariant caller

CHANGELOG.md, scout/commands/update/genes.py
Fix #2801 
1. Locally, run the command `scout --demo update genes` on master branch. The command should fail
2. Switch to this branch and repeat: the command should update genes
**Review:**
=> Do not remove update genes command tempdir before resource files are parsed

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/cancer-variant.html, scout/server/blueprints/variant/templates/variant/components.html, scout/server/blueprints/variant/templates/variant/variant.html, scout/server/config.py
This PR also merges changes from #2809 from @northwestwitch. Sorry about the poor coordination: I'll tentatively blame the GitHub interface, but this user may be slightly at fault as well. 😊 
**Review:**
=> Reachable alamut button

CHANGELOG.md, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/static/form_scripts.js, scout/server/blueprints/variants/views.py, tests/server/blueprints/variants/test_variants_views.py
Fix #2817 
1. Switch to this branch locally
2. Open filter form in STRs variants page
3. Click on Filter and Export
**Review:**
=> Fix STR variantS export

CHANGELOG.md, scout/commands/load/panel.py
Fix #2865 
1.  Load an OMIM gene panel using either pre-downloaded genemap2 and mim2genes or by providing an OMIM API key
**Review:**
=> Fixed broken scout load OMIM command

CHANGELOG.md, scout/build/variant/variant.py, scout/models/variant/variant.py, scout/server/blueprints/variant/templates/variant/variant_details.html, scout/server/config.py
Temporary fix #2169 and fix #2901 until we can parse this number from the real data
1. Install the branch locally 
**Review:**
=> Remove the hardcoded number of total individuals from the variant's old observations panel

CHANGELOG.md, scout/adapter/client.py, scout/adapter/mongo/base.py, scout/commands/base.py, scout/commands/serve.py, scout/server/app.py, scout/server/config.py, tests/commands/test_base_command.py
Fix #2906
- Fixing the the connectivity using .py config files
- Enabling the connectivity using .yaml config files
- Enabling the connectivity using custom connection strings from the cli
**BEFORE TESTING**
- Launch the [replica set](https://hub.docker.com/repository/docker/northwestwitch/mongo4.4-replica-set)
- **wait 30 seconds**
**How to test ----> connect with .PY FILES**:
1. Edit the default config.py file and uncomment the parameter **MONGO_URI**
2. Try to setup a demo instance (`scout setup demo`) and run the web app (`scout --demo serve`) 
3. **Comment that line again before testing the next steps**
---
**How to test ----> connect with .YAML FILES**:
1. Create a .yaml file with this line:
```
mongo_uri : mongodb://127.0.0.1:27011,127.0.0.1:27012,127.0.0.1:27013/?replicaSet=rs0&rea …
```
=> Connect to a MongoDB replica set with .yaml config file and fix connectivity with .py configs

CHANGELOG.md, scout/constants/variant_tags.py, scout/server/blueprints/cases/templates/cases/case_report.html
1. Install on clinical-db
2. Check that general report for this case works: https://scout-stage.scilifelab.se/cust003/15001/
**Review:**
=> Fix general report crashing because of missing key/values

CHANGELOG.md, scout/adapter/mongo/case.py
Fix #2967 
1. Locally from master branch, run `scout --demo load case scout/demo/cancer.load_config.yaml`
2. Switch to this branch and run the same command
**Review:**
=> Fix broken load case when case has no custom images

CHANGELOG.md, docs/admin-guide/loqusdb_integration.md
Fix #2970 
Improve documentation on how to integrate loqusdb instances (executable instance or REST API call) into scout.
1. Read the proposed changes in the documentation and see it makes sense.
**Review:**
=> Improve loqusdb integration documentation - including loqusdbapi connections -

CHANGELOG.md, scout/server/extensions/loqus_extension.py
1. check loqus sv freq on a variant - note it generally missing, even if the case in question is loaded
2. apply fix and see the variant reappear if loaded
Before:
After:
**Review:**
=> Test and fix loqusdbapi sv call 

CHANGELOG.md, scout/adapter/mongo/query.py
Fix variants filtering using the Decipher checkbox (fix #2993)
1. Locally, on master branch, go to SVs variants and filter by clicking on the Decipher checkbox
2. The page should crash with the error described in #2993 
3. Repeat from this branch
**Review:**
=> Fix variants filtering using Decipher criterion

CHANGELOG.md, scout/constants/indexes.py
This PR adds a functionality - index on disease term genes
**Review:**
=> Fix #3020 - add index

CHANGELOG.md, scout/adapter/mongo/panel.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/views.py
This PR adds a functionality or fixes a bug (fix #3035).
**Review:**
=> Cancer gene symbols check - fix #3035

CHANGELOG.md, scout/constants/acmg.py
=> Fix ACMG tooltip BP6

.github/workflows/build_and_publish.yml, .github/workflows/server_stage_docker_push.yml, CHANGELOG.md, Dockerfile-server, README.md, docker-compose.yml, docs/admin-guide/server.md, scout/server/config.py, scout/server/extensions/mongo_extension.py, tests/server/test_links.py
- Created a Dockefile to be used to serve the dockerized app in production
- Modified the code to collect database params specified as env vars
- Created a GitHub action that pushes the Dockerfile-server image to scout-server-stage every time a PR is opened
1. Run docker-compose up and make sure the demo app is served on **localhost:8000**
**Review:**
=> Create a Dockerfile for serving the app via gunicorn - with GitHub action

CHANGELOG.md, scout/adapter/mongo/query.py, scout/server/blueprints/institutes/forms.py, scout/server/blueprints/institutes/templates/overview/gene_variants.html, scout/server/blueprints/institutes/views.py
Install on cg-vm1 and go to this page for an institute.
1. Make sure the page doesn't hang
2. Make sure the HGNC symbol is required to run searches
3. Make sure searches work
**Review:**
=> Fix gene variants page timeout issue

CHANGELOG.md, Dockerfile, Dockerfile-server
Tentative fix to #3094 and #3093. This fixes also the download of the verified variants.
1. Install on cg-vm1 and check that MYT reports and validated vars files can be downloaded
**Review:**
=> Tentative fix to file downloads issue

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Adds instructions on how to deploy test branches to cg-vm1 
**Review:**
=> Instructions on how to deploy a branch to CG-VM1 in a collapsible section of PR template

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
There are some new good fixes in igv.js, so let's give it a shot.
<details> …
=> Update igv.js to 2.10.5

CHANGELOG.md, scout/server/app.py, tests/commands/update/test_update_groups_cmd.py
<details>
</details>
1. arrange a crash
The …
=> Error email subject

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
A small fix to the instructions to deploy on cg-vm1. 
**Review:**
=> Fix pull request template instructions on how to deploy to test server 

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/cases/views.py
Tentative fix #3141 
<details>
</details>
1. Download the general report from a RD case with no pedigree …
=> Attempt at fixing #3141

.github/workflows/tests_and_cov.yml, CHANGELOG.md
Fix #3157 
<details>
</details>
The …
=> Fix unable to fetch libs during Docker build in GitHub actions

CHANGELOG.md, requirements.txt
This PR (temporarily) freezes the version of WTForms to avoid issues displaying some numbers from the database.
<details> …
=> Freeze WTForms

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/cases/views.py, scout/server/templates/report_base.html
- Fix #3167 Sample names not fitting table
- Fixed an error in the report page due to  jquery not imported
Modifies the report from this:
to this:
<details>
1. Make sure the branch is deployed: …
=> Slightly smaller and improved layout of content in case PDF report

CHANGELOG.md, scout/server/blueprints/cases/controllers.py
<details>
</details>
1. try cases with and without working …
=> Fault tolerance chanjo

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html
fir #3210 
From this:
To this:
<details>
</details> …
=> Broader synopsis in general report, much better :D

CHANGELOG.md, scout/constants/case_tags.py, scout/server/blueprints/cases/templates/cases/case_report.html
Fix #3216
From this:
To this:
<details>
</details> …
=> Added OMIM terms and individual-specif info on case repo phenotypes

.github/workflows/tests_and_cov.yml, CHANGELOG.md
Fix #3237 
<details>
</details>
The …
=> Update Codecov GitHub action to v.2

CHANGELOG.md, codecov.yaml
Tentative fix #3248 
<details>
</details>
1. Check that issue #3248 is solved in GitHub actions
**Expected …
=> Remove flags from codecov config file

CHANGELOG.md, security.md
Fixes partially #3250 
<details>
</details>
**Expected …
=> Security policy page

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html, scout/server/links.py
Fix #3254. IARC database has been moved elsewhere!
<details>
</details>
1. how to test it, possibly with real …
=> Fix IARC link

CHANGELOG.md, docs/user-guide/cases.md, scout/server/blueprints/cases/templates/cases/case.html
<details>
</details>
1. how to test it, possibly with real …
=> Chromograph docs link - Fix #3255

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html
Fix #3267
<details>
</details>
The …
=> Same MARRVEL PR, new branch

CHANGELOG.md, docs/admin-guide/annotations.md, scout/server/blueprints/variant/templates/variant/variant_details.html
=> Spliceai link - Fix #3256

CHANGELOG.md, scout/server/blueprints/login/views.py
Tentative fix #3288, inspired by https://github.com/authlib/demo-oauth-client/issues/20 and  https://github.com/authlib/demo-oauth-client/issues/21 
<details>
1. Make sure the branch is deployed: …
=> Fix broken Google login

CHANGELOG.md, requirements.txt
OR
<details>
1. Make sure the branch is …
=> Unfreeze Werkzeug since Flask_login v.0.6 with bugfix has been released

CHANGELOG.md, scout/server/blueprints/genes/controllers.py, scout/server/blueprints/genes/templates/genes/genes.html, scout/server/blueprints/genes/views.py, scout/server/utils.py, tests/server/test_server_utils.py
Fix #3234
Before:
After: 
<details>
</details>
**Expected …
=> Show number of documents and date of last update on genes page

CHANGELOG.md, requirements.txt, scout/server/app.py, scout/server/blueprints/alignviewers/controllers.py, scout/server/blueprints/cases/views.py, scout/server/blueprints/variant/views.py, scout/server/blueprints/variants/views.py, scout/server/extensions/ldap_extension.py, scout/server/utils.py
Fix the 10 code vulnerabilities flagged by SonarCloud (Fix #3330)
<details>
</details>
1. 
**Expected …
=> Fix sonarcloud vulnerabilites

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/utils.html
Point the Alamut API link to the current version:
<details>
</details>
**How to …
=> Update Alamut API docs link

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/templates/overview/institute_settings.html
Fix #3351 
<details>
</details>
1. Check that institute select is populated with sorted institute options …
=> Fix gene panels' select in institute settings

CHANGELOG.md, scout/server/blueprints/genes/templates/genes/gene.html, scout/server/blueprints/variant/templates/variant/components.html, scout/server/links.py
<details>
</details>
1. how to test it, possibly with real …
=> Fix #3366 - add GenCC links

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/gene_panel.html, scout/server/blueprints/cases/templates/cases/utils.html, scout/server/blueprints/variant/templates/variant/variant_details.html
- Fix #3370 
- and this, on case page:
<details>
</details>
**Review:**
=> Fix invisible links and extra parenthesis

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
OR
<details>
1. Make sure the branch is …
=> Expand testing instructions

CHANGELOG.md, scout/server/links.py, scout/utils/ensembl_rest_clients.py, tests/server/blueprints/alignviewers/test_alignviewers_controllers.py, tests/server/blueprints/variant/test_variant_views.py, tests/utils/test_ensembl_rest_clients.py
fix #3327
Use another GRCh37 archive to update genes instead of the official one that returns wrong lines -it's the same genome build v 75 anyway! -
<details>
1. `ssh …
=> Fixed updating genes in build 37

CHANGELOG.md, scout/server/static/bs_styles.css
=> Fix #3409 - recolour visited links

CHANGELOG.md, scout/server/static/bs_styles.css
Tentative fix #3415 
How do they look like this?
<details>
1. (optional) Find out …
=> Changed color of visited links

CHANGELOG.md, scout/server/static/bs_styles.css, scout/server/templates/utils.html
Fix #3427 
Light mode - changes comments style from this:
To this;
Dark more, from this:
To this:
<details>
1. `sudo -iu …
=> More compact and visible comments

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/causatives.html
=> Fix #3421 - drop causatives institute sidebar

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/cases.html
Fix #3439 
Test with cases from [this cust](https://scout-stage.scilifelab.se/cust087/cases)
<details>
1. …
=> Fix visibility of PANEL-UMI tag in cases page

CHANGELOG.md, scout/server/blueprints/diagnoses/templates/diagnoses/omim_terms.html, scout/server/blueprints/phenotypes/templates/phenotypes/hpo_terms.html
The dataTables generated tables get assigned even-odd classes, which are now coloured black for us.
Its only a couple of cells that show plain text. I'll just override them:
<details>
- Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server …
=> Override some of the even-odd color for dataTables

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py
Some more variant specific events.
<details>
1. `ssh …
=> Fix #3455 - update variant specific events

CHANGELOG.md, scout/adapter/mongo/variant.py, scout/export/variant.py
- Fix downloading validated variants when a STR is validated (fix #3485)
- Download only true validated variants (fix #3487)
<details> …
=> Fix funct anno in export and download only true validated vars, once

CHANGELOG.md, scout/server/blueprints/variant/views.py
=> Remove str variant endpoint

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html
This PR adds a functionality: spacing between card elements in case view.
I though this would be a simple one line addition to #3533, fixing spacing between elements.
Before:
After:
<details>
1. Log out from …
=> Fix Spacing Between Panel Elements

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html
=> Fix region|function freq. overlapping in SV variants cells

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html
Addressing [this comment](https://github.com/Clinical-Genomics/scout/issues/3581#issuecomment-1241693658)
<details>
1. `sudo -iu …
=> More evident link to gene coverage in Var page

CHANGELOG.md, scout/adapter/mongo/case.py, scout/server/blueprints/institutes/controllers.py
Attempt at fix #3608 
<details> …
=> Avoid duplicate analyses and showing cases as rerun when first upload failed

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/cases.html, scout/server/blueprints/institutes/templates/overview/utils.html
=> Add Type of analysis on Validated and Causatives pages

CHANGELOG.md, scout/constants/igv_tracks.py
Fix https://github.com/Clinical-Genomics/scout/pull/3625#issuecomment-1274181992
I should have tested another time before merging!
<details>
1. `ssh …
=> Fix typo in dbVar Clinvar track hg19

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
=> Update pax instructions

CHANGELOG.md, scout/adapter/mongo/case.py
While writing the list in #3658, I've realized that I forgot to include the condition of cases with `gene_fusion_report_research` in #3651
<details> …
=> Search cases with research RNA data

CHANGELOG.md, scout/constants/clinvar.py, scout/server/blueprints/clinvar/templates/clinvar_submissions.html, scout/server/blueprints/clinvar/templates/multistep_add_variant.html
Fix #3642 - it's mid November!
<details> …
=> Remove Assertion Method fields from ClinVar submission files

CHANGELOG.md, requirements-dev.txt, requirements.txt, scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
Reverts Clinical-Genomics/scout#3670
Accidentally got the 4.61 version PR on there anyway.
=> Revert "Dashboard labels"

CHANGELOG.md, scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
Same as #3670:
<details>
1. Start the …
=> Fix dashboard search labels again.

CHANGELOG.md, README.md
=> Some more badges for README

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
This PR adds documentation.
1. use test instructions on hasta
**Review:**
=> add hasta test instructions to PR template

CHANGELOG.md, scout/constants/clinvar.py, scout/server/blueprints/clinvar/controllers.py
=> Fixed missing Condition ID type field in exported ClinVar Variant.csv

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar_submissions.html
=> Update status of a ClinVar submission with no name

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/phenotype.html
Fix #3700 
Main branch:
This branch:
<details>
1. Start the scout service with the …
=> Align OMIM diagnoses with delete diagnosis button on case page

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Fix #3717 
From this:
To this:
<details> …
=> Add spacing on Beacon and MME items on case sidebar

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar_submissions.html
Fix #3725 
I've separated the form elements into 2 distinct forms
<details>
1. Start …
=> Fix update CliVar submission ID manually

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar_submissions.html
=> Updated Clinvar howto

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/phenotype.html, scout/server/blueprints/cases/views.py, scout/server/extensions/phenopacket_extension.py
=> Fix 2 errors in phenopacket import

CHANGELOG.md, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/case.html
=> Fix adding case to a group without valid case name

CHANGELOG.md, docs/user-guide/acmg-criterias.md, scout/adapter/mongo/acmg.py, scout/build/acmg.py, scout/models/acmg_evaluation.py, scout/server/blueprints/variant/controllers.py, scout/server/blueprints/variant/templates/variant/acmg.html, scout/server/blueprints/variant/views.py, scout/utils/acmg.py, tests/utils/test_acmg.py
A tentative fix for adding ACMG term modifiers. There are a some things left (tests etc), but it is late and it is also working at the moment so pushing a draft.
This adds a modifier option to the classification terms so that e.g. this Very Strong, directly Pathogenic with another Strong:
When modified to Moderate evidence gives a Likely Pathogenic verdict.
See documentation update for more on what it is supposed to do.. 😄
<details> …
=> ACMG modifiers - fix #2463

CHANGELOG.md, requirements.txt, scout/server/app.py
=> Fix #3761 - really by @TkTech

CHANGELOG.md, scout/server/blueprints/variant/views.py
Fix #3764
Before:
After:
<details> …
=> Fix manual rank message 

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/components.html
Fix #3768 
Main branch:
This branch:
<details>
1. Start the scout service with the …
=> Fix gene and functanno visibility on Causatives/Validated page

CHANGELOG.md, scout/adapter/mongo/institute.py, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/forms.py, scout/server/blueprints/institutes/templates/overview/utils.html, scout/server/links.py, tests/server/test_links.py
=> Add Alamut Institute in Institute settings and use it in Alamut requests

.gitignore, CHANGELOG.md, scout/server/blueprints/panels/templates/panels/panel.html
Fix #3779 
This was an easy fix, so let's have it in the next release!
<details>
1. …
=> Fractional values in gene panel version

CHANGELOG.md, scout/server/blueprints/clinvar/controllers.py
Try to add a variant to a clinvar submission without selecting any tx/hgvs. (fix #3785)
<details> …
=> FIx submitting SNVs to ClinVar without specifying tx and HGVS

CHANGELOG.md, scout/constants/acmg.py, scout/server/blueprints/variant/templates/variant/acmg.html
This PR adds a functionality. Add some requested docs and tool links for ACMG classification strength modification.
<details> …
=> ACMG doc links for strength modification

CHANGELOG.md, scout/server/links.py, tests/server/test_links.py
=> Fix Beacon links to support variants in build 38

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/sanger.html
=> Fix #3826 - Sanger Cancel order modal close

CHANGELOG.md, scout/adapter/mongo/event.py, scout/models/institute.py, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/templates/utils.html
=> Fix #3827 - show comment badges on general report related comments

CHANGELOG.md, docs/admin-guide/panelapp_panels.md
Created the PanelApp green genes howto (fix #3821)
<details> …
=> PanelApp green genes admin howto

CHANGELOG.md, scout/models/variant/variant.py, scout/server/blueprints/cases/templates/cases/individuals_table.html, scout/server/blueprints/variant/templates/variant/sv-variant.html
- `individual_id`-parameter to both Gens links.
- Changes the name of the `sample_id`-field in the `gt_call`-model to the correct `individual_id`. https://github.com/Clinical-Genomics/scout/blob/6ae6114d3fdf2e88b55d61e799f4cfedc6d5e8b8/scout/parse/variant/genotype.py#L76
<details>
1. `sudo -iu …
=> Gens individual

CHANGELOG.md, requirements.txt, scout/__init__.py, scout/constants/__init__.py, scout/demo/__init__.py, scout/demo/resources/__init__.py, scout/load/report.py, scout/resources/__init__.py, scout/utils/handle.py
This was one of the most tedious PRs ever. I regretted taking the issue as soon as I started! 😆 
Fix #3844 
<details> …
=> Fix deprecated pkg resources

CHANGELOG.md, scout/adapter/mongo/event.py, scout/commands/export/mitochondrial_report.py, scout/commands/export/variant.py, scout/commands/view/panels.py, scout/constants/__init__.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/views.py, scout/server/blueprints/panels/controllers.py, scout/server/blueprints/panels/templates/panels/panel.html, scout/server/blueprints/panels/views.py, tests/server/blueprints/panels/test_panels_views.py
=> Export panels in TXT format from the gene panel page

CHANGELOG.md, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/utils.html, scout/server/blueprints/variants/templates/variants/variants.html, scout/server/blueprints/variants/views.py
Allow temporarily dismissing (until page reload) dismiss bar.
<details> …
=> Fix #3792 - thin and allow closing dismiss bar

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/components.html
Fix #3861 
With this branch:
<details> …
=> Fix svs genes visibility

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/utils.html, scout/server/blueprints/variants/templates/variants/variants.html
I took the liberty of harmonising the filters form footer on the SV page. But the main thing was a missing argument in a few of the macro calls.
<details>
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman …
=> Fix SV filter form layout

CHANGELOG.md, requirements.txt, scout/__init__.py
=> Fix #3870 - require importlib metadata explicitly

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html
=> Fix typo for str variants with comment in general report

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/sv-variant.html
=> Gens structural variant page link individual id

CHANGELOG.md, scout/server/blueprints/cases/views.py, scout/server/utils.py
Tentative fix #3897 
<details> …
=> Speed up institutes loading

CHANGELOG.md, docs/blog/new-4.67.md, scout/adapter/mongo/query.py, scout/constants/filters.py, scout/constants/query_terms.py, scout/constants/so_terms.py, tests/adapter/mongo/test_query.py
=> Clinical filter SV local old obs and polypyrimidine annotation severe

CHANGELOG.md, scout/adapter/mongo/case.py, scout/commands/delete/delete_command.py, scout/constants/indexes.py, scout/models/case/__init__.py, scout/server/blueprints/institutes/controllers.py, tests/adapter/mongo/test_case_handling.py, tests/conftest.py
=> Optimise cases

CHANGELOG.md, requirements.txt
=> Freeze werkzeug to version<2.2.3

CHANGELOG.md, scout/server/blueprints/cases/views.py
=> Show empty institutes

CHANGELOG.md, scout/server/blueprints/cases/controllers.py
=> Fix #3923 - default panel on pinned sv report

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
=> Fix #3926 - update igv.js to v2.15.6

.github/workflows/build_and_publish.yml, .github/workflows/linting_and_fixing.yml, .github/workflows/linting_only.yml, .github/workflows/server_stage_docker_push.yml, .github/workflows/tests_and_cov.yml, .github/workflows/vulture.yml, CHANGELOG.md, Dockerfile, Dockerfile-server
=> For starters, fix action versions

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py
=> Restore rank model versions on causatives/verified pages

CHANGELOG.md, requirements.txt, scout/commands/serve.py
=> explicitly declare and freeze tornado for livereload

CHANGELOG.md, scout/server/templates/bootstrap_global.html
Fix #3964.
Before:
After:
(note e.g. the vials and comments bubbles)
<details> …
=> FontAwesome resource integrity changed.

CHANGELOG.md, scout/adapter/mongo/case.py
Tentative fix #3967 
<details> …
=> Force update variants count on case re-upload

CHANGELOG.md, scout/server/app.py, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/templates/overview/gene_variants.html, scout/server/blueprints/variants/templates/variants/components.html, scout/server/blueprints/variants/templates/variants/variants.html
=> Fix gene variant hgvs

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/clinvar.html
=> Include ClinVar variants into a scrollable div on Case page

CHANGELOG.md, Dockerfile, Dockerfile-server
=> Fix gunicorn workers booting by modifying Dockerfiles to use python bullseye

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/forms.py, scout/server/blueprints/institutes/templates/overview/gene_variants.html, scout/server/blueprints/institutes/views.py, tests/server/blueprints/institutes/test_institute_views.py
Partial fix for #3946
New button to export variants from `Search SNVs and Indels` Page:
<details> …
=> Export 500 gene variants resulting from SNVs and Indels queries

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html, scout/server/links.py
This PR adds a functionality or fixes a bug. Fix #4007 - search pubmed for gene from variant.
Single gene symbol
Or OR aliases if known.
<details> …
=> Add PubMed link

CHANGELOG.md, scout/server/blueprints/public/templates/public/index.html
This PR removes the call to the Netlify function that tracks browser version
<details> …
=> Remove call to track browsers

CHANGELOG.md, README.md
=> Fixed Weasyprint installation howto link

CHANGELOG.md, docs/CODEOWNERS
=> Fix #4038 - remove legacy incorrectly formatted codeowners file

CHANGELOG.md, scout/commands/update/hpo.py, scout/load/hpo.py
=> Fix #2294 - drop HPO term collection later into update

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/variant_details.html
=> Fix visualization of cancer variants where cancer case has no affected

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/utils.html
Fix #4060 - variant link for MEI on causatives page
✅ <img width="594" alt="Screenshot 2023-09-01 at 12 54 41" src="https://github.com/Clinical-Genomics/scout/assets/758570/18168832-cab9-4688-9cf9-37cf52b24b24">
<details>
1. `ssh …
=> MEI variant link on causatives page

CHANGELOG.md, scout/server/config.py
- Do not launch the Bionano extension if these settings are not customised
<details> …
=> Bionano settings commented out by default in scout settings

CHANGELOG.md, docs/admin-guide/bionano_access_integration.md
This PR adds a few sentences to the BioNano docs.
<details> …
=> Minor update to bionano docs

.github/workflows/build_and_publish.yml, .github/workflows/keep_a_changelog.yml, .github/workflows/linting_and_fixing.yml, .github/workflows/linting_only.yml, .github/workflows/server_stage_docker_push.yml, .github/workflows/tests_and_cov.yml, .github/workflows/vulture.yml, .github/workflows/woke.yml, CHANGELOG.md
=> Fix #4092 - github actions, tests with newer python

CHANGELOG.md, Dockerfile, Dockerfile-server, requirements.txt
Switch from python 3.8 to python 3.11
<details>
1. Start the scout service with the …
=> Upgrade python to 3.11 in Docker images

CHANGELOG.md, scout/load/hpo.py, scout/parse/hpo_mappings.py
=> Fix missing disease-associated HPO terms

CHANGELOG.md, scout/adapter/mongo/case.py, scout/adapter/mongo/event.py, scout/adapter/mongo/omim.py, scout/server/blueprints/diagnoses/controllers.py, scout/server/blueprints/diagnoses/views.py, tests/adapter/mongo/test_diagnosis_handler.py, tests/adapter/mongo/test_event_handling.py
=> Mitigate memory exhaustion by optimising disease terms queries 

CHANGELOG.md, scout/parse/omim.py
**Simpler to review and test after #4156** 
FIx #4162 -> Parse both old and new format of genemap2.txt files
<details> …
=> Fix genemap2 parsing

CHANGELOG.md, scout/demo/643594.ped_check.csv, scout/server/blueprints/cases/templates/cases/individuals_table.html
=> Fix #4168 - make kinship check more obvious

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
This PR adds a functionality by adding a scrollbar to the OMIM-table if more than 700px.
<details> …
=> add-scroll-to-omim-table

CHANGELOG.md, scout/parse/matchmaker.py, scout/server/config.py
=> Fix MME submissions page crashing

CHANGELOG.md, scout/server/static/bs_styles.css
This PR makes visited links remain the same color if they are styled as btn.
<details> …
=> Visited links color

CHANGELOG.md, scout/adapter/mongo/filter.py
=> Fix saving mei filters

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/blueprints/cases/templates/cases/institutes_sidebar.html, scout/server/blueprints/cases/templates/cases/matchmaker.html, scout/server/blueprints/cases/templates/cases/utils.html, scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html, scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html, scout/server/blueprints/panels/templates/panels/panels.html, scout/server/blueprints/phenomodels/templates/phenomodels.html, scout/server/blueprints/variant/templates/variant/cancer-variant.html, scout/server/blueprints/variant/templates/variant/sv-variant.html, scout/server/blueprints/variant/templates/variant/utils.html, scout/server/blueprints/variant/templates/variant/variant.html, scout/server/templates/bootstrap_global.html, scout/server/templates/report_base.html
=> Test update fontwesome

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/individuals_table.html
=> Gens button case analysis type

CHANGELOG.md, scout/server/templates/report_base.html
=> Fix extra chars on general report

CHANGELOG.md, scout/adapter/mongo/query.py, scout/constants/query_terms.py, scout/parse/variant/variant.py, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/utils.html
This PR closes https://github.com/Clinical-Genomics/scout/issues/4269
<details>
1. …
=> Update fusion filters

CHANGELOG.md
Something happened to the changelog when the last PR was merged. This PR is restoring it to its original format.
<details> …
=> Restore changelog format

CHANGELOG.md, scout/server/links.py
=> Fix Alamut link for MT variants in build 38

CHANGELOG.md, scout/server/blueprints/variants/forms.py, scout/server/blueprints/variants/templates/variants/utils.html
=> Fix #4300 - DecimalFields stepping

CHANGELOG.md, scout/commands/update/user.py
- Fix app not raising error when tying to update a user that doesn't exist (fix  #4299)
<details> …
=> Fix updating unexisting user crash

CHANGELOG.md, requirements.txt
=> Thaw cryptography

CHANGELOG.md, scout/server/links.py
=> GnomAD 38 v4 links

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/static/bs_styles.css
- Fix #4339 
- Fix #4340
Fix the submenu caret symbols
And also the non collapsing entries on the sidebar
With research requested (non-hiding):
Not 100% we really need that partial collapse - you can't do much from the collapsed state anyway, and it is kind of big as a placeholder to remind it exists. But oh well, it's kind of good looking, and total hiding with like a menu button is not easy in the layout.
<details> …
=> Fix sumenu icon fa5

CHANGELOG.md, scout/adapter/mongo/disease_terms.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/cases/templates/cases/phenotype.html, tests/adapter/mongo/test_diagnosis_handler.py
=> Fix number of phenotypes and genes from case diagnoses

CHANGELOG.md, scout/server/app.py, scout/server/blueprints/clinvar/controllers.py, scout/server/blueprints/clinvar/form.py, scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- Fix #4378 
Current situation (bugged). Take for instance a case with these diagnoses - 1 OMIM and 1 ORPHA term
What you see on the ClinVar multistep form: ⛔ 
<hr>
After this fix: 🆗 
And  🆗 
<details>
1. (optional) …
=> Associate ClinVar variants with Orphanet conditions

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- Partially fixes #4373 by checking if there is at least one associated condition to a variant appended to a ClinVar submission
Next step, in separate PRs:
- Add multipleConditionExplanation field
- Fix form that auto-fills condition values when case has both OMIM and ORPHA terms associated
<hr>
<details> …
=> Introduce a super-simple ClinVar multistep validation system and validate associated condition

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/utils.html, scout/server/blueprints/variant/templates/variant/utils.html
=> Fix diseases associated to partial causatives (style, links)

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html
This PR contains visual improvements of the case_report including:
Closing of visible gap in the corners between the card header and card border
Re-aligning of header contents which sometimes overflowed to the left of the card border
Re- aligning of bordered tables located inside a table.
<details>
1. `sudo …
=> Updated styling of case_report to align card contents and headers

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/utils.html
=> Revert style of pinned variants window on case page

.github/workflows/build_and_publish.yml, .github/workflows/linting_and_fixing.yml, .github/workflows/linting_only.yml, .github/workflows/tests_and_cov.yml, .github/workflows/validate_internal_docs_links.yml, CHANGELOG.md, docs/admin-guide/containers/systemd.md
- Fix #4436 - naively update versions. Let's see if something more needs changing. 😊 
<details> …
=> Fix #4436 - update GitHub Actions

CHANGELOG.md, scout/server/blueprints/variant/controllers.py, scout/server/blueprints/variant/utils.py
=> Display common/uncommon/rare on mei variant summary

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py
=> 'Institutes to share cases with' select displays institute names and IDs

CHANGELOG.md, scout/constants/case_tags.py
Add an incidental finding case tag (as per discussion with the geneticists this morning, who were uncertain how to tag a case that had an incidental/secondary finding as partial causative).
<details>
1. (optional) …
=> Fix #4491 - case incidental finding tag

CHANGELOG.md, scout/server/blueprints/variants/controllers.py
=> Fix bug exporting variants without rank score

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/cancer-variant.html, scout/server/blueprints/variant/templates/variant/sv-variant.html, scout/server/blueprints/variant/templates/variant/utils.html, scout/server/blueprints/variant/templates/variant/variant.html
=> Display custom annotations also on cancer variant page

CHANGELOG.md, scout/server/blueprints/panels/templates/panels/panel.html
- Final piece of scout-chanjo2 integration (closes #4000)
- Adds a link to the genes overview on gene panel page
<details>
1. …
=> Link to chanjo2 genes overview on gene panel page

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/gene_panel.html
=> Fix button size on HPO panel

CHANGELOG.md, scout/constants/__init__.py
=> Fix #4541 - DUX4::IGH BALSAMIC SV caller tag

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html
=> Fix cancer_rank_options typo in case report

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/variants/templates/variants/components.html, scout/server/blueprints/variants/templates/variants/fusion-variants.html
- Closes #4567 
Before:
After:
<details> …
=> Changed case report to display more info for fusion variants

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/cases.html
- I noticed a typo in a link name on caseS page
<details> …
=> Fix link name on caseS page

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/utils.html
- Partial fix for #4400
<details>
1. Start …
=> Block ClinVar submission of somatic variants, to reflect changes in ClinVar API

.github/workflows/tests_and_cov.yml, CHANGELOG.md
=> Fix installation of wkhtmltopdf in GitHub action

CHANGELOG.md, scout/constants/clinvar.py
OR
- Fix #4586
<details>
1. Start the …
=> Fix ClinVar form parsing to not include : in conditionType.id when condition is Orphanet

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- Fix both steps windows legends and HGSVs #4580 
Main branch:
<hr>
This branch:
<details> …
=> Improved visibility of ClinVar form in dark mode

CHANGELOG.md, scout/server/blueprints/diagnoses/controllers.py, scout/server/blueprints/diagnoses/views.py
=> Fix diagnoses API search crashing with empty search string

.github/workflows/tests_and_cov.yml, CHANGELOG.md, Dockerfile, Dockerfile-server, requirements.txt, scout/server/app.py, scout/server/blueprints/panels/views.py, scout/server/blueprints/variant/controllers.py, tests/server/conftest.py
=> Unfreeze werkzeug

CHANGELOG.md, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/utils.py, tests/server/test_server_utils.py
=> Hide mtDNA and coverage reports for WTS cases

.github/workflows/tests_and_cov.yml, CHANGELOG.md, requirements-dev.txt
=> Attempt at speeding up tests

CHANGELOG.md, scout/adapter/mongo/case.py
- Fix loading also research variants when loading a case (fix #4661 )
<details> …
=> Fix automatically loading research variants when loading a case

CHANGELOG.md, scout/build/genes/hgnc_gene.py, scout/load/hgnc_gene.py, scout/models/hgnc_map.py, tests/adapter/conftest.py, tests/adapter/mongo/test_gene_handler.py, tests/build/test_build_hgnc_gene.py, tests/conftest.py
- Converted the HgncGene class into a pydantic class
<details> …
=> Pydantic gene

CHANGELOG.md, scout/server/links.py
=> Fix gene links

CHANGELOG.md, requirements.txt
=> Fix #4688 - unfreeze werkzeug to finally get >v3.0

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/blueprints/cases/templates/cases/utils.html, scout/server/templates/utils.html
=> Replace broken "remove" icon

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
- There was a new major release of igv.js yesterday ---> https://github.com/igvteam/igv.js/releases/tag/v3.0.0
<details>
1. Stop …
=> Update igv.js to v 3.0.1

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/utils.html
Before:
After:
<details>
1. Start the …
=> Sort IGV tracks - fix #4726

.wokeignore, CHANGELOG.md
Before it gets super annoying -->
<details>
1. Start the scout service with the branch …
=> Update wokeignore to avoid unfixable warning

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/buttons.html
=> Fix #4738 - IGV sashimi routing hint

CHANGELOG.md, scout/parse/variant/frequency.py, tests/parse/test_frequency.py
- Partial fix to #4742 
<details>
1. Start …
=> Parse gnomad keys from variants annotated with echtvar

CHANGELOG.md, scout/server/blueprints/dashboard/static/charts.js, scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
This PR updates Chart.js to the latest release version, slightly refactoring code on dashboard to retain current output.
<details> …
=> Update Chart.js to v4.4.3

CHANGELOG.md, scout/server/blueprints/omics_variants/controllers.py, scout/server/blueprints/omics_variants/views.py, tests/server/blueprints/omics_variants/omics_variants.py, tests/server/blueprints/variants/test_variants_views.py
- Closes #4701 
<details>
1. Start the …
=> Download -omics variants

CHANGELOG.md, scout/server/templates/bootstrap_global.html
- Closes #4759
<details>
1. Start the …
=> Switch to non-kit FontAwesome 6

CHANGELOG.md, scout/server/templates/utils.html
- Closes #4764 
<details>
1. Start the …
=> Show time (hours and minutes) additionally to date on comments and activity panel

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html, scout/server/blueprints/cases/templates/cases/phenotype.html
=> Re-style case HPO terms to have one phenotype per line

CHANGELOG.md, scout/adapter/mongo/hgnc.py, scout/load/panel.py
=> Fix panelapp updating error

CHANGELOG.md, scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html, scout/server/blueprints/variants/templates/variants/components.html
=> Fix style of SNVs and SVs buttons on WTS Outliers page

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html, scout/server/blueprints/variant/templates/variant/buttons.html, scout/server/blueprints/variant/templates/variant/components.html, scout/server/blueprints/variant/templates/variant/sv-variant.html
Before:
After:
<details>
1. Start the …
=> Fix #4780 - RNA aln genome build tooltips

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
=> Update igv.js to 3.0.4.

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
- Closes #4787
<details>
1. Start the …
=> Show genes track also when RNA alignments are present without splice junctions tracks

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
=> Fix #4790 - trailing comma

CHANGELOG.md, scout/build/variant/gene.py, scout/load/setup.py
- Fix #4802
After the fix:
<details>
1. …
=> Fix setup database command

.github/workflows/tests_and_cov.yml, CHANGELOG.md
=> Fix coverage upload

CHANGELOG.md, scout/adapter/mongo/omics_variant.py, scout/build/individual.py, scout/models/omics_variant.py
=> Display WTS outliers again

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
=> Patch IGV.js to v3.0.5

CHANGELOG.md, docs/admin-guide/login-system.md, docs/admin-guide/setup-scout.md
=> Fix broken heading anchors pointing to admin login markdown page

CHANGELOG.md, scout/server/app.py, scout/server/blueprints/login/views.py
- Addresses the following security advisory --> https://github.com/Clinical-Genomics/scout/security/advisories/GHSA-3x45-2m34-x95v
<details> …
=> Avoid open login redirect attacks via next

CHANGELOG.md, scout/server/blueprints/panels/templates/panels/panel.html, scout/server/blueprints/panels/templates/panels/panels.html
=> Include both creation and last modification dates in gene panels pages

CHANGELOG.md, scout/server/blueprints/panels/controllers.py, scout/server/blueprints/panels/templates/panels/panels.html
- Addresses the following [vunerability](https://github.com/Clinical-Genomics/scout/security/advisories/GHSA-24xv-q29v-3h6r)
<details> …
=> Fix regular expression check in new panel form

CHANGELOG.md, scout/server/blueprints/panels/templates/panels/panels.html
Before:
After:
<details>
1. Start the …
=> Remove a duplicated panel version history list

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html
=> Fix #4847 - retired SPANR link

CHANGELOG.md, scout/server/links.py
=> Fix alamut link error

CHANGELOG.md, scout/constants/igv_tracks.py
=> Update igv.js chrom alias files to include alias for chrom M

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- Closes #4874 
<details>
1. Start the …
=> Preselect ClinVar ACMG criteria according to the variant's ACMG classification

CHANGELOG.md, scout/adapter/mongo/case.py
=> Fix search similar cases

CHANGELOG.md, docs/admin-guide/load-config.md, scout/adapter/mongo/case.py, scout/build/case.py, scout/constants/case_tags.py, scout/demo/643594.config.yaml, scout/models/case/case_loading_models.py, scout/server/app.py, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Add an RNA delivery report.
<details>
1. …
=> Fix #4888 - add RNA delivery report

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
- Closes #4910 
<details>
1. Start the …
=> Do not show ORPHA inheritance on variant page

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/blueprints/panels/templates/panels/panel.html
- Adds a link to the new MANE overview on the case side panel
- Adds a link also on the gene panel page
<details>
1. Stop the …
=> Chanjo2 MANE coverage overview

CHANGELOG.md, scout/server/blueprints/panels/templates/panels/gene-edit.html, scout/server/blueprints/panels/templates/panels/panel.html
- Closes #4933 
<hr>
<details>
1. Start …
=> Move panel cols

CHANGELOG.md, scout/adapter/mongo/panel.py, scout/server/blueprints/panels/views.py
=> Fix updating genes in a panel with custom info

CHANGELOG.md, scout/server/blueprints/panels/controllers.py, scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html
=> Fix pdf panel download

CHANGELOG.md, scout/constants/variant_tags.py, scout/server/blueprints/institutes/controllers.py
=> Fix #4938 - show more filter categories for filterS

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py
- Fix #4942  - search limit went into advanced form
<details> …
=> Fix #4942 - respect search limit

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/matchmaker.html
- Fix #4940 
Tested on stage with [this case](https://scout-stage.scilifelab.se/cust101/F0000310/mme_matches)
<details>
1. Stop …
=> Improve visibility of MME matches on dark mode

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/utils.html
=> Fix variant gene panel links

CHANGELOG.md, scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
Adds a position copy button to the WTS outliers page.
Close #4980
Worked as intended on testing. Copied from the button:
```
7:124532319-124532434
```
<details> …
=> WTS outlier copy to clipboard

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
=> Fix #4977 - update IGV.js to 3.0.9

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
- Closes #4997 
<details>
1. Start the …
=> Fix ClinVar form to accept MedGen phenotypes

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
- Closes #4999 
<details>
1. Start the …
=> Expand ClinVar submission description section to display full info

CHANGELOG.md, scout/constants/acmg.py
- Fix #5001 
Also added `noreferrer` directives to the documentation links on the ACMG page. Quite friendly destinations, but they are external after all.
<details> …
=> Fix #5001 - Jarvik for ACMG PP1 modification

CHANGELOG.md, scout/server/blueprints/dashboard/controllers.py
- Clearer institute names on dashboard select (closes #5018 )
<details> …
=> Display institute _id + display name on dashboard filters

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
=> Fix broken ClinVar submission status enquiry for all submissions after the latest

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/utils.html
- Closes #5044 and closes #5043 
<details> …
=> Merge `Qual` and `Callers` cell on cancer SNVs page

CHANGELOG.md, scout/server/blueprints/variants/controllers.py
- Fix #5042 
##HAVEN'T TESTED IT YET!
<details> …
=> Fix missing repeat locus info on STRs export

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html
=> Fix #5058 - structural variantS header

CHANGELOG.md, scout/parse/variant/genotype.py
=> Fix stranger missing loci

CHANGELOG.md, docs/admin-guide/panelapp_panels.md
- Closes #5055
<details>
1. Start the …
=> Fixed documentation of PanelApp panels to reflect the latest changes in the command line

CHANGELOG.md, scout/server/blueprints/panels/templates/panels/panels.html
- Closes #5067
<hr>
<hr>
<hr>
<hr>
<details> …
=> Improvements on gene panels page

CHANGELOG.md, scout/parse/panelapp.py, scout/server/blueprints/genes/templates/genes/gene.html
- Closes #5036
<details>
1. Start the …
=> Panelapp links

CHANGELOG.md, scout/adapter/mongo/query.py, scout/commands/delete/delete_command.py
- Closes #5088 
Where appo.txt contains the following lines:
<details> …
=> Add more options to the variants delete command

CHANGELOG.md, Dockerfile, Dockerfile-server, scout/server/extensions/panelapp_extension.py
=> Use the clinicalgenomics/python3.11-venv:1.0 image everywhere in the Dockerfiles

CHANGELOG.md, scout/adapter/mongo/variant.py
=> Fix missing classifications in case report

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other-issue.md, CHANGELOG.md
- Closes #4962
<details>
1. Start the …
=> Add a warning to not to post sensitive info on issues

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html, scout/server/blueprints/cases/templates/cases/index.html
- Fix #5102 
Share
Revoke
<details>
1. …
=> Fix #5102 - customer id in sharing dialog

CHANGELOG.md, scout/server/blueprints/panels/controllers.py, scout/server/blueprints/panels/templates/panels/panel.html
=> Fix updating gene panels via file

.github/workflows/build_and_publish.yml, .github/workflows/linting_and_fixing.yml, .github/workflows/linting_only.yml, .github/workflows/tests_and_cov.yml, .github/workflows/validate_internal_docs_links.yml, CHANGELOG.md, Dockerfile, Dockerfile-server, scout/commands/serve.py
- Switch to Python 3.12 in Dockerfiles and automatic tests
By switching to python:3.12-slim-bookworm, the health of the image is improving:
<details> …
=> Switch to Python 3.12 in Dockerfiles and automatic tests

CHANGELOG.md, scout/commands/serve.py, scout/server/blueprints/variant/templates/variant/ccv.html
We might as well I guess:
- Fix #5109 
<details> …
=> Fix #5109 - CCV Horak link in new window

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/tx_overview.html
- Closes #4995 
<details>
1. Start the …
=> Truncate protein change descriptions on variant page, RefSeq transcripts panel

CHANGELOG.md, scout/server/blueprints/cases/views.py
=> Fix #5147 - MT report temp dir generation

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html
=> Clearer links to Richards 2015

CHANGELOG.md, scout/load/panelapp.py
- Closes #5161 : Allow using all types by typing "all" in the prompt:
<details> …
=> Include 'all' option to update PanelApp Green panel from all source types easily

CHANGELOG.md, scout/adapter/mongo/hgnc.py, scout/load/panelapp.py, scout/parse/panelapp.py
- Tentative fix to #5163 
<details>
1. …
=> Parse HGNC IDs directly from PanelApp when updating PanelApp panels

CHANGELOG.md, scout/load/panelapp.py
=> Fix loading of PanelApp panels

CHANGELOG.md, docs/admin-guide/load-config.md, scout/build/case.py, scout/demo/rnafusion.load_config.yaml, scout/models/case/case_loading_models.py, scout/parse/case.py, scout/server/blueprints/variant/templates/variant/acmg.html
- Closes #4892
<details>
1. Start the …
=> Case status on loading

CHANGELOG.md, scout/adapter/mongo/case.py, scout/build/case.py, scout/server/blueprints/cases/controllers.py, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
- Closes #4963
<details>
1. Start the …
=> Display version of scout used when loading a case on case page and general report

CHANGELOG.md, scout/adapter/mongo/case.py, scout/commands/load/variants.py
- Fixes #5224 
<details>
1. Start the …
=> Set case as research case if it contains any type of research variants

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
- Fix #5230 
Good starting point for LRS.
Also very useful for the STR view
Does make a regular SNV view a bit noisier - SR for a few extra soft clips shown, LRS since methylation sites may be present on the view, but I'd say it is not by that much, and can of course easily be disabled.
<details>
1. `ssh …
=> Fix #5230 - IGV v3.1.4 and more aln track defaults

CHANGELOG.md, scout/commands/load/variants.py, scout/server/blueprints/cases/templates/cases/case.html
- Closes #5221
<details>
1. Start the …
=> Load research WTS outliers using the load variants  command

CHANGELOG.md, scout/constants/igv_tracks.py, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
=> Fix #5250 - update IGV.js to 3.2.0

CHANGELOG.md, scout/adapter/mongo/filter.py, scout/server/blueprints/omics_variants/views.py, scout/server/blueprints/variants/controllers.py, scout/server/blueprints/variants/views.py
- Closes #5253 
<details>
1. Start the …
=> Ordered filters

CHANGELOG.md, docs/admin-guide/load-config.md, scout/build/individual.py, scout/demo/cancer.load_config.yaml, scout/models/case/case.py, scout/models/case/case_loading_models.py, scout/server/blueprints/cases/templates/cases/individuals_table.html
This PR adds a functionality or fixes a bug. Closes #5247
<details> …
=> Make HRD a config parameter and display for cancer cases.

CHANGELOG.md, scout/server/blueprints/alignviewers/controllers.py, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html, scout/server/utils.py
- Closes #5270 
<details>
1. Start the …
=> Hide soft clips in IGV for wes and panel samples

CHANGELOG.md, scout/demo/643594.config.yaml, scout/demo/643594.somalier.ancestry.tsv, scout/parse/case.py
```
[daniel.nilsson@hasta:trustingchipmunk] [S_base] $ scout load case -u scout_load_somalier.yaml
```
Before:
After:
<details> …
=> Fix demo file and operator priority

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case.html
=> Case page patch for research cases without WTS outliers

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
=> Fix #5308 - dont default to twocolor

CHANGELOG.md, scout/utils/ensembl_rest_clients.py, tests/utils/test_ensembl_rest_clients.py
=> Error message when requests to Ensembl (liftover) fail

CHANGELOG.md, docs/admin-guide/login-system.md
- Closes #5341
<details>
1. Start the …
=> Keycloak docs

CHANGELOG.md, scout/utils/ensembl_biomart_clients.py
=> Fix schug url

CHANGELOG.md, scout/constants/igv_tracks.py
=> Fix missing MT genes from the IGV track

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html, scout/server/links.py
Adds a link to cancerhotspots to external link panel for cancer cases.
<details>
1. …
=> Add link to cancerhotspots.org

CHANGELOG.md, scout/server/extensions/chanjo2_extension.py
- Closes #5363 
<details>
1. Start the …
=> Chanjo2 gene coverage report reflects type of analyses

CHANGELOG.md, docs/admin-guide/export.md
- Closes #5051
<details>
1. Start the …
=> Add the documentation on how to export data using the CLI

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
- Closes #5379 
<details>
1. Start the …
=> Update PR template instructions to not stop target when deploying a test branch

CHANGELOG.md, scout/adapter/mongo/case.py
- Closes #5333 
<details>
1. Start the …
=> Keep phenotype-related info on case reupload with --keep-actions tag

CHANGELOG.md, scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
=> Fix step back in ClinVar multistep form

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/utils.html
=> Truncate all compounds names on compounds popup table

CHANGELOG.md, scout/adapter/mongo/variant_loader.py, tests/adapter/mongo/test_variant_loader.py
=> Variants loader progress bar

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html, scout/server/blueprints/variant/templates/variant/sv-variant.html, scout/server/blueprints/variants/templates/variants/indicators.html, scout/server/static/bs_styles.css
- Fix #5418 
- Fix #5417 
<details> …
=> Fix matching ranked

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/utils.html
=> Fix x compounds

CHANGELOG.md, scout/server/blueprints/panels/views.py
=> Institutes by ID on PanelS page

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/indicators.html
=> Simplify previous classifications badges on variantS page

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/indicators.html, scout/server/blueprints/variants/templates/variants/utils.html
- Avoid also repeating CCV classification badges on cancer variants
<details> …
=> Avoid also repetated CCV classification badges on cancer variants page

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/utils.html
=> Remove ClinVar add button for unsupported MEI variants

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/variant/templates/variant/variant_details.html
=> Reuse the variant frequencies table from variant page on case reports

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/utils.html
=> Fix #5480 - UCSC link for SV breakpoint in hg38

CHANGELOG.md, scout/server/blueprints/cases/templates/cases/case_report.html, scout/server/blueprints/variant/templates/variant/variant_details.html
- Closes #5476. Let's start by displaying the archived local frequencies. According how many loqus instances you have, the non archived obs table could be quite big and it's occupying a lot of space.. I don't know, perhaps this is enough?
<details>
1. `sudo -iu …
=> Archived local frequencies on general report

CHANGELOG.md, scout/constants/igv_tracks.py, scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
=> Fix #5494 - IGV.js genomes.json URL intermittent errors

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/utils.html
=> Enforce numeric values in Limit field of cases search

CHANGELOG.md, scout/server/app.py, scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
=> Log2 fold change + fold change values on WTS page

CHANGELOG.md, scout/parse/variant/genotype.py, tests/parse/test_parse_genotype.py
- Fix #5540 
Local
Stage
<details> …
=> Str read support

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/institute_sidebar.html
=> Clinvar sidebar margin

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/variant_details.html
- Undefined VQ gets rounded
<details> …
=> Fix rounding missing SV VQ

CHANGELOG.md, scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/mei-variants.html, scout/server/blueprints/variants/templates/variants/str-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/utils.html, scout/server/blueprints/variants/templates/variants/variants.html
=> Always display number of available/displayed variants on variantS pages

CHANGELOG.md, scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
A new IGV.js version has been released.
Display and locus search all good on local:
<details> …
=> Bump IGV.js version to 3.4.1

CHANGELOG.md, scout/server/blueprints/panels/controllers.py
- closes #5576 
WIth this panel: https://scout-stage.scilifelab.se/panels/680b73d93d10e2fcc4378ce6
Before and after the fix:
<details> …
=> Fix downloaded panels names sanitization

CHANGELOG.md, pyproject.toml, uv.lock
=> Fix deprecated flask login

CHANGELOG.md, scout/commands/load/user.py, scout/commands/update/user.py, scout/constants/user.py, scout/load/user.py, scout/server/blueprints/login/controllers.py, scout/server/blueprints/login/forms.py, scout/server/blueprints/login/templates/login/users.html, scout/server/blueprints/login/views.py, tests/server/blueprints/login/test_controllers.py, tests/server/blueprints/login/test_views.py
- This is a partial fix to #5159
<details> …
=> New form to create users on the general users page (visible to admin users only)

CHANGELOG.md, scout/server/blueprints/institutes/templates/overview/cases.html, scout/server/blueprints/institutes/templates/overview/utils.html, scout/server/blueprints/variants/templates/variants/utils.html, scout/server/static/bs_styles.css
=> Stretch cases link

CHANGELOG.md, scout/server/blueprints/login/templates/login/users.html, scout/server/blueprints/login/views.py, tests/server/blueprints/login/test_views.py
- Edit a user directly from the main users page (closes #5159)
<details> …
=> Edit an existing user using a web form from main users page

CHANGELOG.md, scout/constants/ccv.py
Some conflicts between the criteria for the ClinGen-CGC-VICC Oncogenicity classification as defined in [Horak et al](https://doi.org/10.1016/j.gim.2022.01.001) were missing, and in one case, mixed up.
<details>
1. …
=> Fix CCV conflicts

CHANGELOG.md, scout/constants/filters.py
- Fixes partially #5628 
<details> …
=> Improve Clinical Filter for WTS outliers

CHANGELOG.md, scout/adapter/mongo/query.py, scout/constants/query_terms.py, scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html, scout/server/blueprints/variants/forms.py, tests/adapter/mongo/test_query.py
=> New "P-value", "Abs log₂FC" and "abs ΔΨ" WTS filters options

CHANGELOG.md, scout/commands/base.py
=> Fix yaml db name parsing

CHANGELOG.md, scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html, scout/server/blueprints/variants/templates/variants/cancer-variants.html, scout/server/blueprints/variants/templates/variants/fusion-variants.html, scout/server/blueprints/variants/templates/variants/mei-variants.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, scout/server/blueprints/variants/templates/variants/variants.html, scout/server/templates/utils.html
=> Fix #5667 - dont follow clickable row for checkbox

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
This PR adds a functionality or fixes a bug: 🤛 📖 -> First
<details> …
=> Fix PR template typo

CHANGELOG.md, scout/server/blueprints/variant/templates/variant/components.html
=> ACMG and CCV classification open in a new tab

CHANGELOG.md, scout/adapter/mongo/hgnc.py, scout/constants/indexes.py, scout/server/blueprints/variant/controllers.py, scout/server/blueprints/variant/templates/variant/components.html, scout/server/blueprints/variant/templates/variant/sv-variant.html, scout/server/blueprints/variant/templates/variant/utils.html, scout/server/blueprints/variants/templates/variants/sv-variants.html, tests/adapter/mongo/test_gene_handler.py
- Fix #2969
It appears common to have very large RNA genes spanning a particular position. I've put the ones that don't have protein ids on a separate collapse not to swamp the display.
<details> …
=> SV edge gene

CHANGELOG.md, scout/server/blueprints/institutes/controllers.py, scout/server/blueprints/institutes/templates/overview/gene_variants.html, scout/server/blueprints/institutes/templates/overview/utils.html, scout/server/blueprints/variants/templates/variants/utils.html
- Fix #5728 
Borrowed the display style from causative/verified variants, adding some icons:
<details> …
=> Fix #5728 - zygosity on gene variants page
